### ISSUE TITLE
hallo

### ISSUE THREAD

**Issue by zhanwu123** [alf45tar/PedalinoMini#100]

**Comment by alf45tar** [comment]
Hi zhanwu123

**Comment by zhanwu123** [comment]
sorryl

**Comment by zhanwu123** [comment]
i am a Chinese，English is not good

**Comment by zhanwu123** [comment]
your pedalino i‘m in the imitation

**Comment by zhanwu123** [comment]
Many problems on PlatformIOIDE to build，I am not electric professional。

**Comment by alf45tar** [comment]
If you need support you should be more specific on your request

**Comment by zhanwu123** [comment]
![Uploading 0307FBE1-7B3E-4A6C-89E1-FF4873524FC7.jpeg…]()
