### ISSUE TITLE
After the completion of the upload, step 5 and 6

### ISSUE THREAD

**Issue by zhanwu123** [alf45tar/PedalinoMini#102]
> Executing task in folder PedalinoMini: C:\Users\Administrator\.platformio\penv\Scripts\platformio.exe device monitor <

--- Available filters and text transformations: colorize, debug, default, direct, esp32_exception_decoder, hexlify, log2file, nocontrol, printable, send_on_enter, time
--- More details at http://bit.ly/pio-monitor-filters
--- Miniterm on COM4  115200,8,N,1 ---
--- Quit: Ctrl+C | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---
2:57

rst:ChipRevision 1, CPU Freq 240 MHz, SDK Version v3.2.3-14-gd3e562907
Flash Size 4194304, Flash Speed 80000000 Hz
Internal Total Heap 329204, Internal Free Heap 300416
PSRAM Total Heap 0, PSRAM Free Heap 0
PlatformIO Built Environment: esp32doit-devkit-v1-wifi
_________           .___      .__  .__                 _____  .__       .__
 ___ ________________    ___
\______  \ ____   __| _/____  |  | |__| ____   ____   /     \ |__| ____ |__|
/  / \__    ___/     \   \  \
|     ___// __ \ / __ |\__  \ |  | |  |/    \ /  _ \ /  \ /  \|  |/    \|  |  /  /    |    | /  \ /  \   \  \
|    |   \  ___// /_/ | / __ \|  |_|  |   |  (  <_> )    Y    \  |   |  \  | (
 (     |    |/    Y    \   )  )
|____|    \___  >____ |(____  /____/__|___|  /\____/\____|__  /__|___|  /__|  \  \    |____|\____|__  /  /  /
              \/     \/     \/             \/               \/        \/
\__\                 \/  /__/

   (c) 2018-2020 alf45star
                                                                      https://github.com/alf45tar/PedalinoMini

Hostname: 60C40A24
PSRAM not found
Internal Total Heap 329204, Internal Free Heap 300416
PSRAM Total Heap 0, PSRAM Free Heap 0
'nvs' partition was successfully initialized
Reading NVS Global ... done
[NVS][Global][Device Name]:      60C40A24
[NVS][Global][Boot Mode]:        2
[NVS][Global][STA SSID]:
[NVS][Global][STA Password]:
[NVS][Global][AP SSID]:          Pedalino-60C40A24
[NVS][Global][AP Password]:      60C40A24
[NVS][Global][Bootstrap Theme]:  bootstrap
[NVS][Global][Current Profile]:  0
[NVS][Global][Tap Dance Mode]:   0
[NVS][Global][Bank Switch]:      0
[NVS][Global][Single Time]:      200
[NVS][Global][Double Time]:      400
[NVS][Global][Long   Time]:      500
[NVS][Global][Repeat Time]:      500
[NVS][Global][Encoder Sensit]:   5
[NVS][Global][Blynk Cloud]:      0
[NVS][Global][Blynk Token]:
[NVS][Global][Ladder]:           Ladder 0 Threshold 497 Tolerance 82
[NVS][Global][Ladder]:           Ladder 1 Threshold 660 Tolerance 47
[NVS][Global][Ladder]:           Ladder 2 Threshold 752 Tolerance 33
[NVS][Global][Ladder]:           Ladder 3 Threshold 816 Tolerance 31
[NVS][Global][Ladder]:           Ladder 4 Threshold 876 Tolerance 31
[NVS][Global][Ladder]:           Ladder 5 Threshold 945 Tolerance 35

Boot BLE
USB MIDI started
DIN MIDI started
Internal Total Heap 329012, Internal Free Heap 299308
Loading profile ...
Reading NVS Profile A ... done
Pedal autosensing...
Pedal  1   autosensing disabled
Pedal  2   autosensing disabled
Pedal  3   autosensing disabled
Pedal  4   autosensing disabled
Pedal  5   Tip Pin 12 Value  680    Ring Pin 32 Value  901 ANALOG POLARITY+
Pedal  6   Tip Pin 13 Value  570    Ring Pin 33 Value  871 ANALOG POLARITY+
Bank  1
Pedal  1     MIDI         MOMENTARY1   PRESS_1       POLARITY+   NOTE_ON_OFF
      60   Channel  1   Pin D25
Pedal  2     MIDI         MOMENTARY1   PRESS_1       POLARITY+   NOTE_ON_OFF
      62   Channel  1   Pin D26
Pedal  3     MIDI         MOMENTARY1   PRESS_1       POLARITY+   NOTE_ON_OFF
      64   Channel  1   Pin D27
Pedal  4     MIDI         MOMENTARY1   PRESS_1       POLARITY+   NOTE_ON_OFF
      65   Channel  1   Pin D14
Pedal  5     MIDI         ANALOG       PRESS_1       POLARITY-   CONTROL_CHANGE      12   Channel  1   Pin A32 D12
Pedal  6     MIDI         ANALOG       PRESS_1       POLARITY-   CONTROL_CHANGE      13   Channel  1   Pin A33 D13
Pedal  5 calibration min 0
Pedal  5   input 0 output 127 velocity 0.11
Pedal  6 calibration min 62
Pedal  6 calibration max 62
Pedal  6   input 62 output 127 velocity 0.11
Pedal  6 calibration min 0
MTC None
Pedal  5 calibration max 68
Pedal  5   input 68 output 0 velocity -4.76
CONTROL CHANGE.....Code  12......Value   0.....Channel  1
CONTROL CHANGE.....Code  12......Value   0.....Channel  1
Pedal  5 calibration max 89
Pedal  6 calibration max 66
Pedal  6   input 66 output 0 velocity -4.26
CONTROL CHANGE.....Code  13......Value   0.....Channel  1
CONTROL CHANGE.....Code  13......Value   0.....Channel  1
Pedal  5   input 0 output 127 velocity 6.13
CONTROL CHANGE.....Code  12......Value 127.....Channel  1
CONTROL CHANGE.....Code  12......Value 127.....Channel  1
Pedal  5 calibration max 260
Pedal  5   input 260 output 0 velocity -50.76
CONTROL CHANGE.....Code  12......Value   0.....Channel  1
CONTROL CHANGE.....Code  12......Value   0.....Channel  1
Pedal  6 calibration max 80
Pedal  5   input 108 output 82 velocity 18.63
CONTROL CHANGE.....Code  12......Value  82.....Channel  1
CONTROL CHANGE.....Code  12......Value  82.....Channel  1
Pedal  6   input 0 output 127 velocity 2.70
CONTROL CHANGE.....Code  13......Value 127.....Channel  1
CONTROL CHANGE.....Code  13......Value 127.....Channel  1
Pedal  5   input 48 output 127 velocity 2.30
CONTROL CHANGE.....Code  12......Value 127.....Channel  1
CONTROL CHANGE.....Code  12......Value 127.....Channel  1
Pedal  5   input 178 output 25 velocity -675.50
CONTROL CHANGE.....Code  12......Value  25.....Channel  1
CONTROL CHANGE.....Code  12......Value  25.....Channel  1
Pedal  6   input 54 output 0 velocity -4.50
CONTROL CHANGE.....Code  13......Value   0.....Channel  1
CONTROL CHANGE.....Code  13......Value   0.....Channel  1
Pedal  5   input 24 output 127 velocity 6.27
CONTROL CHANGE.....Code  12......Value 127.....Channel  1
CONTROL CHANGE.....Code  12......Value 127.....Channel  1
Pedal  6   input 0 output 127 velocity 9.07
CONTROL CHANGE.....Code  13......Value 127.....Channel  1
CONTROL CHANGE.....Code  13......Value 127.....Channel  1
Pedal  5   input 149 output 49 velocity -4.78
CONTROL CHANGE.....Code  12......Value  49.....Channel  1
CONTROL CHANGE.....Code  12......Value  49.....Channel  1
Pedal  5   input 59 output 121 velocity 480.00
CONTROL CHANGE.....Code  12......Value 121.....Channel  1
CONTROL CHANGE.....Code  12......Value 121.....Channel  1
Pedal  5   input 0 output 127 velocity 1.48
CONTROL CHANGE.....Code  12......Value 127.....Channel  1
CONTROL CHANGE.....Code  12......Value 127.....Channel  1
Pedal  6   input 78 output 0 velocity -3.01
CONTROL CHANGE.....Code  13......Value   0.....Channel  1
CONTROL CHANGE.....Code  13......Value   0.....Channel  1
Pedal  5   input 174 output 29 velocity -5.06
CONTROL CHANGE.....Code  12......Value  29.....Channel  1
CONTROL CHANGE.....Code  12......Value  29.....Channel  1
Pedal  6   input 0 output 127 velocity 9.01
CONTROL CHANGE.....Code  13......Value 127.....Channel  1
CONTROL CHANGE.....Code  13......Value 127.....Channel  1
Pedal  5   input 44 output 127 velocity 6.00
CONTROL CHANGE.....Code  12......Value 127.....Channel  1
CONTROL CHANGE.....Code  12......Value 127.....Channel  1
Pedal  5   input 232 output 0 velocity -819.35
CONTROL CHANGE.....Code  12......Value   0.....Channel  1
CONTROL CHANGE.....Code  12......Value   0.....Channel  1
Pedal  5   input 108 output 82 velocity 14.39
CONTROL CHANGE.....Code  12......Value  82.....Channel  1
CONTROL CHANGE.....Code  12......Value  82.....Channel  1
Pedal  5   input 33 output 127 velocity 284.81
CONTROL CHANGE.....Code  12......Value 127.....Channel  1
CONTROL CHANGE.....Code  12......Value 127.....Channel  1
Pedal  6 calibration max 90
Pedal  6   input 90 output 0 velocity -2.16
CONTROL CHANGE.....Code  13......Value   0.....Channel  1
CONTROL CHANGE.....Code  13......Value   0.....Channel  1
Pedal  5   input 144 output 53 velocity -4.05
CONTROL CHANGE.....Code  12......Value  53.....Channel  1
CONTROL CHANGE.....Code  12......Value  53.....Channel  1
Pedal  6   input 0 output 127 velocity 9.01
CONTROL CHANGE.....Code  13......Value 127.....Channel  1
CONTROL CHANGE.....Code  13......Value 127.....Channel  1
Pedal  5   input 23 output 127 velocity 4.53
CONTROL CHANGE.....Code  12......Value 127.....Channel  1
CONTROL CHANGE.....Code  12......Value 127.....Channel  1
Pedal  6   input 64 output 0 velocity -9.07
CONTROL CHANGE.....Code  13......Value   0.....Channel  1
CONTROL CHANGE.....Code  13......Value   0.....Channel  1
Pedal  6   input 0 output 127 velocity 52.74
CONTROL CHANGE.....Code  13......Value 127.....Channel  1
CONTROL CHANGE.....Code  13......Value 127.....Channel  1
Pedal  5   input 55 output 126 velocity -0.01
CONTROL CHANGE.....Code  12......Value 126.....Channel  1
CONTROL CHANGE.....Code  12......Value 126.....Channel  1
Pedal  5   input 164 output 37 velocity -664.18
CONTROL CHANGE.....Code  12......Value  37.....Channel  1
CONTROL CHANGE.....Code  12......Value  37.....Channel  1
Pedal  5   input 152 output 45 velocity 1.73
CONTROL CHANGE.....Code  12......Value  45.....Channel  1
CONTROL CHANGE.....Code  12......Value  45.....Channel  1
Pedal  5   input 0 output 127 velocity 535.95
CONTROL CHANGE.....Code  12......Value 127.....Channel  1
CONTROL CHANGE.....Code  12......Value 127.....Channel  1
Pedal  6   input 62 output 0 velocity -1.32
CONTROL CHANGE.....Code  13......Value   0.....Channel  1
CONTROL CHANGE.....Code  13......Value   0.....Channel  1
Pedal  5   input 198 output 9 velocity -6.65
CONTROL CHANGE.....Code  12......Value   9.....Channel  1
CONTROL CHANGE.....Code  12......Value   9.....Channel  1
Pedal  6   input 0 output 127 velocity 9.07
CONTROL CHANGE.....Code  13......Value 127.....Channel  1
CONTROL CHANGE.....Code  13......Value 127.....Channel  1
Pedal  5   input 32 output 127 velocity 7.22
CONTROL CHANGE.....Code  12......Value 127.....Channel  1
CONTROL CHANGE.....Code  12......Value 127.....Channel  1
Pedal  6   input 68 output 0 velocity -9.07
CONTROL CHANGE.....Code  13......Value   0.....Channel  1
CONTROL CHANGE.....Code  13......Value   0.....Channel  1
Pedal  6   input 0 output 127 velocity 52.74
CONTROL CHANGE.....Code  13......Value 127.....Channel  1
CONTROL CHANGE.....Code  13......Value 127.....Channel  1
Pedal  5   input 56 output 126 velocity -0.01
CONTROL CHANGE.....Code  12......Value 126.....Channel  1
CONTROL CHANGE.....Code  12......Value 126.....Channel  1
Pedal  5   input 161 output 39 velocity -635.04
CONTROL CHANGE.....Code  12......Value  39.....Channel  1
CONTROL CHANGE.....Code  12......Value  39.....Channel  1
Pedal  5   input 160 output 39 velocity 0.00
CONTROL CHANGE.....Code  12......Value  39.....Channel  1
CONTROL CHANGE.....Code  12......Value  39.....Channel  1
Pedal  5   input 0 output 127 velocity 637.68
CONTROL CHANGE.....Code  12......Value 127.....Channel  1
CONTROL CHANGE.....Code  12......Value 127.....Channel  1
Pedal  6   input 58 output 0 velocity -1.32
CONTROL CHANGE.....Code  13......Value   0.....Channel  1
CONTROL CHANGE.....Code  13......Value   0.....Channel  1
Pedal  5   input 190 output 16 velocity -6.25
CONTROL CHANGE.....Code  12......Value  16.....Channel  1
CONTROL CHANGE.....Code  12......Value  16.....Channel  1
Pedal  6   input 0 output 127 velocity 9.01
CONTROL CHANGE.....Code  13......Value 127.....Channel  1
CONTROL CHANGE.....Code  13......Value 127.....Channel  1
Pedal  5   input 28 output 127 velocity 6.79
CONTROL CHANGE.....Code  12......Value 127.....Channel  1
CONTROL CHANGE.....Code  12......Value 127.....Channel  1
Pedal  6   input 73 output 0 velocity -9.07
CONTROL CHANGE.....Code  13......Value   0.....Channel  1
CONTROL CHANGE.....Code  13......Value   0.....Channel  1
Pedal  6   input 0 output 127 velocity 52.65
CONTROL CHANGE.....Code  13......Value 127.....Channel  1
CONTROL CHANGE.....Code  13......Value 127.....Channel  1
Pedal  5   input 58 output 124 velocity -0.04
CONTROL CHANGE.....Code  12......Value 124.....Channel  1
CONTROL CHANGE.....Code  12......Value 124.....Channel  1
Pedal  5   input 164 output 37 velocity -604.17
CONTROL CHANGE.....Code  12......Value  37.....Channel  1
CONTROL CHANGE.....Code  12......Value  37.....Channel  1
Pedal  5   input 155 output 42 velocity 1.08
CONTROL CHANGE.....Code  12......Value  42.....Channel  1
CONTROL CHANGE.....Code  12......Value  42.....Channel  1
Pedal  5   input 0 output 127 velocity 541.40
CONTROL CHANGE.....Code  12......Value 127.....Channel  1
CONTROL CHANGE.....Code  12......Value 127.....Channel  1
Pedal  6   input 64 output 0 velocity -1.32
CONTROL CHANGE.....Code  13......Value   0.....Channel  1
CONTROL CHANGE.....Code  13......Value   0.....Channel  1
Pedal  5   input 196 output 11 velocity -6.54
CONTROL CHANGE.....Code  12......Value  11.....Channel  1
CONTROL CHANGE.....Code  12......Value  11.....Channel  1
Pedal  6   input 0 output 127 velocity 9.01
CONTROL CHANGE.....Code  13......Value 127.....Channel  1
CONTROL CHANGE.....Code  13......Value 127.....Channel  1
Pedal  5   input 20 output 127 velocity 7.10
CONTROL CHANGE.....Code  12......Value 127.....Channel  1
CONTROL CHANGE.....Code  12......Value 127.....Channel  1
Pedal  6   input 75 output 0 velocity -9.07
CONTROL CHANGE.....Code  13......Value   0.....Channel  1
CONTROL CHANGE.....Code  13......Value   0.....Channel  1
Pedal  6   input 0 output 127 velocity 52.54
CONTROL CHANGE.....Code  13......Value 127.....Channel  1
CONTROL CHANGE.....Code  13......Value 127.....Channel  1
Pedal  5   input 58 output 124 velocity -0.04
CONTROL CHANGE.....Code  12......Value 124.....Channel  1
CONTROL CHANGE.....Code  12......Value 124.....Channel  1
Pedal  5   input 164 output 37 velocity -604.17
CONTROL CHANGE.....Code  12......Value  37.....Channel  1
CONTROL CHANGE.....Code  12......Value  37.....Channel  1
Pedal  5   input 153 output 44 velocity 1.52
CONTROL CHANGE.....Code  12......Value  44.....Channel  1
CONTROL CHANGE.....Code  12......Value  44.....Channel  1
Pedal  5   input 0 output 127 velocity 512.35
CONTROL CHANGE.....Code  12......Value 127.....Channel  1
CONTROL CHANGE.....Code  12......Value 127.....Channel  1
Pedal  6   input 60 output 0 velocity -1.32
CONTROL CHANGE.....Code  13......Value   0.....Channel  1
CONTROL CHANGE.....Code  13......Value   0.....Channel  1
Pedal  5   input 180 output 24 velocity -5.80
CONTROL CHANGE.....Code  12......Value  24.....Channel  1
CONTROL CHANGE.....Code  12......Value  24.....Channel  1
Pedal  6   input 0 output 127 velocity 9.01
CONTROL CHANGE.....Code  13......Value 127.....Channel  1
CONTROL CHANGE.....Code  13......Value 127.....Channel  1
Pedal  5   input 24 output 127 velocity 6.31
CONTROL CHANGE.....Code  12......Value 127.....Channel  1
CONTROL CHANGE.....Code  12......Value 127.....Channel  1
Pedal  6   input 76 output 0 velocity -9.07
CONTROL CHANGE.....Code  13......Value   0.....Channel  1
CONTROL CHANGE.....Code  13......Value   0.....Channel  1
Pedal  6   input 0 output 127 velocity 52.59

**Comment by alf45tar** [comment]
Sorry, which is the question or issue?

**Comment by zhanwu123** [comment]
https://v.youku.com/v_show/id_XNDY5MTg2NDQ2OA==.html

**Comment by alf45tar** [comment]
I suggest to have a look of issue https://github.com/alf45tar/PedalinoMini/issues/59
