### ISSUE TITLE
Update when there is an error

### ISSUE THREAD

**Issue by zhanwu123** [alf45tar/PedalinoMini#107]
Updating AppleMIDI                       @ 417bafa        [Up-to-date]
Updating ArduinoJson-esphomelib          @ 5.13.3         [Up-to-date]
Updating ArduinoJson                     @ 6.15.2         [Up-to-date]
Updating AsyncTCP                        @ ca8ac5f        [Up-to-date]
Updating AsyncTCP                        @ 1.1.1          [Up-to-date]
Updating BLE-MIDI                        @ 6eaf748        Error: VCS: Could not receive an output from `['git', 'branch']` command ({'out': '', 'err': "fatal: Invalid path 'I:/PedalinoMini-My/.git': No such file or directory\n", 'returncode': 128})

**Comment by alf45tar** [comment]
I suppose you resolved the issue. If not reopen it with more details.
