### ISSUE TITLE
Feature request: Last MIDI event recall while switching bank ?

### ISSUE THREAD

**Issue by quangvankts** [alf45tar/PedalinoMini#11]
Hi
Is it possible to have the option of by switching to a bank, the last pedal/MIDI event that was sent while in that bank get repeated again ? 
Ex: While at bank 1, the last MIDI message sent is PC #18. Switch to bank 2, the last MIDI message sent is PC #21. Switching back to bank 1 makes Pedalino automatically send PC #18 again. Switching to bank 2 and PC#21 is sent immediately after etc
This option maybe useful in certain scenarios (less tap dancing on stage)
Thank you

**Comment by alf45tar** [comment]
Yes, it is. I am working on it and I will release shortly.

**Comment by alf45tar** [comment]
To enable repeat on bank switch goto Options menu

**Comment by quangvankts** [comment]
Amazing ! It works exactly as descripted. Thanks alf45tar !
