### ISSUE TITLE
Web UI various problems

### ISSUE THREAD

**Issue by aFunkyBass** [alf45tar/PedalinoMini#110]
Hello there, I have some problems with Web UI. 

**First** when I enter the web configuration, it doesn't load the bootstrap module, so the interface is totally screwd up, here's what I got:

![immagine](https://user-images.githubusercontent.com/66510206/87345620-9f5dc680-c550-11ea-959a-b4a8d5be3bbe.png)

Going on the options page and changing the theme solves the problem, but it needs Internet connection

**Second** going on the  Actions page the "New Action" button doesn't do anything. I tried with several browsers under Linux, but had no luck. The only way for me to add an action is to use the Enter key when in the "Bank Name" field, but it only adds actions on Pedal 1

What am I doing wrong?

Thank you!

**Comment by alf45tar** [comment]
Run “Upload File System image” task in PlatformIO IDE or use PlatformIO Core (CLI) and 'platformio run --target uploadfs' command

**Comment by aFunkyBass** [comment]
Ops... I can't believe I was so dumb!! :sob: :smile: 
Sorry!

**Comment by aFunkyBass** [comment]
Obviously it works flawlessly! :wink: 

Now  I have another problem, I'll put it here (even if it's OT), I can open a new issue if you prefer.

I'm building a pedalboard with 8 footswitch (momentary), so I'm using 4 channels in momentary/2 configuration, leaving 2 channels for external epression pedals.

The thing is that momentary/2 acts weird. The first button toggles values (press once sends 127, press again sends 0), which is what I need, but the second button of the momentary, always sends 127. plus it seems to affect the value of the first button. 

Here's my configuration
![immagine](https://user-images.githubusercontent.com/66510206/87409216-f1403400-c5c4-11ea-9f7d-f30b4bcb5798.png)

Is it an intended behaviour?

**Comment by alf45tar** [comment]
It is not an intended behaviour. It is a bug. I tried to fix it on the fly but I didn't tested yet. Check the latest commit if it works now.

**Comment by aFunkyBass** [comment]
It works as expected now, I tested it only on channel 1 though, but I'm confident about the rest of channels! ;)

Thanks a lot!

**Comment by alf45tar** [comment]
Thanks to you for debugging my software

**Comment by WernAir77** [comment]
I have the same issues with the web interface. 
Which theme and which browser is working?

**Comment by alf45tar** [comment]
Did you upload the file system image?

Under PlatformIO Project Tasks select your environment (i.e. env:esp32doit-devkit-v1)
Click “Upload File System Image” under Platform 

The standard system image includes only the "bootstrap" theme. For the other themes an internet connection is required.
Any modern browser is supported including mobile devices.

**Comment by WernAir77** [comment]
I reinstalled the image and now it works fine. 
Merci
