### ISSUE TITLE
WiFi connection timeout

### ISSUE THREAD

**Issue by mknerr** [alf45tar/PedalinoMini#114]
Not sure if this is an issue or not, but it's happening consistently enough, I thought I would mention it. It seems every other time I boot my pedalino, the Wifi times out. And, on the opposite times, it connects to my network almost immediately.

**Comment by alf45tar** [comment]
Check the log. Are there any errors?

**Comment by mknerr** [comment]
Yes, as follows:

[W][WiFiGeneric.cpp:353] _eventCallback(): Reason: 15 - 4WAY_HANDSHAKE_TIMEOUT
SYSTEM_EVENT_STA_DISCONNECTED
SmartConfig started
SmartConfig timeout
WPS started
WPS timeout
AP Pedalino-71AE114C started

**Comment by alf45tar** [comment]
I need all the log from the beginning of boot to the end.

**Comment by alf45tar** [comment]
Did you try to reset to factory default and/or erase flash?

**Comment by alf45tar** [comment]
Is still an issue?

**Comment by mknerr** [comment]
I have not been noticing it since I've updated. Thank you.
