### ISSUE TITLE
Using momentary switch as toggle switch

### ISSUE THREAD

**Issue by frankdeath** [alf45tar/PedalinoMini#115]
Issue #54 discussed how to use a momentary switch as a toggle with the old web interface. Is this still possible with the new web interface?

My ultimate goal is to use the momentary switch of a rotary knob to switch between forward and reverse modes of the Line 6 Helix Looper (see screenshot).

![Screenshot_20200628-203057](https://user-images.githubusercontent.com/1928514/88250512-71bdff00-cc6d-11ea-827c-a2c93368ebda.png)

**Comment by frankdeath** [comment]
It looks like subsequent presses of the momentary switch alternate between the "From" and the "To" values. If this is correct, it would be very helpful to have a unique tag for each value.

**Comment by alf45tar** [comment]
@frankdeath added the second tag
