### ISSUE TITLE
Arduino Pro Micro power is too big?

### ISSUE THREAD

**Issue by zhanwu123** [alf45tar/PedalinoMini#121]
Today just completed PedalinoMini, when the test to the Arduino Pro Micro power is too big
![IMG_0170](https://user-images.githubusercontent.com/65864505/89866560-59912e00-dbe2-11ea-9a67-59840f6504e3.PNG)

**Comment by alf45tar** [comment]
You can draw 100 mA from a lightning connector or use the lighting to usb camera adapter with an additional lightning port to connect power.

**Comment by zhanwu123** [comment]
Can you send some software to connect video? Thank you very much!

**Comment by alf45tar** [comment]
https://youtu.be/pCNSvJ9QiDs?t=40

**Comment by zhanwu123** [comment]
If I need a cable to connect the USB interface, what's the solution? Thank you for a long time
