### ISSUE TITLE
Possibility to convert all pins to digital

### ISSUE THREAD

**Issue by raidolo** [alf45tar/PedalinoMini#126]
Hi!

I finally built my Pedalino Mini.
I designed a box which is a mix of laser cutting and 3d printing: 

![image](https://user-images.githubusercontent.com/25846804/91668083-dfc9d180-eb09-11ea-818e-1f8f97915324.jpeg)

I'm experiencing an issue with the analog pins, I'm using 3.3Komh pull-up resistors, and my Pedalino is configured with 5x Latch2 switches, so I have 5x buttons connected to the digital pins and 5x buttons connected to the analog pins.
When I press the 4th button connected on the analog pin, something weird happens and I have also the 3rd button doing stuff, fluctuating in a weird way, and I'm not able to turn them off.

Is it possible to configure all pins as digital to get rid of this issue?

Thanks a lot in advance.

Cheers,
Alessio.

**Comment by alf45tar** [comment]
Wow...It looks very professional.

Using Latch2 the analog pins are configured as digital.
Can you attach the log?

**Comment by raidolo** [comment]
Just a correction, the resistors are 10k omhs not 3.3k. ( I confused the resistors used for the oled.... sorry)

Which log? The one from the serial?

**Comment by alf45tar** [comment]
yes the serial log.

**Comment by raidolo** [comment]
On the analog side I've found a cold solder and it seems I've fixed it. But I've started to see the same strange behavior also on the digital pins. See the video:

https://youtu.be/gNVr6zfyuAo

First button on the top row is pin 25, second button is pin 26. The first two digital pins. There's no external pull-up resistors connected to them.

It seems that the issue starts when using BLE only, it's like the internal pull-up of my esp32 board doesn't work very well.

Do you think that using an external pull-up resistor also on the digital pins could solve the issue?

Regarding the serial log you'll see no input (as in the video when pushing the green button does nothing) or weird stuff like inputs activated by themselves, not much interesting.

Thanks.

**Comment by raidolo** [comment]
I've pulled up all the pins except the pin 12, otherwise the ESP32 don't boot. 

Seems working fine now, I'll let you know, I'll test it more.

**Comment by raidolo** [comment]
I had to move the button on pin D12 to the D13, with a 10k omh pull-up resistor. 
Leaving the D12 pin floating leads to unpredictable results. I had a weird behavior like before.
As I said, pin D12 cannot be pulled up, otherwise the ESP32 does not boot. 
SO now I'm using all the "analog" pins except D33 and all the digital pins except D12, all with pull up resistor.

I didn't see strange activations since I've done it. If anything new comes up I'll let you know.

I don't know if it's my dev board that has some issues, but I think this is something worth mentioning in the wiring guide as a possible option.  

Cheers,
Alessio.

**Comment by alf45tar** [comment]
Digital pins do not need external pull up resistor because if used the internal pull up resistor is used.

**Comment by raidolo** [comment]
What do you mean? Is that because in the code they are defined as INPUT_PULLUP and so you mean I’m using a double resistance in this case?

**Comment by alf45tar** [comment]
Yes, confirm. Double resistor is not a problem except for pin 12.
