### ISSUE TITLE
Possibility to use SSD1309 2.42" OLED

### ISSUE THREAD

**Issue by micahvdm** [alf45tar/PedalinoMini#129]
As the title says, I'm wondering if the above would be possible? Would be really nice to have a bigger OLED for a pedal board situation.

**Comment by alf45tar** [comment]
PedalinoMini supports SSD1306 and SH1106 128x64 OLED display only.
If SSD1309 is not backward compatible with SSD1306 it doesn't work.

It could be possible adapting https://github.com/ThingPulse/esp8266-oled-ssd1306 library.

**Comment by wybbbb** [comment]
![image](https://user-images.githubusercontent.com/77892552/133078470-35c1980b-73ec-439d-8729-7b75f9a6be17.png)
![image](https://user-images.githubusercontent.com/77892552/133078521-e65a2f33-bb36-4326-8b8b-c9a0859e5126.png)
After testing, the SSD1309 module compatible with SSD1306 can be used normally. I used translation software to translate it, and the meaning may be a little off!

**Comment by DWSQUIRES** [comment]
Cool. Did this require any code changes?

**Comment by wybbbb** [comment]
> Cool. Did this require any code changes?

Without modifying any code, you can use it directly after connecting
