### ISSUE TITLE
Interface only shows 6 pedals

### ISSUE THREAD

**Issue by jberry** [alf45tar/PedalinoMini#13]
Whem using an alternate pedal wiring schema, like ladder, the interface still only shows the original 6 pedals even when setting it to Ladder.

How do we configure what those additional switches activate/do?

**Comment by alf45tar** [comment]
Ladder is not yet fully supported. The idea is to configure only the first one. The 2nd, the 3rd, the 4th and the 5th will send the same MIDI message of the 1st but it will increse by 1, by 2, by 3 and by 4 the note, the CC or the PC.
