### ISSUE TITLE
Pedal three trigger modes

### ISSUE THREAD

**Issue by zhanwu123** [alf45tar/PedalinoMini#130]
Hello, alf45tar. I'm prepared to pedal1 set to single press, double press and long press three modes, and has enabled the single press, double press and long press, what should I do?
Thank you very much!

**Comment by zhanwu123** [comment]
![微信图片_20200924173821](https://user-images.githubusercontent.com/65864505/94128801-2999a380-fe8d-11ea-9258-2d1359598147.jpg)
![微信图片_20200924173816](https://user-images.githubusercontent.com/65864505/94128811-2acad080-fe8d-11ea-89af-cf326b59aa8b.jpg)

**Comment by alf45tar** [comment]
Very good. The setup is ok.
Just press pedal 1 to send the configured MIDI messages.

**Comment by zhanwu123** [comment]
Now pedal pressed the from is 127 it after work, is 0, there is no action

**Comment by alf45tar** [comment]
@zhanwu123 not clear to me what you mean

**Comment by zhanwu123** [comment]
Pedal pressed, the value value is 0, then pedal no MIDI information output, the value value of 127 is the MIDI output

**Comment by alf45tar** [comment]
With your configuration when you click (press and release) pedal 1 PedalinoMini send CC 60 value 127.
The second time send CC 60 value 0. The third time CC 60 value 127, the fouth CC 60 value 0 and so on.

**Comment by zhanwu123** [comment]
Does or does not work, want to turn off the automatic sorting of pedals, behind every action and release.

**Comment by zhanwu123** [comment]
Set before
![微信图片_20200929141824](https://user-images.githubusercontent.com/65864505/94520521-fffec480-025e-11eb-8548-a6267ce2205e.jpg)
Save the future
![微信图片_20200929141819](https://user-images.githubusercontent.com/65864505/94520597-1f95ed00-025f-11eb-9cd7-65ca0746d691.jpg)

**Comment by zhanwu123** [comment]
Alf45tar hello, I have already completed the PedalinoMini project, is now double-click and long press cannot be applied, don't know what's the problem? Thank alf45tar.

**Comment by alf45tar** [comment]
For Pedal 1 create 3 actions. The first on Press, the second on Double Press and third on Long Press.
Assign different midi messages of course.

**Comment by zhanwu123** [comment]
I have already done so, but still can't work perfect, because is worth, 0 or 127 can't return.

**Comment by alf45tar** [comment]
@zhanwu123 
Did you solved?
