### ISSUE TITLE
10 Pedal Board - It is working great!

### ISSUE THREAD

**Issue by bsos** [alf45tar/PedalinoMini#131]
Thank you for such a great project! Put together a 10 pedal board using an ESP32. 

I have plans to convert 1 of the pedals to a momentary 3 switch, so I can have two 1/4 jacks for expression pedals.  Right now input 1 + 2 are wired as a momentary 3 switch. I would have went for a 6 switch ladder, but just couldn’t get the sensitivity right. 

![48601A50-47EF-46B9-BCE1-AC512F7B604A](https://user-images.githubusercontent.com/6843511/94213274-63c26f80-fea4-11ea-9e11-c6955389c7e1.jpeg)
![885169B4-4B8A-479A-9EE1-5AD590CAC5C5](https://user-images.githubusercontent.com/6843511/94213280-64f39c80-fea4-11ea-9d75-261437c90085.jpeg)

It’s working great. Thanks again.

**Comment by alf45tar** [comment]
Thanks for sharing your project. Well done!
