### ISSUE TITLE
cannot open source file "hardware/ESP32_NimBLE.h"

### ISSUE THREAD

**Issue by noisedestroyers** [alf45tar/PedalinoMini#133]
After git cloning into vscode, I see the following error in BLEMidiIn.h and BLEMidiOut.h

cannot open source file "hardware/ESP32_NimBLE.h"

Was this a custom header written recently with the NimBLE update and not included in the repo? Or perhaps I need to manually add another library to PIO?

Thanks for the great project and looking at this issue.

**Comment by alf45tar** [comment]
Latest commits of https://github.com/lathoub/Arduino-BLE-MIDI and https://github.com/bblanchon/ArduinoJson are not backward compatible.

Fixed.

**Comment by noisedestroyers** [comment]
Confirmed, project compiles with updated platformio.ini 

Thank you alf45tar!
