### ISSUE TITLE
...and this module?

### ISSUE THREAD

**Issue by davidin73** [alf45tar/PedalinoMini#135]
Hello!
Do you think this module is compatible for pedalino?
https://www.amazon.it/MakerHawk-Sviluppo-Display-Arduino-Compatibile/dp/B076P8GRWV/ref=mp_s_a_1_11?dchild=1&keywords=esp32&qid=1601842580&sr=8-11
Thanks in advice!

**Comment by alf45tar** [comment]
I don't think so. It looks like an Heltec.
 See #8 and #125.

**Comment by davidin73** [comment]
Okay, thank you. I have another question, I post it here over
