### ISSUE TITLE
Arduino mega r3

### ISSUE THREAD

**Issue by davidin73** [alf45tar/PedalinoMini#136]
Can I use a arduino mega 2560 r3 instead of the micro pro? What are the differences in terms of coding and connections?
Thank you in advice

**Comment by alf45tar** [comment]
No, you can't.

> The Micro board is similar to the Arduino Leonardo in that the ATmega32U4 has built-in USB communication, eliminating the need for a secondary processor. This allows the Micro to appear to a connected computer as a mouse and keyboard, in addition to a virtual (CDC) serial / COM port.

 Arduinio Micro Pro is a full USB client. Arduino Mega can only emulate a virtual serial port.

**Comment by davidin73** [comment]
Okay,thank you very much!
