### ISSUE TITLE
4 pedals, 6 output jacks

### ISSUE THREAD

**Issue by rigr** [alf45tar/PedalinoMini#138]
Just wanted to share my project, I use 4 push buttons (will install two more) and can also connect anything else using stereo-jacks. I also use small stereo-jacks for MIDI and also installed an arduino pro for USB-MIDI.

![IMG_20201007_184300___](https://user-images.githubusercontent.com/6568315/95367333-eef42a00-08d4-11eb-92a8-3345ff4f358a.jpg)

![IMG_20201007_184341__](https://user-images.githubusercontent.com/6568315/95367429-0c28f880-08d5-11eb-9263-c017f5dae684.jpg)

![IMG_20201007_184246_](https://user-images.githubusercontent.com/6568315/95367206-c2d8a900-08d4-11eb-9cc1-21adec9d219b.jpg)

Thanks alf45tar for coding!
Best regards
Richard

**Comment by alf45tar** [comment]
@rigr thanks for sharing your built
