### ISSUE TITLE
Display issues

### ISSUE THREAD

**Issue by davidin73** [alf45tar/PedalinoMini#141]
Web io and services working,but display shows this :

![16023256314548362487490966515042](https://user-images.githubusercontent.com/72359395/95652784-f2b1c780-0af3-11eb-87c8-27a911b81af6.jpg)

**Comment by akosbeke** [comment]
@davidin73 try changing these lines:
```
	-D SSD1306WIRE
;	-D SSH1106WIRE
```

to:

```
;	-D SSD1306WIRE
	-D SSH1106WIRE
```

in platformio.ini

**Comment by davidin73** [comment]
@akosbeke thanks,when I back home I try.
Cheers

**Comment by davidin73** [comment]
Thank you very much!!!! This was the problem.
By the road,I have two stupid questions (be patient, I'm a noob...😅)
1 i don't understand from the schematic where to connect the six buttons
2 ...and if I want 8 buttons, how can I do?

**Comment by rigr** [comment]
David, for better structure I think you should open another issue when changing the topic. 
When clicking on schematic 2 it will open a new window where you can click on RAW and see a bigger version of the sheet.
You can connect up to 6 buttons to any port using a voltage ladder as shown in schematic 2:
![6_buttons](https://user-images.githubusercontent.com/6568315/95658843-c1e68800-0b1d-11eb-862c-b7bd13eaf5ad.jpg)
If you want 8 buttons you need to use at least two ports to connect them.

**Comment by davidin73** [comment]
Ah,okay
Thank you very much. 
Now I open another topic
Cheers

**Comment by jisv48** [comment]
Thanks for tip regarding the OLED definition.  It is appreciated and now is working correctly.  Cheers
