### ISSUE TITLE
How many cc commands

### ISSUE THREAD

**Issue by davidin73** [alf45tar/PedalinoMini#142]
Hello.
Just a (maybe stupid) question...
How many cc commands can send the pedalino on button pressing?
I.e.
Button 1 send cc n.24, value x, cc.n56 value y, etc. Etc..
Button 2 send cc n. 78 value x and nothing more
and then on for each button ..

**Comment by mknerr** [comment]
You could use the sequence feature to send 10 commands on a single press.

**Comment by davidin73** [comment]
Thank you @mknerr

**Comment by alf45tar** [comment]
If 10 commands are not enough you can use una sequence position to run a different sequence.

**Comment by davidin73** [comment]
Thanks a lot!!!
