### ISSUE TITLE
OLED Display | Profile Indicator, Battery Status

### ISSUE THREAD

**Issue by TarFilarek** [alf45tar/PedalinoMini#143]
Hi!

First of all - I want to thank You for Your hard work. This project is simply amazing!

_**1st question:**_ How can I move the Profile Indicator [A]/[B]/[C] slightly more to the centre of the display? Which code line I should modify? 

_**2nd question:**_ Is it possible to change the way of displaying the battery status? The current way is slightly inaccurate and adding percentage value (just like in mobile phones) next to the battery status (or instead of) would be a great addon.

**Comment by alf45tar** [comment]
1. https://github.com/alf45tar/PedalinoMini/blob/46f40604f3befd1aff69c31ba92c01bfe330d0c2/src/DisplayOLED.h#L445

2. Battery status is disabled by default because it is still under development. Thanks for your suggestion.
