### ISSUE TITLE
The Configuration files can be downloaded and Shared with others PedalinoMini ™ users

### ISSUE THREAD

**Issue by zhanwu123** [alf45tar/PedalinoMini#146]
The Configuration files can be downloaded and Shared with others PedalinoMini ™ users. How can I operate?

**Comment by rigr** [comment]
well, if you "program" your pedalino (using the webinterface) you can save the configuration to a file and offer that file to others. If you get such a file you can upload it to your pedalino.

**Comment by zhanwu123** [comment]
I still can't work. Could you tell me the specific steps? Thank you very much!

**Comment by rigr** [comment]
zhanwu123 please explain where you have a problem.

**Comment by zhanwu123** [comment]
Configuration file export and import of CFG, what should I do?

**Comment by rigr** [comment]
ok, lets start systematically:
1) So you have built a pedalino?
2) Have you been able to call the webinterface?
3) Did you make any settings (actions, pedals, etc?)
next steps later :)

**Comment by zhanwu123** [comment]
Configuration file export and import of CFG, what should I do?

**Comment by rigr** [comment]
ok, and did you go to pedals page and actions-page  and change anything?
When done go to configurations- page, type in a name at new configuration (for example zhanwu001), then click "save configuration". 
then choose your zhanwoo001 configuration at "available configurations" and click "download"
you will receive a zhanwu001.cfg file. 
Yes?

**Comment by zhanwu123** [comment]
Yes, I can do this.

**Comment by rigr** [comment]
ok, so you can then upload that file to your pedalino later. Choose that file at "Upload configuration", upload, then go up to "available configurations" and click "apply and save". That's it.

**Comment by rigr** [comment]
and you can send that file to me, and I can also upload to my pedalino. :))

**Comment by zhanwu123** [comment]
How to export zhanwu001 this file?

**Comment by rigr** [comment]
have you been able to download the zhanwu001.cfg file?

_

> When done go to configurations- page, type in a name at new configuration (for example zhanwu001), then click "save configuration".
> then choose your zhanwoo001 configuration at "available configurations" and click "download"
> you will receive a zhanwu001.cfg file.

_

**Comment by zhanwu123** [comment]
Zhanwu001. CFG this file on the phone?

**Comment by rigr** [comment]
Did you download the zhanwu001.cfg filr to your phone?
If yes, you can attach it to your reply. I would suggest you use a tablet or even better your computer but it will work with your phone, too.

**Comment by zhanwu123** [comment]
![Uploading 微信图片_20201015165143.jpg…]()
Then what should I do?

**Comment by rigr** [comment]
Do you have zhanwu001.cfg on your phone?

**Comment by rigr** [comment]
if you want to upload it to here, you will need to rename the file to zhanwu001.cfg.txt or pack it into a zip-file - otherwise github will refuse to accept the file.

**Comment by zhanwu123** [comment]
I'm sorry. I still can't import and export CFG file.

**Comment by zhanwu123** [comment]
![QQ截图20201016102255](https://user-images.githubusercontent.com/65864505/96205794-0b115e80-0f9a-11eb-8359-d3ce16b5bb78.png)
I've been to the mailbox, but on the computer.

**Comment by rigr** [comment]
pk, you downloaded with your browser.

Please have a look here:
1) save configuration inside pedalino
![zhan2](https://user-images.githubusercontent.com/6568315/96284280-a5df5c80-0fdd-11eb-9aad-aa94a8ebe20e.jpg)
2) choose configuration
![zhan3](https://user-images.githubusercontent.com/6568315/96284370-c7404880-0fdd-11eb-991c-b9ec00d8842c.jpg)
3) download configuration
![zhan4](https://user-images.githubusercontent.com/6568315/96284433-d9ba8200-0fdd-11eb-9a79-802b370fce36.jpg)
4) decide where to save configuration on your computer
![zhan5](https://user-images.githubusercontent.com/6568315/96284496-efc84280-0fdd-11eb-8e97-0b4794da802c.jpg)
5) to upload a configuration you need to choose it from your computer
![zhan6](https://user-images.githubusercontent.com/6568315/96284575-0bcbe400-0fde-11eb-8b4d-3c6a7d030b7d.jpg)

Please try that. Good luck.

**Comment by zhanwu123** [comment]
Why I don't have the item 5？

**Comment by zhanwu123** [comment]
After I click on the download directly into the WEB.
![微信图片_20201017085900](https://user-images.githubusercontent.com/65864505/96325034-6190a280-1057-11eb-8dc5-1da8d139265b.jpg)

**Comment by rigr** [comment]
It might depend on your browser - it looks like your browser is showing what is written in the cnf - file, and you might try right-clicking on "download" (in 3.) and tell your browser where to save the file.
BTW: I suggest you use a better password for your WiFi :)) a123456789 might be too weak.
