### ISSUE TITLE
MIDI Phantom Power

### ISSUE THREAD

**Issue by marosell** [alf45tar/PedalinoMini#15]
Would it be possible to power over a 7-pin midi cable, and if so, can the diagram be updated to show how this is done?

**Comment by alf45tar** [comment]
Yes, it would.
Did you considered to use the battery connected to the TTGO board? For my projects I am using a Lithium battery of an old phone. A 1000 mAh battery can power it for 3 hours at least.

**Comment by marosell** [comment]
I did consider battery, but I'm also considering using this in other ways as well. I'd like to use this to connect directly to the midi port on my XR18 and program buttons to change mixer parameters. If I can draw power right from the mixer, it negates needing to plug in anything else or even use a battery :). Something to consider for future schematics.

I'm not great with electronic design, but may do some research down the road on what it takes to send power through a 7-pin midi into the ESP32.

**Comment by alf45tar** [comment]
XR18 has 5-pin midi port. I don't think you can draw power from it.

**Comment by marosell** [comment]
> XR18 has 5-pin midi port. I don't think you can draw power from it.

You're right 😞 .
