### ISSUE TITLE
Wemos LoLin32 V1.0.0 ESP32 

### ISSUE THREAD

**Issue by MaxZak2020** [alf45tar/PedalinoMini#150]
First of all - thanks for this mighty project you've started and for your and all community support! 
I'm absolute beginner in controller building and kindly ask for advice about platform Wemos LoLin32 V1.0.0 ESP32 Wi-Fi + Bluetooth 4MB Flash CP2102 Li-po (NodeMCU).
Can I use your code from right from the box to load in this controller or it needs to be corrected and pinout is not applied for the project? 
I've interested to make controller working on rechargeable accum and this one is quite easy to get.
Thanks for any comments to all.

**Comment by alf45tar** [comment]
It should works without too much changes. The only issue could be the missing BOOT button. It should be remapped to some external pin but not too hard to accomplish.

**Comment by MaxZak2020** [comment]
Thanks!
