### ISSUE TITLE
Remap inputs GPIO

### ISSUE THREAD

**Issue by aFunkyBass** [alf45tar/PedalinoMini#151]
For some reason, I think I blew D25 and D27 digital inputs!!! Me idiot!!

Is it possible to remap those inputs, if there are spare ones?

Thank you!

**Comment by alf45tar** [comment]
Yes you can remap them here https://github.com/alf45tar/PedalinoMini/blob/4faa2e02ecf6ae6c291eb422bc735b7ae3c1fd6f/src/Pedalino.h#L33

Found some available pins is a little bit more hard.

**Comment by aFunkyBass** [comment]
Thank you @alf45tar I'll see what to do...
