### ISSUE TITLE
Boot button functionality on a 38pin DevKit v1

### ISSUE THREAD

**Issue by copych** [alf45tar/PedalinoMini#153]
Hello, it was so cool to find what I've been thinking of! Great project, nice interface.
By coincidence I've bought a couple of boards to play with, and they should do as I understand. I have ESP32 DEVKIT V1 38pin version, not sure if it's a clone.
Builtin led is gpio1, EN pin is bound to RST button, and gpio0 to BOOT button.
The issue is that the boot button ain't working as expected in this project (
Debug shows that digitalRead(0) always returns 0, no matter if it's pressed or not. I tried different combinations, but not succeeded. I tried different pinMode() settings, reversed logical states and so on.
Meanwhile, simple test app i wrote confirmed that the BOOT button itself is working ok on this board if i test it isolated (in terms of programming, wiring is the same).
Please, give me a direction to dig.
I've killed a couple of evenings trying to fix it so far, but I only manage to pass the dead loop on startup when triggered gpio0 manually with 3v3 wire :/
Unfortunately, I don't have another ESP32 board to switch and test. I've ordered a couple from China 2 months ago, but they are still somewhere in transit...

**Comment by copych** [comment]
I don't know why, but the gpio0 become heavily pulled down right some 100 msecs after reset, so only shorting it to the 3v3 changes the state (. 
But i believe that it is somehow software caused. As i told, simple app can fteely operate with gpio0, lighting the led on gpio1...

**Comment by RomanKlein777** [comment]
I have the same problem. my devkit board was running fine with previous version, (by the way it was only 160MHz CPU). now updated (also system image) and only loop. it makes always factory reset as if I was holding BOOT button. I have tried also other boards. Correct 240MHz cpu. No PSRAM versions. Maybe i try those boards. I hope it makes also some difference with PSRAM... 
is it not a bug?

**Comment by copych** [comment]
I've remapped both CENTER and BOOT buttons to GPIO23. This way the board behaves more or less predictable. Also I had to update NimBLE library because the included version caused CRI reboots. In fact i have deleted the supplied version and added according section with the github link to the lib_deps section of the project in PlatformIO.
Maybe the author have some thoughts on this matter. For example, could this be some changes that are not properly synced with github?

**Comment by alf45tar** [comment]
The issue is with the 3rd parties libraries. I am looking into the issue.

**Comment by alf45tar** [comment]
To fix the NimBLE advertising error add the following line to `lib_deps` in platform.ini

https://github.com/h2zero/NimBLE-Arduino

I will release it to `master` branch soon.

**Comment by alf45tar** [comment]
Also the BOOT button always LOW depends by a 3rd party library. In this case FastLED. Returned to version FastLED 3.3.3.
