### ISSUE TITLE
Could not find remote branch feat/2.0.0 to clone

### ISSUE THREAD

**Issue by WernAir77** [alf45tar/PedalinoMini#154]
Hey, 

first of all, thank you very much for this awesome project.

But I have an issue during the PlatformIO. build. Warning text:"Could not find remote branch feat/2.0.0 to clone" Do I need an extension? Or what I'm doing wrong?
It's my first time with Visual Studio.
Maybe this issue is already solved, but I did not find anything.
I work on Mac, Python 2.7 is installed, PlatformIO IDE (latest Version) is also installed. I fixed the issue that the .confit could not be found.

**Comment by alf45tar** [comment]
The latest branch is `master` which include PedalinoMini version 2.

**Comment by WernAir77** [comment]
How can I change it? Pedalino.Uni?

**Comment by WernAir77** [comment]
Now I have already 26 problems with unused variable 'checkPoint', 'channelNr.', ...

**Comment by alf45tar** [comment]
Sorry I am lost. What version of PedalinoMini are you compiling? `master` branch or release `v1.0.0`?

Use `master` branch. Release `v1.0.0` is there only for historical reason.
