### ISSUE TITLE
Can't connect with ESP32 after upload 

### ISSUE THREAD

**Issue by WernAir77** [alf45tar/PedalinoMini#155]
After solving some problems before, I'm actually not at the finish.

During upload Error 1 came. I my mind it is a connection Error between Mac and ESP32. (ESP32 DevKitC V2 from AZ Delivery).
The ESP is out of the box. Do I need to do some pre configuration, firmware updates, etc.? Or do I need to bring the ESP into the upload mode? When 'YES', how?

**Comment by WernAir77** [comment]
esp32doit-devkit-v1-ble und esp32doit-devkit-v1 are uploaded. I installed some driver and after that, it worked.

So far so good, but how can I connect with Bluetooth or WiFi? iPhone and iPad can't find new hardware

**Comment by alf45tar** [comment]
For Bluetooth connection you can use Garageband, MIDI Wrench or midimittr.
For Wifi connection setup you can use MIDI Network.

**Comment by WernAir77** [comment]
All programs can't find the ESP. Actually I don't connect buttons, but in my mind it should be found as well, or am I wrong?

**Comment by alf45tar** [comment]
esp32doit-devkit-v1-ble has no Wifi, only BLE.

esp32doit-devkit-v1 has Wifi and BLE. In order to use Wifi you must connect PedalinoMini to your router or connect your iPhone to PedalinoMini access point.

**Comment by WernAir77** [comment]
How do I choose which esp32doit would be installed? 
It's my first time on Visual Studio and auch a project...

**Comment by alf45tar** [comment]
![Screenshot 2020-11-29 at 17 54 39](https://user-images.githubusercontent.com/35426671/100548323-0f54bb00-326c-11eb-9ebf-aa5cf7273f57.png)

**Comment by WernAir77** [comment]
Thanks a lot. I installed the BLE, build and upload was successful, but I can't connect with the ESP32. 
The LED on the board is blinking, some bright, many short and low light. Is this normal, or is there an problem with the board?

**Comment by alf45tar** [comment]
Did you have a display?
If not you can use the serial monitor.

**Comment by WernAir77** [comment]
Did you mean "upload and monitor" or "monitor"?

**Comment by alf45tar** [comment]
1. Re-sync PedalinoMini source code (platformio.ini has been updated yesterday).
2. Delete `libdeps`
3. Upload & Monitor

**Comment by WernAir77** [comment]
Where do I find the libdeps? In the new downloaded PedalinoMini folder isn't such a file and no hidden files, etc...

**Comment by alf45tar** [comment]
`libdeps` is where you build the PedalinoMini.

**Comment by WernAir77** [comment]
Finally I found it. Command+Shift+. doesn't work at El Capitan 😬
Now it works fine and I can connect via bluetooth.

Thanks a lot
