### ISSUE TITLE
PedalinoMini BLE not discoverable ?

### ISSUE THREAD

**Issue by quangvankts** [alf45tar/PedalinoMini#156]
Hi 
I cant find PedalinoMini BLE using both my iPhone and Macbook 
It does show “BLE MIDI service advertising started” in monitor window when started and still can connect to local Wifi network.
PS: I could only run “Build” and “Upload”. But not “Upload File System Image” since I can’t find it anywhere, if it matters.
Thanks !
Update: I did “Upload File System Image” as well but still can't find connect to ESP32 using BLE. Everything else seems to work fine.

**Comment by alf45tar** [comment]
BLE is not bluetooth. Do not use Bluetooth from Settings.
To connect to PedalinoMIDI via BLE you can use Garageband, midimittr or MIDI Wrench.

**Comment by quangvankts** [comment]
Got it 
Thanks !
