### ISSUE TITLE
Reboots repeatedly

### ISSUE THREAD

**Issue by someshout** [alf45tar/PedalinoMini#157]
Hi alf45tar,
Thanks for your sharing this repository with us.

I followed your guide and have encountered a problem, My project is stuck in "Boot Mode" select stage and Esp32 reboots repeatedly.

I pressed the En & Boot button ,but it does not work.
Boot button is not reponding.
En button  will force reboot ESP32.

Do you have any suggestions?

**Comment by alf45tar** [comment]
It is solved here https://github.com/alf45tar/PedalinoMini/issues/155#issuecomment-735606131

**Comment by someshout** [comment]
Thanks~ It's working!!
![P_20201202_164437](https://user-images.githubusercontent.com/23203469/100857090-3529cc00-34c7-11eb-9578-98d8db259bee.jpg)
![P_20201202_164446](https://user-images.githubusercontent.com/23203469/100857112-3ce97080-34c7-11eb-96a6-dac77e8ac242.jpg)

**Comment by alf45tar** [comment]
I think you missed the last step Upload File System Image

https://github.com/alf45tar/PedalinoMini#how-to-build-and-upload

**Comment by someshout** [comment]
Thanks~~~
![image](https://user-images.githubusercontent.com/23203469/100969764-9658aa80-356e-11eb-9ca3-c2c15aeb9ab1.png)
