### ISSUE TITLE
Antenna Pin Out

### ISSUE THREAD

**Issue by marosell** [alf45tar/PedalinoMini#16]
Since most will want to put this in an aluminum enclosure to support heavy-duty buttons and foot use, I fear that the wireless capabilities will be very effectively shielded. Are there certain pin-outs for antenna to stick out of enclosure?

**Comment by alf45tar** [comment]
I think you need and ESP32 board with external antenna connector.  Not hard to find on google.
As alternative you can try to sold your external antenna to the internal antenna. Not sure of the result.

Please share with us your final result with the enclosure.

Thanks
alf45tar

**Comment by marosell** [comment]
I went ahead and ordered the ESP32-DevKitC-32U board which includes a U.FL/IPEX connector for an external antenna (ESP32-DevKitC-32U). I'm sure I have an antenna lying around somewhere. Once I have my build put together, will report back.

For pedal enclosure applications, I might make boards with U.FL connectors a recommendation on the material list (note that the TTGO card listed has a U.FL connector as well, but that card is no longer available?). As a dev board, the ESP32-DevKitC-32U is also suitable for breadboard use.

**Comment by marosell** [comment]
FYI, I was able to connect an external antenna using a U.FL connector. Works great, and the WIFI bars doubled on this particular board (probably because there isn't an internal antenna on this card).

![IMG_6978](https://user-images.githubusercontent.com/1125586/64084670-a21a4900-ccfb-11e9-9bc6-a70d8092d40f.JPG)
