### ISSUE TITLE
Strange behavior of "Action" menu of Web UI

### ISSUE THREAD

**Issue by MaxZak2020** [alf45tar/PedalinoMini#164]
Dear Alf45tar!
Thanks for your great work with this progect. I've made it and it works generally. But I have some issues during tuning it for my goals.

When I tried to configure ladder with 6 buttons first time "Apply" and "Save" disappear when I added Button 6. ![screenshot-31b267ac local-2020 12 27-20_00_17](https://user-images.githubusercontent.com/74506186/103178438-d40dd200-4893-11eb-92eb-b957e475c170.png)

But when I've deleted Pedal 2 those buttons are appeared again and I've save it but when I added Pedal 2, "Apply" and "Save" disappiared again. 
![screenshot-31b267ac local-2020 12 27-21_24_31](https://user-images.githubusercontent.com/74506186/103178454-fbfd3580-4893-11eb-9d83-9666a0aee0ad.png)

But after I've deleted and added Pedal 2 it again looks like suppose to be... 
![screenshot-31b267ac local-2020 12 27-22_05_05](https://user-images.githubusercontent.com/74506186/103178464-07e8f780-4894-11eb-88a4-acd2393f361a.png)

It's strange and can to confuse))

**Comment by alf45tar** [comment]
Thanks @MaxZak2020 for your detailed contribution. I will have a look.

**Comment by alf45tar** [comment]
A long list of actions requires a lot of memory to create the web page. Sometime the memory is not enough to complete the page creation and the page is incomplete.
To avoid it I suggest:
1. Use the filter at the top to display one pedal per time
2. Boot in WIFi mode to free Bluetooth memory during configuration

I am exploring alternatives like creating page in trunks (I am already sending page in trunk).

Regards
alf45tar

**Comment by MaxZak2020** [comment]
I see! Ok Thanks!
