### ISSUE TITLE
Wrong serial midi data via USB

### ISSUE THREAD

**Issue by davethegrinch** [alf45tar/PedalinoMini#169]
Hello, 
Firstly, thanks for all the great work you've put into this. 

The problem I'm seeing is that sending midi data via serial USB is not working correctly. I have a Sparkfun ESP32 Thing and a Sparkfun Micro Pro configured as the instructions say. 

When I operate an analog pot, I see the right midi CC values generated on the ESP32 but when I monitor in the incoming midi on my mac that CC messages are replaced by a stream of other midi messages such as Program Change, note off, CC on a random selection of channels. 

<img width="455" alt="Screen Shot 2020-12-30 at 6 13 49 PM" src="https://user-images.githubusercontent.com/58012859/103390725-d312b580-4aca-11eb-8689-4b4b4f600889.png">

If I turn on IPMidi interface and monitor that from my mac, I see exactly the right messages. 
<img width="385" alt="Screen Shot 2020-12-30 at 6 14 58 PM" src="https://user-images.githubusercontent.com/58012859/103390768-f3427480-4aca-11eb-9541-2a7ac91c76b0.png">

Something is not translating well from Micro Pro board. I have the UsbMidiConvertor library loaded and I can program that to send hardcoded midi message just fine. I've matched the baud rate in the convertor to ESPSerialMIDI.h (115200). But something between the micro pro and ESP32 board is not working even though they share the same GND. 

Any ideas??

Thanks...
Dave

**Comment by alf45tar** [comment]
Are ESP32 board and Pro Micro sharing the GND?

**Comment by davethegrinch** [comment]
I believe so. I have them both connected to a common GND bus.

**Comment by davethegrinch** [comment]
I think I might have a ground loop somewhere.

**Comment by davethegrinch** [comment]
Well - turns out it was a bad pro micro board. Issue closed
