### ISSUE TITLE
Bank Select +/-

### ISSUE THREAD

**Issue by MaxZak2020** [alf45tar/PedalinoMini#173]
Hi there. Unfortunately I can not understand how to use Bank Select + to change bank of Program patches in midi unit. Would you please explain how shoul I use MSB and LSB in both casese (+ and -)

I've tryed like that: MSB=0 and LSB = 0-127 for + and -
But Tone Stack (guitar processor iOS soft) blinks to next Bank and then back to Bank 0 when push + (for - it is the same but negative - it lows down the bank and then switches to 0).

**Comment by alf45tar** [comment]
@MaxZak2020 try the latest version.
It should work as documented.

**Comment by MaxZak2020** [comment]
Thanks a lot. I will try after new ESP32 board has come.. Old one has usb port burned.

**Comment by alf45tar** [comment]
@MaxZak2020 may I close the issue?

**Comment by bobvc133** [comment]
> @MaxZak2020 try the latest version. It should work as documented.
BOSS GT1000CORE cannot use the BNAK SELECT+/- function normally, is this function working normally now?

![Snipaste_2023-02-18_20-11-49](https://user-images.githubusercontent.com/91867813/219865351-b7bd5e9f-7d99-4c57-9451-8d8a4bb15208.jpg)
![Snipaste_2023-02-18_20-12-40](https://user-images.githubusercontent.com/91867813/219865356-3a546825-bf08-4e27-93b4-c07744871882.jpg)
![Snipaste_2023-02-18_20-16-31](https://user-images.githubusercontent.com/91867813/219865358-ccc74308-5ad0-4550-af55-f277fc24c729.jpg)

https://www.thegearpage.net/board/index.php?threads/boss-gt-1000core-midi-mapping-banks-1-4-do-they-actually-work-solved.2375020/
