### ISSUE TITLE
LED hardcoded number

### ISSUE THREAD

**Issue by joesuspense** [alf45tar/PedalinoMini#177]
I've got 8 LEDs in my enclosure, but noticed the UI it's limited to 6.  It seems to be this line. I'm testing increasing this to 8, but troubleshooting other issues with the LEDS that prevent me from confirming if this works. Should it be OK to change this?

https://github.com/alf45tar/PedalinoMini/blob/98109a939335dfc4aba8b798fcfac99034d5c112/src/Pedalino.h

#define LEDS              6   // number of WS2812B leds

**Comment by alf45tar** [comment]
Yes, it is ok.
