### ISSUE TITLE
Through-hole neopixels - wrong colors

### ISSUE THREAD

**Issue by joesuspense** [alf45tar/PedalinoMini#178]
I purchased some individual through-hole and they were showing up the wrong color. Just a heads up that I was able to resolve 
this for my LEDs by changing:

  FastLED.addLeds<NEOPIXEL, FASTLEDS_DATA_PIN>(fastleds, LEDS);
to
  FastLED.addLeds<WS2812, FASTLEDS_DATA_PIN>(fastleds, LEDS);

https://github.com/alf45tar/PedalinoMini/blob/98109a939335dfc4aba8b798fcfac99034d5c112/src/PedalinoMini.cpp

This may be useful for others.

**Comment by alf45tar** [comment]
Thanks
