### ISSUE TITLE
Problem with legacy midi

### ISSUE THREAD

**Issue by teopost** [alf45tar/PedalinoMini#181]
In the mail README I read:

_Legacy serial MIDI interface with 5 pins DIN connectors. Requires additional hardware (see schematic)._

![image](https://user-images.githubusercontent.com/2573389/107118085-10fbba00-687f-11eb-970a-8504c70d96f8.png)

but in the diagram it seems to me that it is possible to use the legacy midi without using other hardware.

![image](https://user-images.githubusercontent.com/2573389/107118217-d0507080-687f-11eb-826b-2316cfe44fd1.png)

I am wrong ?

I ask this because I can't get it to work!

![pedalinomini](https://user-images.githubusercontent.com/2573389/107118178-9f703b80-687f-11eb-865e-dd8ee03f8fda.png)

**Comment by alf45tar** [comment]
Additional hardware means a couple of resistors and a connector.
Di you tried to invert blank and red wire?

**Comment by teopost** [comment]
No. it seems to me that it is correct

![din](https://user-images.githubusercontent.com/2573389/107121516-2975cf80-6893-11eb-93b5-29d6e1ce3b06.png)

![image](https://user-images.githubusercontent.com/2573389/107121531-532ef680-6893-11eb-8ff6-d57ea535b20d.png)

maybe the configuration is wrong?

Configuration

![image](https://user-images.githubusercontent.com/2573389/107121592-94270b00-6893-11eb-8c31-8b746421306d.png)

Pedals

![image](https://user-images.githubusercontent.com/2573389/107121614-ab65f880-6893-11eb-9dfc-13b0ead619e0.png)

Actions

![image](https://user-images.githubusercontent.com/2573389/107121627-bf115f00-6893-11eb-9975-e4f8f23c340b.png)

**Comment by alf45tar** [comment]
May I suggest to add the optional led to see the MIDI traffic?

**Comment by teopost** [comment]
the led is always off

![led_midi](https://user-images.githubusercontent.com/2573389/107124434-2df6b400-68a4-11eb-861d-1a895ac4d2fa.png)

**Comment by teopost** [comment]
@alf45tar the configuration is correct ?

**Comment by alf45tar** [comment]
Yes, it is

**Comment by alf45tar** [comment]
Yes, it is

**Comment by teopost** [comment]
It has been compiled since the last commit

![image](https://user-images.githubusercontent.com/2573389/107129755-0f0a1900-68c8-11eb-83b1-87c51be70787.png)


The oled display is a wemos oled shield that I had. I already know it's not supported.

I have to buy a compatible one but first I have to get the legacy midi to work

**Comment by teopost** [comment]
erasing the eeprom it works!

https://www.youtube.com/watch?v=DIaNEkbmiro&feature=youtu.be

Thank you! Fantastic project!!!!
