### ISSUE TITLE
Problem in configuring Sequences

### ISSUE THREAD

**Issue by teopost** [alf45tar/PedalinoMini#182]
I have configured a pedal to perform a Sequence

![image](https://user-images.githubusercontent.com/2573389/107158036-c023b880-6987-11eb-8fc1-8e89aef805d9.png)

![image](https://user-images.githubusercontent.com/2573389/107158051-d16cc500-6987-11eb-8d85-492b247325f2.png)

it seems that the value sent to the midi is always 2, that is the one configured in Pedals and not in the Sequences

![image](https://user-images.githubusercontent.com/2573389/107158094-14c73380-6988-11eb-9cd8-c9b95d766b07.png)

What am I doing wrong ?

**Comment by alf45tar** [comment]
You are not doing anything wrong.
It is by design. Every CC in a sequence is transmitting the value coming from the pedal. It makes sense if it connected to a Analog or Jog Wheel pedal. It doesn't make sense for Momentary/Latch pedals.
It is an historical feature before the Actions era. With multiple Actions by pedal it is not anymore requested.
I will fix it.

**Comment by teopost** [comment]
Can I only use actions to send a sequence of messages?

**Comment by alf45tar** [comment]
Yes, you can if the numbers of messages to send it is not too long.
Otherwise a Sequence is better.

**Comment by teopost** [comment]
if I execute 2 commands in sequence in this way using Actions, the device I am controlling does not accept them.

![image](https://user-images.githubusercontent.com/2573389/107277563-e1060f80-6a54-11eb-9e70-3501ede90786.png)

It only works if I run the second command with "On Release"

![image](https://user-images.githubusercontent.com/2573389/107277887-5b369400-6a55-11eb-9346-37a581aa908d.png)

I think a short sleep from one command to another is needed

I did a test with another arduino project

![image](https://user-images.githubusercontent.com/2573389/107278242-c6806600-6a55-11eb-8dd6-71e38d8b4b17.png)

I think it would be useful to be able to add a pause between CC commands

**Comment by teopost** [comment]
Wow! Great buy!

**Comment by davidin73** [comment]
I'm interested about this problem because my intention is to have more than 3 snapshots with the commands sequences,as rhemorningstar' products

**Comment by teopost** [comment]
AHHH! I have the same problem too!

**Comment by teopost** [comment]
HX stomp does not have a native patch up/dn midi command so we can switching to scroll mode and emulating a FS1/2 button press.
I did this with this project

* https://github.com/mattzzw/midi_muppet_hx_2btn

**Comment by davidin73** [comment]
Hm, no....i wanna be have a different approach.
The concept is :if I can have different variations of the same preset with the snapshot,i can have 'more snapshots' by changing the various blocks parameters, with a sequence of CC..
And/or by changing a preset with the trails activated.
I think I can do this with the cc sequences, to avoid the silence between the programs/presets change

**Comment by teopost** [comment]
PedalinoMini is better than morning star!

**Comment by davidin73** [comment]
Sure! This is why I'm building a pedalino mini for my stomp🤗

**Comment by teopost** [comment]
I'll show you my next pedalboard just finished

**Comment by teopost** [comment]
> Sure! This is why I'm building a pedalino mini for my stomp🤗

How many switches?

**Comment by davidin73** [comment]
8 swirches
