### ISSUE TITLE
Click and Press differences

### ISSUE THREAD

**Issue by teopost** [alf45tar/PedalinoMini#183]
What is the difference between the click and press events?

**Comment by alf45tar** [comment]
Press is press. Event is trigger when button is pressed.
Click is press + release.  Event is trigger when button is released.

Press is more reactive.

**Comment by teopost** [comment]
Thank you.
Is there a Telegram channel of pedalinomini?

**Comment by alf45tar** [comment]
There is no Telegram channel.
To be more precise. Click is different from Release.
Between a Press event and a Release event can pass any amount of time.
A Click event is triggered only if the button is pressed and released within a certain amount of time.
