### ISSUE TITLE
Problem configuring midi block bypass with HX Stomp

### ISSUE THREAD

**Issue by teopost** [alf45tar/PedalinoMini#184]
HX Stomp can be configured to bypass a block using midi command

From manual: "CC values 0-63 turn the block off; values 64-127 turn the block on."

If I configure a pedal with "From value" to 5 and "To value" to 65 the block turns off when the pedal is ON (and viceversa)

I inverted the values by putting "From value" to 65 and "To value" to 5 but when I do it pedalinomini doesn't work and the display goes crazy!

See video here:  https://www.youtube.com/watch?v=BB86vlJ_4RQ&feature=youtu.be

**Comment by alf45tar** [comment]
Thanks for feedback. I am going to fix.

**Comment by alf45tar** [comment]
It was only a display issue. Fixed.

**Comment by teopost** [comment]
Tested!
It works. Thank you
