### ISSUE TITLE
Awesome yellow box build

### ISSUE THREAD

**Issue by teopost** [alf45tar/PedalinoMini#186]
Hi,
  my first pedalboard with PedalinoMini is almost finished !
I would like to thank you by putting the PedalinoMini logo 

![yellow-first](https://user-images.githubusercontent.com/2573389/108223166-d07f2480-7139-11eb-8d57-c5ac22571e9a.png)

Can you provide me the svg file?

**Comment by alf45tar** [comment]
Just uploaded. Check under images folder.
I am excited to see the final assembly.

**Comment by teopost** [comment]
I have some pictures on its construction. if you need them tell me where to put them

**Comment by alf45tar** [comment]
Upload here or create a separate issue/discussion for your build.
I will add one picture on the home page.

**Comment by teopost** [comment]
I still don't know how to put the logo!

![trasferelli](https://user-images.githubusercontent.com/2573389/108533014-c9dae380-72d8-11eb-8119-51439cb4d94d.jpg)

**Comment by teopost** [comment]
![IMG_3475](https://user-images.githubusercontent.com/2573389/109355763-02059780-7880-11eb-88f4-3630039a3324.png)

![IMG_3473 2](https://user-images.githubusercontent.com/2573389/109355786-0cc02c80-7880-11eb-9d7c-7eb23dfa2dee.png)

https://www.youtube.com/watch?v=XpELX5sSgZE&feature=youtu.be

**Comment by davidin73** [comment]
Ho Stefano.
what kind of container did you use for pedalino? (excellent result by the
way ...)

Il ven 26 feb 2021, 22:15 Stefano Teodorani <notifications@github.com> ha
scritto:

**Comment by teopost** [comment]
Hi,
   I uploaded all the images here 

https://photos.app.goo.gl/4xGTSbXWA1XYLDvw9

Enclosure is this

https://www.amazon.it/dp/B0827VQQ69?ref=ppx_pop_mob_ap_share

Ps: ma sei italiano ?

Inviato da iPhone

**Comment by davidin73** [comment]
Di Trieste 😁😁😁

Il ven 26 feb 2021, 22:46 Stefano Teodorani <notifications@github.com> ha
scritto:

**Comment by alf45tar** [comment]
@teopost 
Awesome job.

**Comment by jimhiggs** [comment]
Did you include wifi and bluetooth? and if so how well do they work inside the case?

**Comment by teopost** [comment]
I use only wifi and work fine

**Comment by jimhiggs** [comment]
Thanks. I made the little black one with red buttons and the Pedalinomini tm on the front. Have added a rotary encoder for bank select and usb midi and use a TC Helicon Switch 6 with it. Think I will build a new version with 8 switches and sell the switch 6. I will also make one of those 2 button switches in your link for my HX Stomp. Useful little pedal.

**Comment by jimhiggs** [comment]
I will probably add midi thru as well so can use both at once.  It would be really something if I could put a bigger screen on it though, the info screens are too small for me to read so I just use patch/bank names. The full range of midi options on the padalinomini are awesome though. I have driven my Hx using rptmidi over wifi between the box and my pc and usbmidi to Hx from my pc. I have also used the Bluetooth midi. Fantastic.
