### ISSUE TITLE
TC ladder issue/challenge

### ISSUE THREAD

**Issue by wrpooley** [alf45tar/PedalinoMini#188]
I have limited experience with reading circuits but I've basically duplicated the design of BotsmanDead for the Ladder6 resistor ladder.  However, when I boot into Ladder Config and calibrate each button, I only Pedal:0 and Button:0 for each of the 6 buttons.  Also, the Ladder Level values posted in the serial monitor on re-boot are oddly close together for the first 4 values (ascending) and the same for value 5 & 6 (see screenshot below).  

If anyone would be so kind as to review the attached media and see of there is anything wrong with my wiring?  One are of confusion for me is the +3V and 10K resistor show on an analog pin (A1, etc).  If it's not clear form the pictures, I have GND going though a 10k resistor to the start of the ladder, one leg of the switch going to D1 (GPIO_25) and the other leg of all the switches connected together in series and connected to A1 (GPIO_36).

I appreciate any help in this matter.  And if anyone has a good resource for someone trying to learn how to build a circuit from a schematic I'd appreciate that too!
![IMG_4256](https://user-images.githubusercontent.com/61659362/108926107-c5316a80-760b-11eb-8d8c-17cd285d5580.jpg)
![IMG_4254](https://user-images.githubusercontent.com/61659362/108926134-ce223c00-760b-11eb-8387-afa9970d5187.jpg)
![IMG_4255](https://user-images.githubusercontent.com/61659362/108926136-cebad280-760b-11eb-86a4-a154728d4e21.jpg)

https://user-images.githubusercontent.com/61659362/108926565-ae3f4800-760c-11eb-9660-f907cd025f5b.mp4

**Comment by alf45tar** [comment]
Is the brown resistor of the ladder of 10k? It looks like is only 1k.

**Comment by wrpooley** [comment]
Yes.  It measure 10k on multi-meter.  I could certainly swap out for same
type as ladder.

**Comment by rigr** [comment]
Just a quick idea: Does the resistor in red circle go to the correct hole
in the breadboard?

Am Mi., 24. Feb. 2021 um 14:37 Uhr schrieb wrpooley <
notifications@github.com>:

> Yes. It measure 10k on multi-meter. I could certainly swap out for same
> type as ladder.
>

**Comment by rigr** [comment]
oh, attachment not visible - here it comes:
![resist_](https://user-images.githubusercontent.com/6568315/109009607-0595f480-76af-11eb-936f-9b9bb56249db.jpg)

**Comment by rigr** [comment]
well, just saw that in the video it looks like it is connected to the correct hole.

**Comment by wrpooley** [comment]
Yes I believe it is.

**Comment by alf45tar** [comment]
It must be connected to line 17

**Comment by wrpooley** [comment]
That is correct. I also made all 10k the same type. No difference.

**Comment by alf45tar** [comment]
I don't see the pull-up resistor for A1. It is a 10k resistor from A1 (GPIO_36) and +3.3V

**Comment by wrpooley** [comment]
I’m afraid this is where my knowledge of circuit design breaks down!

Does that mean I simply put a 10k resistor between the 3V rail and A1 and
leave the connector from the end of the switches also to A1? If I do that,
then during the calibration, all of the switches ladder level is 1010

Grateful for you hand holding!

**Comment by alf45tar** [comment]
Because the orange wire is not connected to GND.

**Comment by wrpooley** [comment]
DOH!  That did it. Thank you so much.
