### ISSUE TITLE
WebUI Themes

### ISSUE THREAD

**Issue by jimhiggs** [alf45tar/PedalinoMini#189]
Do I have to do anything other than select a theme? All options appear un-themed when I use them. My Pedalino mini is using wifi to connect to  my home network which has internet connection.

**Comment by alf45tar** [comment]
I updated Bootstrap to version 5 but themes for version 5 are not yet released.
Bootstrap 5 is still in beta.

**Comment by jimhiggs** [comment]
Ok Thanks. Bootstrap looks great, just thought I would take a look.
