### ISSUE TITLE
Long press and single press priority

### ISSUE THREAD

**Issue by teopost** [alf45tar/PedalinoMini#193]
Button 4 in this image has 2 functions

![image](https://user-images.githubusercontent.com/2573389/109411456-8d774980-79a2-11eb-875e-8209a5fe4b3e.png)

1. LONG PRESS: Activate remote TUNER
2. PRESS: Preset selection of my controlled device

When I do a "long press" the tuner is activated correctly, but the press event is also triggered and the preset is changed

Is there a way to prevent the preset from being changed when I do a long press?

**Comment by akosbeke** [comment]
HI @teopost 

Try changing the PRESS action to a CLICK action.

**Comment by teopost** [comment]
The result is the same
When I activate the tuner, I don't want the preset to be changed

**Comment by alf45tar** [comment]
Use CLICK for preset and LONG PRESS for tuner. It should work.

The event PRESS is triggered immediately on press and if the pedal is keep pressed for a long period also LONG PRESS is triggered.
CLICK is triggered when the pedal is pressed and released quickly before the LONG PRESS timeout.

**Comment by teopost** [comment]
OK. I do some tests
Thanks for your patience!

**Comment by teopost** [comment]
It works. Thank you
