### ISSUE TITLE
Program Change+/- should start from last Program Change

### ISSUE THREAD

**Issue by teopost** [alf45tar/PedalinoMini#194]
Yesterday I played with my band and my new Pedalinomini!

![pedalboard-1](https://user-images.githubusercontent.com/2573389/109465879-27092e80-7a69-11eb-80f7-a051c9dd9051.png)

I still have to finish the configuration of Pedalinomini, but everything worked fine.
However, I have noticed a problem with this configuration:

* Button 4: "Program Change 1" - (Go to Preset 1)
* Button 5: "Program Change -"
* Button 6: "Program Change +"

During the performance I changed the preset with button 6 until reaching value 7

Then I pressed button 1 to go back to preset 1

When I later pressed button 6 I expected PC 2, instead Pedalinomini sent PC8

PS: I know! I have to fix the cables!

**Comment by alf45tar** [comment]
Fixed in the latest version just released
Thanks for debugging

**Comment by teopost** [comment]
Thanks @alf45tar 
Note: Using Pedalinomini with the band, I realized that the display is a bit small for me

**Comment by alf45tar** [comment]
I agree display is a bit small but the project must remain affordable for everyone.

**Comment by teopost** [comment]
Tested. It's works
