### ISSUE TITLE
By changing LED's color when it is on OFF status, it is set on ON status

### ISSUE THREAD

**Issue by teopost** [alf45tar/PedalinoMini#198]
When I turn ON the switch, the color associated with the status is switched
When I restart pedalinomini the leds works fine 

https://www.youtube.com/watch?v=6ccRJRoHGuE

**Comment by alf45tar** [comment]
I am aware of that "bug" but never fixed because it is not too much disturbing.
I will fix soon or later.

Thanks again @teopost

**Comment by alf45tar** [comment]
Fixed
