### ISSUE TITLE
Accessing ladder config

### ISSUE THREAD

**Issue by FabrizioGrasso0289** [alf45tar/PedalinoMini#201]
I have 2 butttons configured as momentary with Control change 12, 62 for MIdi and the BOOT & EN buttons from the ESP-32 devkit board,

How can i access the ladder config boot mode?

**Comment by alf45tar** [comment]
Press and release EN button and immediately after press and hold BOOT button.

Keep it pressed until the display show "Ladder Config". Release the BOOT button and press all the ladder buttons in sequence. There is a bar showing the remaining time to press the button. Press and keep pressed the first ladder button until the timeout bar reach zero. When the timeout restart press the second button and so on.
