### ISSUE TITLE
Possible momentary 2 schematics?

### ISSUE THREAD

**Issue by davidin73** [alf45tar/PedalinoMini#202]
Hi!
Is this maybe a good connection schematic for a 4x2 momentary switches model,or i must put a 10k resistor on every 'ring' connection?
(Excuse me for the horrible sketch😅)
![16165105662134488262962328683998](https://user-images.githubusercontent.com/72359395/112164802-7bc64200-8bee-11eb-9944-62be24759afa.jpg)

**Comment by alf45tar** [comment]
PIN_A1, PIN_A2, PIN_A3 and PIN_A4 are connected together. It is not correct.
Each analog pin must have e separate pull up resistor.

**Comment by davidin73** [comment]
Okay, thank you very much!
🤗

**Comment by alf45tar** [comment]
Digital pins are correct.

**Comment by davidin73** [comment]
Thank you very much!
