### ISSUE TITLE
config files structure

### ISSUE THREAD

**Issue by rigr** [alf45tar/PedalinoMini#203]
Thanks again alf45tar for your great project. I just installed the latest version and all looks good after some minor tweaks (the options-page was not displayed, it took several reboots).
While setting up the pedalino I thought it would be cool if I could use an external (java) program to write a config file and then upload, because clicking through the interface is very time consuming and would be a lot easier to be done on my laptop. Such a software might even be enhanced with graphical environment to show colors of LEDs etc.
Would you mind explaining the config files?
Thank you and best regards
Richard

**Comment by alf45tar** [comment]
Before any update save configuration, reset to factory default and reload configuration. EEPROM can change without any further advice.

There is nothing fancy in the configuration file. It is just a JSON file.

{
  "Pedals": [
    {
      "Pedal": 1,
      "Function": 1,
      "AutoSensing": 0,
      "Mode": 2,
      "PressMode": 1,
      "InvertPolarity": 0,
      "MapFunction": 0,
      "Min": 0,
      "Max": 127
    },
    {
      "Pedal": 2,
      "Function": 1,
      "AutoSensing": 0,
      "Mode": 2,
      "PressMode": 1,
      "InvertPolarity": 0,
      "MapFunction": 0,
      "Min": 0,
      "Max": 127
    },
    {
      "Pedal": 3,
      "Function": 1,
      "AutoSensing": 0,
      "Mode": 2,
      "PressMode": 1,
      "InvertPolarity": 0,
      "MapFunction": 0,
      "Min": 0,
      "Max": 127
    },
    {
      "Pedal": 4,
      "Function": 1,
      "AutoSensing": 0,
      "Mode": 2,
      "PressMode": 1,
      "InvertPolarity": 0,
      "MapFunction": 0,
      "Min": 0,
      "Max": 127
    },
    {
      "Pedal": 5,
      "Function": 1,
      "AutoSensing": 0,
      "Mode": 4,
      "PressMode": 1,
      "InvertPolarity": 0,
      "MapFunction": 0,
      "Min": 102,
      "Max": 921
    },
    {
      "Pedal": 6,
      "Function": 1,
      "AutoSensing": 0,
      "Mode": 4,
      "PressMode": 1,
      "InvertPolarity": 0,
      "MapFunction": 0,
      "Min": 102,
      "Max": 921
    }
  ],
  "BankNames": [
    {
      "Bank": 1,
      "Name": ":Mode 1"
    },
    {
      "Bank": 2,
      "Name": ":Mode 2"
    },
    {
      "Bank": 3,
      "Name": ""
    },
    {
      "Bank": 4,
      "Name": ""
    },
    {
      "Bank": 5,
      "Name": ""
    },
    {
      "Bank": 6,
      "Name": ""
    },
    {
      "Bank": 7,
      "Name": ""
    },
    {
      "Bank": 8,
      "Name": ""
    },
    {
      "Bank": 9,
      "Name": ""
    },
    {
      "Bank": 10,
      "Name": ""
    },
    {
      "Bank": 11,
      "Name": ""
    },
    {
      "Bank": 12,
      "Name": ""
    },
    {
      "Bank": 13,
      "Name": ""
    },
    {
      "Bank": 14,
      "Name": ""
    },
    {
      "Bank": 15,
      "Name": ""
    },
    {
      "Bank": 16,
      "Name": ""
    },
    {
      "Bank": 17,
      "Name": ""
    },
    {
      "Bank": 18,
      "Name": ""
    },
    {
      "Bank": 19,
      "Name": ""
    },
    {
      "Bank": 20,
      "Name": ""
    }
  ],
  "Actions": [
    {
      "Bank": 1,
      "Pedal": 1,
      "Button": 1,
      "Name": "[ A ]",
      "Event": 0,
      "Message": 144,
      "Channel": 1,
      "Code": 60,
      "Value1": 100,
      "Value2": 100
    },
    {
      "Bank": 1,
      "Pedal": 1,
      "Button": 1,
      "Name": ">   A   <",
      "Event": 1,
      "Message": 128,
      "Channel": 1,
      "Code": 60,
      "Value1": 0,
      "Value2": 0
    },
    {
      "Bank": 1,
      "Pedal": 2,
      "Button": 1,
      "Name": "[ B ]",
      "Event": 0,
      "Message": 144,
      "Channel": 1,
      "Code": 62,
      "Value1": 100,
      "Value2": 100
    },
    {
      "Bank": 1,
      "Pedal": 2,
      "Button": 1,
      "Name": ">   B   <",
      "Event": 1,
      "Message": 128,
      "Channel": 1,
      "Code": 62,
      "Value1": 0,
      "Value2": 0
    },
    {
      "Bank": 1,
      "Pedal": 3,
      "Button": 1,
      "Name": "[ C ]",
      "Event": 0,
      "Message": 144,
      "Channel": 1,
      "Code": 64,
      "Value1": 100,
      "Value2": 100
    },
    {
      "Bank": 1,
      "Pedal": 3,
      "Button": 1,
      "Name": ">   C   <",
      "Event": 1,
      "Message": 128,
      "Channel": 1,
      "Code": 64,
      "Value1": 0,
      "Value2": 0
    },
    {
      "Bank": 1,
      "Pedal": 4,
      "Button": 1,
      "Name": "[ D ]",
      "Event": 0,
      "Message": 144,
      "Channel": 1,
      "Code": 65,
      "Value1": 100,
      "Value2": 100
    },
    {
      "Bank": 1,
      "Pedal": 4,
      "Button": 1,
      "Name": ">   D   <",
      "Event": 1,
      "Message": 128,
      "Channel": 1,
      "Code": 65,
      "Value1": 0,
      "Value2": 0
    },
    {
      "Bank": 1,
      "Pedal": 5,
      "Button": 1,
      "Name": "[ E ]",
      "Event": 6,
      "Message": 176,
      "Channel": 1,
      "Code": 12,
      "Value1": 0,
      "Value2": 127
    },
    {
      "Bank": 1,
      "Pedal": 6,
      "Button": 1,
      "Name": "[ F ]",
      "Event": 6,
      "Message": 176,
      "Channel": 1,
      "Code": 13,
      "Value1": 0,
      "Value2": 127
    },
    {
      "Bank": 2,
      "Pedal": 1,
      "Button": 1,
      "Name": "[ A ]",
      "Event": 0,
      "Message": 176,
      "Channel": 1,
      "Code": 20,
      "Value1": 127,
      "Value2": 127
    },
    {
      "Bank": 2,
      "Pedal": 1,
      "Button": 1,
      "Name": ">   A   <",
      "Event": 1,
      "Message": 176,
      "Channel": 1,
      "Code": 20,
      "Value1": 0,
      "Value2": 0
    },
    {
      "Bank": 2,
      "Pedal": 2,
      "Button": 1,
      "Name": "[ B ]",
      "Event": 0,
      "Message": 176,
      "Channel": 1,
      "Code": 21,
      "Value1": 127,
      "Value2": 127
    },
    {
      "Bank": 2,
      "Pedal": 2,
      "Button": 1,
      "Name": ">   B   <",
      "Event": 1,
      "Message": 176,
      "Channel": 1,
      "Code": 21,
      "Value1": 0,
      "Value2": 0
    },
    {
      "Bank": 2,
      "Pedal": 3,
      "Button": 1,
      "Name": "[ C ]",
      "Event": 0,
      "Message": 176,
      "Channel": 1,
      "Code": 22,
      "Value1": 127,
      "Value2": 127
    },
    {
      "Bank": 2,
      "Pedal": 3,
      "Button": 1,
      "Name": ">   C   <",
      "Event": 1,
      "Message": 176,
      "Channel": 1,
      "Code": 22,
      "Value1": 0,
      "Value2": 0
    },
    {
      "Bank": 2,
      "Pedal": 4,
      "Button": 1,
      "Name": "[ D ]",
      "Event": 0,
      "Message": 176,
      "Channel": 1,
      "Code": 23,
      "Value1": 127,
      "Value2": 127
    },
    {
      "Bank": 2,
      "Pedal": 4,
      "Button": 1,
      "Name": ">   D   <",
      "Event": 1,
      "Message": 176,
      "Channel": 1,
      "Code": 23,
      "Value1": 0,
      "Value2": 0
    },
    {
      "Bank": 2,
      "Pedal": 5,
      "Button": 1,
      "Name": "[ E ]",
      "Event": 6,
      "Message": 176,
      "Channel": 1,
      "Code": 12,
      "Value1": 0,
      "Value2": 127
    },
    {
      "Bank": 2,
      "Pedal": 6,
      "Button": 1,
      "Name": "[ F ]",
      "Event": 6,
      "Message": 176,
      "Channel": 1,
      "Code": 13,
      "Value1": 0,
      "Value2": 127
    }
  ]
}

**Comment by rigr** [comment]
Thank you, so you are not parsing it for line feeds and spaces.. I'll hope to be able to play around with uploading files to my pedalino after editing them with notepad++

Thank you an best regards
Richard

**Comment by alf45tar** [comment]
The Configuration Editor has been added to Configuration page. Give a try.

**Comment by rigr** [comment]
wow, this is great! will play around asap.
Thank you a lot!


Am Sa., 27. März 2021 um 14:30 Uhr schrieb alf45tar <
***@***.***>:

**Comment by rigr** [comment]
It works great, thank you!
Please allow me to suggest you set a link to
https://github.com/alf45tar/PedalinoMini in the headerline of the
pedalino-webinterface.

Best wishes
Richard

Am Sa., 27. März 2021 um 15:05 Uhr schrieb Richard G. <
***@***.***>:
