### ISSUE TITLE
Function to move a bank

### ISSUE THREAD

**Issue by teopost** [alf45tar/PedalinoMini#205]
I created 7 banks
I have to insert a new bank between 1 and 2, but if I create a new bank it adds it at the end.
A function to move a bank would be useful !

**Comment by alf45tar** [comment]
For the moment the easy way is to save your configuration, download it and edit manually.
Then upload and apply.

**Comment by alf45tar** [comment]
Configuration file is a text file in JSON format. I suggest the following online editor http://jsoneditoronline.org/

**Comment by alf45tar** [comment]
The Configuration Editor is integrated into Configuration page. Adjust banks is not so hard.

**Comment by teopost** [comment]
Thank you
