### ISSUE TITLE
Help understanding how buttons actually work with the software.

### ISSUE THREAD

**Issue by johnpaularthur** [alf45tar/PedalinoMini#207]
I have a dumb question.   How am I supposed to get a momentary button to behave like a momentary button using CC messages.

For instance, I'm trying out Quantiloop on iOS.  It has a learn feature, but every time I try to learn  using either the single momentary switch on the KY-040 or one of the momentary switches on the ladder, Quantiloop senses latching.   

Another example would be "UNDO" for any thing.   Undo should just be momentary, there is no on or off.   But in PedalinoMini, there seem to always have to be an on or off state.  Is this right?

**Comment by alf45tar** [comment]
- Set the Pedal as Momentary 1.
- Add an event on Press **or** Release **or** Click
- Set Value From **and** To Value with the same value

**Comment by johnpaularthur** [comment]
Ok.  I tried setting From and To with same value earlier, but it caused a boot loop.   I'll try again since I've since wiped mem and reflashed.

**Comment by johnpaularthur** [comment]
I can confirm that on 2.1.0, setting the From and To value to be the same on a ladder switch will reboot the device when clicked.
![Capture](https://user-images.githubusercontent.com/7483101/112678001-68a6b280-8e38-11eb-979f-9bc4086dd59e.PNG)

**Comment by johnpaularthur** [comment]
the way I got around this was 2 separate actions: one for press (127-0) and one for release (0-127).   But this is a pain to setup for 9 buttons.
![Capture](https://user-images.githubusercontent.com/7483101/112681025-1f586200-8e3c-11eb-9edd-297e66b113a8.PNG)

**Comment by alf45tar** [comment]
Reboot when the From = To value has been fixed in version 2.1.3 or later.
I am releasing version 2.1.4 including fix for Pedals page.

**Comment by johnpaularthur** [comment]
This worked.  with the latest update.  BTW after updating to 2.1.5, the configuration imported incorrectly and shifted banks over by 1.   But the new config editor made it easy to correct.

**Comment by johnpaularthur** [comment]
Ok.   so what worked was that the pedal didn't get in a reboot loop when setting to and from to the same value.   However, the switches still aren't being recognized as momentary, unless I have separate press/release action like above.

**Comment by alf45tar** [comment]
Is not working as momentary or is it not working with quantiloop as expected?

**Comment by johnpaularthur** [comment]
Quantiloop has a learn feature.   If I use it, "momentary" switches show up at latching (it senses momentary and, latching), unless i do the work around.   The same thing happens in Ableton Live.   Actually Ableton will not recognize momentary switches from PedalinoMini, unless i also do the work around. ( Specifically the Helix native plugin).

I'm not sure what to expect which is why I ask.  Somewhat new to messing with midi in this detail.    And having trouble wrapping my head around all the options.    Technically, I see Midi OX receives a single code when set up with the to and from as the same value.    When setting up the switch with my work around, Midi OS receives two codes.   00 first and then 7F(127)

![image](https://user-images.githubusercontent.com/7483101/112786630-508f8880-901c-11eb-9e93-e92fb0b37699.png)

**Comment by alf45tar** [comment]
I cannot test Quantiloop because MIDI is not working in the free version. However according to the following video

https://www.youtube.com/watch?v=JrvJb7FGqhM&feature=emb_rel_end

Quantiloop is working with iRig Blueboard in mode 2. The good new is PedalinoMidi is iRig Blueboard compatible.
There is a ready to use configuration to emulate iRig Blueboard called 'bluebird'. Remember to switch to bank 2.

iRig Blueboard sends CC 20 value 127 on press of button A and 0 on release.
I show below the setup of the first button:

![Screenshot 2021-03-29 at 17 58 22](https://user-images.githubusercontent.com/35426671/112864786-736f7a80-90b8-11eb-9e4e-eae8c8f0edab.png)

For button B it sends CC 21 value 127 on press and 0 on release.
For button C it sends CC 22 value 127 on press and 0 on release.
For button D it sends CC 23 value 127 on press and 0 on release.

**Comment by johnpaularthur** [comment]
Gotcha.  Thanks.

**Comment by johnpaularthur** [comment]
> Gotcha. Thanks.

I think that was my confusion.   I assumed that since these are physically momentary switches and a ladder config is momentary, that a single click action would behave as momentary.   I thought that since I had to have 2 different actions (press/release) I was doing something wrong.  This is not the case then.
