### ISSUE TITLE
Sponsoring

### ISSUE THREAD

**Issue by rigr** [alf45tar/PedalinoMini#211]
Alf45tar, thanks for pedalino. I'd like to support your work but I'd prefer to donate once, because I do not always have funds on my paypal account. Would you mind to mention your paypal-account name, so I can send $$? Thanks and best wishes! RIchard

**Comment by alf45tar** [comment]
Just activated the one time sponsorship. I prefers GitHub Sponsor because there is no fee. I am receiving the 100% of your donations.
