### ISSUE TITLE
Web interface display problems.

### ISSUE THREAD

**Issue by SD456** [alf45tar/PedalinoMini#212]
Hello everyone!

I have successfully uploaded PedalinoMini to my TTGO T-Display, but the Web interface is not displayed correctly. I have tried in Chrome, Firefox, and Microsoft Edge. I have disabled the browsers extensions too, but it did not changed anything.

Thanks for the help in advance!

Images:

![webinterface_edge](https://user-images.githubusercontent.com/1049821/115107800-60402400-9f6d-11eb-8a13-c0acda254b29.jpg)
![webinterface_chrome](https://user-images.githubusercontent.com/1049821/115107803-61715100-9f6d-11eb-9872-aae523546b31.jpg)
![webinterface_firefox](https://user-images.githubusercontent.com/1049821/115107805-61715100-9f6d-11eb-9eeb-709f4e76589d.jpg)

**Comment by rigr** [comment]
I had the same "problem" and solved it in "Options" changing the
web-UI-theme.


Am Sa., 17. Apr. 2021 um 11:10 Uhr schrieb SD456 ***@***.***>:

**Comment by alf45tar** [comment]
The solution is in the session 'How to build your Pedalino' and reported here for your earlier convenience.

Click “Upload File System Image” under Platform. Do not skip this step otherwise the WebUI will not works properly.

**Comment by rigr** [comment]
It once also showed because I did not reset to defaults before starting an
upload.

Am Sa., 17. Apr. 2021 um 12:00 Uhr schrieb alf45tar <
***@***.***>:

**Comment by SD456** [comment]
> The solution is in the session 'How to build and upload' and reported here for your earlier convenience.
> 
> Click “Upload File System Image” under Platform. Do not skip this step otherwise the WebUI will not works properly.

My bad, I was not paying attention, thanks for the info!
