### ISSUE TITLE
Green box built!

### ISSUE THREAD

**Issue by gallochri** [alf45tar/PedalinoMini#214]
Hi, my first pedalino.

![2021-04-27 13 31 09](https://user-images.githubusercontent.com/404229/116234477-ef62ee00-a75c-11eb-9898-9a201d32d2ec.jpg)

**Comment by rigr** [comment]
wow, looks great! What box did you use? And maybe install some tempered glass over the TTGO.
Regards
Richard

**Comment by alf45tar** [comment]
Great job @gallochri

**Comment by alf45tar** [comment]
To simplify the enclosure build process I am working on

https://github.com/alf45tar/PedalinoMini-Case-1

**Comment by Dante777** [comment]
Hi, great box, @gallochri! Are these LEDs connected with button state? If so, could you, please, share the connection scheme?

**Comment by gallochri** [comment]
> wow, looks great! What box did you use? And maybe install some tempered glass over the TTGO.
> Regards
> Richard

https://catalog.weidmueller.com/catalog/Start.do?ObjectID=group23308260189911
I am an electrician  ;-)

**Comment by gallochri** [comment]
> Hi, great box, @gallochri! Are these LEDs connected with button state? If so, could you, please, share the connection scheme?

I used the schema in the readme file.
https://github.com/alf45tar/PedalinoMini/blob/master/images/Schematic_PedalinoMini_Sheet-2.svg

**Comment by gallochri** [comment]
Other photos...
![2021-04-27 18 23 13](https://user-images.githubusercontent.com/404229/116277549-e0446600-a785-11eb-9ca7-2ecb96117f4c.jpg)
![2021-04-27 18 23 21](https://user-images.githubusercontent.com/404229/116277564-e3d7ed00-a785-11eb-99e5-e77df0bbd130.jpg)
![2021-04-27 18 23 59](https://user-images.githubusercontent.com/404229/116277581-e76b7400-a785-11eb-93de-1398c2673f02.jpg)

**Comment by teopost** [comment]
Wow!  another picture for the github home page!

**Comment by davidin73** [comment]
> To simplify the enclosure build process I am working on
> 
> https://github.com/alf45tar/PedalinoMini-Case-1

Seems nice!!!!!

**Comment by teopost** [comment]
@gallochri, what happens if a glass of beer falls on the pedaboardl?  :-)

**Comment by gallochri** [comment]
Never drink & play ;)
