### ISSUE TITLE
Invert of Pedal Action in Analog mode

### ISSUE THREAD

**Issue by MaxZak2020** [alf45tar/PedalinoMini#216]
When my expression pedal is fully closed (down) it is 0 and when it's fully open (up) it's 127. Unfortunately there is no way to rewire pedal pot. 

Is there any opportunity to invert it by software?
Thanks for help!

**Comment by MaxZak2020** [comment]
The problem is solved by reverting of Tip and Sleeve on Connector.

**Comment by alf45tar** [comment]
It is also possible via software using Invert Polarity.
