### ISSUE TITLE
Compatibility with different addressable RGB LEDS?

### ISSUE THREAD

**Issue by MiqViq** [alf45tar/PedalinoMini#217]
Hi, thanks for a promising project!

I built a working test on a prototyping board and I am planning to build one inside a small metal casing.

Could you tell which kind of addressable RGB LEDs are compatible with PedalinoMini?

I am looking for addressable RGB LEDs that could be mounted on the footswitch top cover through holes.

Are any of these examples usable?

https://bit.ly/3vLLKhu

https://bit.ly/3ttllDJ

https://bit.ly/3tqjnnv

**Comment by alf45tar** [comment]
They can work because they are supported by FastLED https://github.com/FastLED/FastLED

> Adafruit's Neopixel - aka the WS2812B (also WS2811/WS2812/WS2813, also supported in lo-speed mode) - a 3 wire addressable led chipset

Thenks for let me know these products. I will consider to use them in https://github.com/alf45tar/PedalinoMini-Case-1
