### ISSUE TITLE
Update to pedalino-sponsors version

### ISSUE THREAD

**Issue by juani13973** [alf45tar/PedalinoMini#218]
Hi Alf45tar,
I am not an expert. I am almost there to build my prototype and I want to upgrade my DOIT ESP32 to the latest version. I have a couple of questions based on your comment: "Before any update save configuration, reset to factory default and reload configuration. EEPROM can change without any further advice."

1. After saving the config, reseting to factory default, how do I update ?
Do I need to map the your new GitHub page to Visual Studio Code, compile and upload ?

2. If I want to do OTA update ? What is the file I need to select to make this happen ? Where is it located ?

Thanks for your support,

**Comment by juani13973** [comment]
Sorry, it was easy..... :)

https://1drv.ms/u/s!An_BLYGSRFV5iMUZBbXovnMdF9FJYg?e=bdLlVL

I shared this folder, I think you can upload the new config based on my original one. It is a basic one, but I have 18 footswitches programmed.

Thanks

**Comment by juani13973** [comment]
Hi alf45tar.... I faced an error trying to do the update.
When I followed the same process to compline the sponsor version the complication failed. This is the terminal output. Would you know what I need to do ? (thank you very much for your support as always)

The error seems to be : src/OTAHTTPS.h:4:28: fatal error: HttpsOTAUpdate.h: No such file or directory

below the terminal result :

> Executing task: platformio run --environment esp32doit-devkit-v1 <

Processing esp32doit-devkit-v1 (board: esp32doit-devkit-v1; platform: espressif32; framework: arduino)
------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32doit-devkit-v1.html
PLATFORM: Espressif 32 (3.0.0) > DOIT ESP32 DEVKIT V1
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
DEBUG: Current (esp-prog) External (esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES: 
 - framework-arduinoespressif32 3.10004.210126 (1.0.4) 
 - tool-esptoolpy 1.30000.201119 (3.0.0) 
 - toolchain-xtensa32 2.50200.80 (5.2.0)
LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 42 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <AceButton> 1.8.3+sha.60beb73
|-- <ArduinoJson> 6.16.0+sha.b85181a
|-- <AsyncTCP> 1.1.1+sha.ca8ac5f
|-- <ESP Async WebServer> 1.2.3+sha.2f78426
|   |-- <AsyncTCP> 1.1.1+sha.ca8ac5f
|   |-- <FS> 1.0
|   |-- <WiFi> 1.0
|   |-- <ArduinoJson> 6.16.0+sha.b85181a
|-- <ESP8266 and ESP32 OLED driver for SSD1306 displays> 4.2.0+sha.5930c1c
|   |-- <Wire> 1.0.1
|   |-- <SPI> 1.0
|-- <FastLED> 3.4.0+sha.cfffa13
|   |-- <SPI> 1.0
|-- <MD_REncoder> 1.0.1+sha.d0c998d
|-- <NimBLE-Arduino> 1.2.0+sha.f970a1e
|-- <OSC> 0.0.0+sha.de8cf4b
|-- <ResponsiveAnalogRead> 1.2.1+sha.504c16b
|-- <TFT_eSPI> 2.3.67+sha.8164629
|   |-- <SPIFFS> 1.0
|   |   |-- <FS> 1.0
|   |-- <FS> 1.0
|   |-- <SPI> 1.0
|-- <MIDI Library> 5.0.2+sha.d9149d1
|-- <AppleMIDI> 3.1.0+sha.ae9daba
|   |-- <MIDI Library> 5.0.2+sha.d9149d1
|-- <BLE-MIDI> 2.1.0+sha.e0fb12b
|   |-- <MIDI Library> 5.0.2+sha.d9149d1
|   |-- <NimBLE-Arduino> 1.2.0+sha.f970a1e
|-- <ipMIDI> 1.0.3+sha.d131a37
|   |-- <MIDI Library> 5.0.2+sha.d9149d1
|-- <Preferences> 1.0
|-- <SPIFFS> 1.0
|   |-- <FS> 1.0
|-- <WiFi> 1.0
|-- <SPI> 1.0
|-- <Wire> 1.0.1
|-- <Ticker> 1.1
|-- <HTTPClient> 1.2
|   |-- <WiFi> 1.0
|   |-- <WiFiClientSecure> 1.0
|   |   |-- <WiFi> 1.0
|-- <WiFiClientSecure> 1.0
|   |-- <WiFi> 1.0
|-- <ArduinoOTA> 1.0
|   |-- <Update> 1.0
|   |-- <WiFi> 1.0
|   |-- <ESPmDNS> 1.0
|   |   |-- <WiFi> 1.0
|-- <ESPmDNS> 1.0
|   |-- <WiFi> 1.0
|-- <ESP32 Async UDP> 1.0.0
|-- <FS> 1.0
|-- <Update> 1.0
Building in release mode
Compiling .pio/build/esp32doit-devkit-v1/src/PedalinoMini.cpp.o
Compiling .pio/build/esp32doit-devkit-v1/libaab/AceButton/ace_button/LadderButtonConfig.cpp.o
Compiling .pio/build/esp32doit-devkit-v1/libaab/AceButton/ace_button/testing/EventTracker.cpp.o
Archiving .pio/build/esp32doit-devkit-v1/lib340/libArduinoJson.a
Indexing .pio/build/esp32doit-devkit-v1/lib340/libArduinoJson.a
Compiling .pio/build/esp32doit-devkit-v1/libcf0/AsyncTCP/AsyncTCP.cpp.o
In file included from src/PedalinoMini.cpp:68:0:
src/OTAHTTPS.h:4:28: fatal error: HttpsOTAUpdate.h: No such file or directory

************************************************************************
* Looking for HttpsOTAUpdate.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:HttpsOTAUpdate.h"
* Web  > https://platformio.org/lib/search?query=header:HttpsOTAUpdate.h
*
************************************************************************

compilation terminated.
*** [.pio/build/esp32doit-devkit-v1/src/PedalinoMini.cpp.o] Error 1
============================ [FAILED] Took 9.37 seconds ============================

Environment          Status    Duration
-------------------  --------  ------------
esp32doit-devkit-v1  FAILED    00:00:09.366
====================== 1 failed, 0 succeeded in 00:00:09.366 ======================
The terminal process "platformio 'run', '--environment', 'esp32doit-devkit-v1'" terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.

**Comment by alf45tar** [comment]
Update the ESP32 platform. I am on 3.2 with Arduino 1.0.6.


PLATFORM: Espressif 32 (3.2.0) > Espressif ESP32 Dev Module
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
DEBUG: Current (esp-prog) External (esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES: 
 - framework-arduinoespressif32 3.10006.210326 (1.0.6) 
 - tool-esptoolpy 1.30000.201119 (3.0.0) 
 - tool-mkspiffs 2.230.0 (2.30) 
 - toolchain-xtensa32 2.50200.97 (5.2.0)

**Comment by juani13973** [comment]
Hi Alf45tar, thanks for your quick reply.
I guess you mean to update the entire ESP32 platform with a new firmware ? (not buy a new one ...)
Would you have a link to do that ?
Sorry for the basic question.

**Comment by alf45tar** [comment]
It is a software update of PlatformIO

![image](https://user-images.githubusercontent.com/35426671/118030370-7d49f600-b365-11eb-966f-fa5aea8346f6.png)

**Comment by juani13973** [comment]
Hi Alf45tar, would it be possible that after reboot, the sponsor version doesn't go into AP mode ?
it goes fro smartconfig to WPS, then it shows the WIFI symbol again and the Pedalino-xxxxxx network doesn't appear in options to connect.

I am almost there.....

**Comment by alf45tar** [comment]
Did you reset to factory default?
EEPROM is changed in the latest versions.

**Comment by alf45tar** [comment]
I almost there to finish the conversion of your configuration

**Comment by juani13973** [comment]
I think I did.
I did that in the pedalino interface and I lost all my configs getting the board without connection again.
I think there is a problem with the wifi.
I used the Esptouch app and I managed to configure the wifi in my 2,4ghz guest network but it doesn't connect ....
(it it got the name of the SSDI network)

**Comment by alf45tar** [comment]
{"Globals":[{"Hostname":"pedalinomini","BootMode":3,"SSID":"Virus Infected Wifi","WiFiPassword":"tenesantivirus","SSIDsoftAP":"Pedalino-63A8CC84","PasswordSoftAP":"74y3ByAg","HTTPUsername":"juani13973","HTTPPassword":"74y3ByAg","Theme":"bootstrap","PressTime":200,"DoublePressTime":400,"LongPressTime":500,"RepeatPressTime":500,"EncoderSesitivity":5,"TapDanceMode":false,"RepeatOnBankSwitch":false,"TapDanceBank":true,"LedsOnBrightness":5,"LedsOffBrightness":1}],"Ladder":[{"Step":1,"Level":0},{"Step":2,"Level":116},{"Step":3,"Level":314},{"Step":4,"Level":487},{"Step":5,"Level":710},{"Step":6,"Level":868},{"Step":7,"Level":1023}],"Pedals":[{"Pedal":1,"AutoSensing":false,"Mode":"Ladder","PressMode":"1","InvertPolarity":false,"AnalogResponse":"Linear","Min":0,"Max":1023},{"Pedal":2,"AutoSensing":false,"Mode":"Ladder","PressMode":"1","InvertPolarity":false,"AnalogResponse":"Linear","Min":102,"Max":921},{"Pedal":3,"AutoSensing":false,"Mode":"Ladder","PressMode":"1","InvertPolarity":false,"AnalogResponse":"Linear","Min":102,"Max":921},{"Pedal":4,"AutoSensing":false,"Mode":"Analog","PressMode":"1","InvertPolarity":false,"AnalogResponse":"Linear","Min":1003,"Max":972},{"Pedal":5,"AutoSensing":false,"Mode":"None","PressMode":"None","InvertPolarity":false,"AnalogResponse":"Linear","Min":972,"Max":1023},{"Pedal":6,"AutoSensing":false,"Mode":"None","PressMode":"None","InvertPolarity":false,"AnalogResponse":"Linear","Min":972,"Max":1023},{"Pedal":7,"AutoSensing":false,"Mode":"Momentary 1","PressMode":"12L","InvertPolarity":false,"AnalogResponse":"Linear","Min":1,"Max":20}],"BankNames":[{"Bank":0,"Name":"Global"},{"Bank":1,"Name":"Ipad 1"},{"Bank":2,"Name":""},{"Bank":3,"Name":""},{"Bank":4,"Name":""},{"Bank":5,"Name":""},{"Bank":6,"Name":""},{"Bank":7,"Name":""},{"Bank":8,"Name":""},{"Bank":9,"Name":""},{"Bank":10,"Name":""},{"Bank":11,"Name":""},{"Bank":12,"Name":""},{"Bank":13,"Name":""},{"Bank":14,"Name":""},{"Bank":15,"Name":""},{"Bank":16,"Name":""},{"Bank":17,"Name":""},{"Bank":18,"Name":""},{"Bank":19,"Name":""},{"Bank":20,"Name":""}],"Actions":[{"Bank":0,"Pedal":7,"Button":1,"Led":0,"Color0":"#000000","Color1":"#000000","NameOff":"","NameOn":"","Name":"","Event":"Press","Message":"Bank+","Channel":1,"Code":1,"Value1":1,"Value2":20},{"Bank":0,"Pedal":7,"Button":1,"Led":0,"Color0":"#000000","Color1":"#000000","NameOff":"","NameOn":"","Name":"","Event":"Double Click","Message":"Bank-","Channel":1,"Code":1,"Value1":1,"Value2":20},{"Bank":1,"Pedal":1,"Button":1,"Led":1,"Color0":"#000000","Color1":"#ff00ff","NameOff":"","NameOn":"","Name":"","Event":"Press","Message":"Control Change","Channel":1,"Code":21,"Value1":0,"Value2":127},{"Bank":1,"Pedal":1,"Button":2,"Led":2,"Color0":"#000000","Color1":"#ff00ff","NameOff":"","NameOn":"","Name":"","Event":"Press","Message":"Control Change","Channel":1,"Code":22,"Value1":0,"Value2":127},{"Bank":1,"Pedal":1,"Button":3,"Led":3,"Color0":"#000000","Color1":"#ff00ff","NameOff":"","NameOn":"","Name":"","Event":"Press","Message":"Control Change","Channel":1,"Code":23,"Value1":0,"Value2":127},{"Bank":1,"Pedal":1,"Button":4,"Led":4,"Color0":"#000000","Color1":"#ff00ff","NameOff":"","NameOn":"","Name":"","Event":"Press","Message":"Control Change","Channel":1,"Code":24,"Value1":0,"Value2":127},{"Bank":1,"Pedal":1,"Button":5,"Led":5,"Color0":"#000000","Color1":"#ff00ff","NameOff":"","NameOn":"","Name":"","Event":"Press","Message":"Control Change","Channel":1,"Code":25,"Value1":0,"Value2":127},{"Bank":1,"Pedal":1,"Button":6,"Led":6,"Color0":"#000000","Color1":"#ff00ff","NameOff":"","NameOn":"","Name":"","Event":"Press","Message":"Control Change","Channel":1,"Code":26,"Value1":0,"Value2":127},{"Bank":1,"Pedal":2,"Button":1,"Led":7,"Color0":"#000000","Color1":"#DF1111","NameOff":"","NameOn":"","Name":"","Event":"Press","Message":"Control Change","Channel":1,"Code":31,"Value1":0,"Value2":127},{"Bank":1,"Pedal":2,"Button":2,"Led":8,"Color0":"#000000","Color1":"#DF1111","NameOff":"","NameOn":"","Name":"","Event":"Press","Message":"Control Change","Channel":1,"Code":32,"Value1":0,"Value2":127},{"Bank":1,"Pedal":2,"Button":3,"Led":9,"Color0":"#000000","Color1":"#DF1111","NameOff":"","NameOn":"","Name":"","Event":"Press","Message":"Control Change","Channel":1,"Code":33,"Value1":0,"Value2":127},{"Bank":1,"Pedal":2,"Button":4,"Led":10,"Color0":"#000000","Color1":"#DF1111","NameOff":"","NameOn":"","Name":"","Event":"Press","Message":"Control Change","Channel":1,"Code":34,"Value1":0,"Value2":127},{"Bank":1,"Pedal":2,"Button":5,"Led":11,"Color0":"#000000","Color1":"#DF1111","NameOff":"","NameOn":"","Name":"","Event":"Press","Message":"Control Change","Channel":1,"Code":35,"Value1":0,"Value2":127},{"Bank":1,"Pedal":2,"Button":6,"Led":12,"Color0":"#000000","Color1":"#DF1111","NameOff":"","NameOn":"","Name":"","Event":"Press","Message":"Control Change","Channel":1,"Code":36,"Value1":0,"Value2":127},{"Bank":1,"Pedal":3,"Button":1,"Led":13,"Color0":"#000000","Color1":"#00ff00","NameOff":"","NameOn":"","Name":"","Event":"Press","Message":"Control Change","Channel":1,"Code":51,"Value1":0,"Value2":127},{"Bank":1,"Pedal":3,"Button":2,"Led":14,"Color0":"#000000","Color1":"#00ff00","NameOff":"","NameOn":"","Name":"","Event":"Press","Message":"Control Change","Channel":1,"Code":52,"Value1":0,"Value2":127},{"Bank":1,"Pedal":3,"Button":3,"Led":15,"Color0":"#000000","Color1":"#00ff00","NameOff":"","NameOn":"","Name":"","Event":"Press","Message":"Control Change","Channel":1,"Code":53,"Value1":0,"Value2":127},{"Bank":1,"Pedal":3,"Button":4,"Led":16,"Color0":"#000000","Color1":"#00ff00","NameOff":"","NameOn":"","Name":"","Event":"Press","Message":"Control Change","Channel":1,"Code":54,"Value1":0,"Value2":127},{"Bank":1,"Pedal":3,"Button":5,"Led":17,"Color0":"#000000","Color1":"#00ff00","NameOff":"","NameOn":"","Name":"","Event":"Press","Message":"Control Change","Channel":1,"Code":55,"Value1":0,"Value2":127},{"Bank":1,"Pedal":3,"Button":6,"Led":18,"Color0":"#000000","Color1":"#00ff00","NameOff":"","NameOn":"","Name":"","Event":"Press","Message":"Control Change","Channel":1,"Code":56,"Value1":0,"Value2":127},{"Bank":1,"Pedal":4,"Button":1,"Led":19,"Color0":"#000000","Color1":"#000000","NameOff":"","NameOn":"","Name":"","Event":"Move","Message":"Control Change","Channel":1,"Code":41,"Value1":0,"Value2":127},{"Bank":1,"Pedal":5,"Button":1,"Led":20,"Color0":"#000000","Color1":"#000000","NameOff":"","NameOn":"","Name":"","Event":"Move","Message":"Control Change","Channel":1,"Code":61,"Value1":0,"Value2":127},{"Bank":1,"Pedal":6,"Button":1,"Led":21,"Color0":"#000000","Color1":"#000000","NameOff":"","NameOn":"","Name":"","Event":"Move","Message":"Control Change","Channel":1,"Code":71,"Value1":0,"Value2":127}],"Interfaces":[{"Interface":1,"Name":"USB MIDI   ","In":false,"Out":true,"Thru":false,"Clock":false},{"Interface":2,"Name":"Legacy MIDI","In":false,"Out":true,"Thru":false,"Clock":false},{"Interface":3,"Name":"RTP-MIDI   ","In":true,"Out":true,"Thru":false,"Clock":false},{"Interface":4,"Name":"ipMIDI     ","In":true,"Out":true,"Thru":false,"Clock":false},{"Interface":5,"Name":"BLE MIDI   ","In":true,"Out":true,"Thru":false,"Clock":false},{"Interface":6,"Name":"OSC        ","In":true,"Out":true,"Thru":false,"Clock":false}],"Sequences":[{"Sequence":1,"Step":1,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":1,"Step":2,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":1,"Step":3,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":1,"Step":4,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":1,"Step":5,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":1,"Step":6,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":1,"Step":7,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":1,"Step":8,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":1,"Step":9,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":1,"Step":10,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":2,"Step":1,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":2,"Step":2,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":2,"Step":3,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":2,"Step":4,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":2,"Step":5,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":2,"Step":6,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":2,"Step":7,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":2,"Step":8,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":2,"Step":9,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":2,"Step":10,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":3,"Step":1,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":3,"Step":2,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":3,"Step":3,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":3,"Step":4,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":3,"Step":5,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":3,"Step":6,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":3,"Step":7,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":3,"Step":8,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":3,"Step":9,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":3,"Step":10,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":4,"Step":1,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":4,"Step":2,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":4,"Step":3,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":4,"Step":4,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":4,"Step":5,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":4,"Step":6,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":4,"Step":7,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":4,"Step":8,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":4,"Step":9,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":4,"Step":10,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":5,"Step":1,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":5,"Step":2,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":5,"Step":3,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":5,"Step":4,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":5,"Step":5,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":5,"Step":6,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":5,"Step":7,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":5,"Step":8,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":5,"Step":9,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":5,"Step":10,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":6,"Step":1,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":6,"Step":2,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":6,"Step":3,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":6,"Step":4,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":6,"Step":5,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":6,"Step":6,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":6,"Step":7,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":6,"Step":8,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":6,"Step":9,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":6,"Step":10,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":7,"Step":1,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":7,"Step":2,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":7,"Step":3,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":7,"Step":4,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":7,"Step":5,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":7,"Step":6,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":7,"Step":7,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":7,"Step":8,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":7,"Step":9,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":7,"Step":10,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":8,"Step":1,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":8,"Step":2,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":8,"Step":3,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":8,"Step":4,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":8,"Step":5,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":8,"Step":6,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":8,"Step":7,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":8,"Step":8,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":8,"Step":9,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":8,"Step":10,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":9,"Step":1,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":9,"Step":2,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":9,"Step":3,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":9,"Step":4,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":9,"Step":5,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":9,"Step":6,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":9,"Step":7,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":9,"Step":8,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":9,"Step":9,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":9,"Step":10,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":10,"Step":1,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":10,"Step":2,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":10,"Step":3,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":10,"Step":4,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":10,"Step":5,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":10,"Step":6,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":10,"Step":7,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":10,"Step":8,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":10,"Step":9,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":10,"Step":10,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":11,"Step":1,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":11,"Step":2,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":11,"Step":3,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":11,"Step":4,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":11,"Step":5,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":11,"Step":6,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":11,"Step":7,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":11,"Step":8,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":11,"Step":9,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":11,"Step":10,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":12,"Step":1,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":12,"Step":2,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":12,"Step":3,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":12,"Step":4,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":12,"Step":5,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":12,"Step":6,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":12,"Step":7,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":12,"Step":8,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":12,"Step":9,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":12,"Step":10,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":13,"Step":1,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":13,"Step":2,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":13,"Step":3,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":13,"Step":4,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":13,"Step":5,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":13,"Step":6,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":13,"Step":7,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":13,"Step":8,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":13,"Step":9,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":13,"Step":10,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":14,"Step":1,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":14,"Step":2,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":14,"Step":3,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":14,"Step":4,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":14,"Step":5,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":14,"Step":6,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":14,"Step":7,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":14,"Step":8,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":14,"Step":9,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":14,"Step":10,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":15,"Step":1,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":15,"Step":2,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":15,"Step":3,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":15,"Step":4,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":15,"Step":5,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":15,"Step":6,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":15,"Step":7,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":15,"Step":8,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":15,"Step":9,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":15,"Step":10,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":16,"Step":1,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":16,"Step":2,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":16,"Step":3,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":16,"Step":4,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":16,"Step":5,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":16,"Step":6,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":16,"Step":7,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":16,"Step":8,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":16,"Step":9,"Message":0,"Channel":1,"Code":0,"Value":0},{"Sequence":16,"Step":10,"Message":0,"Channel":1,"Code":0,"Value":0}]}

**Comment by alf45tar** [comment]
Above your converted configuration

**Comment by juani13973** [comment]
Thx alf45tar... I will try to upload it when I manage to get this working.
Can I use the clean command and try to upload the esp32doit-devkit-v1 ? this is what is going on ....

Uploading IMG_7665.mp4…

**Comment by juani13973** [comment]
Hi alf45tar.
now it works. I do not know what I did wrong before.
This is my prototype. waiting for box to come from China to mount it..... I will share later the PCBs and Fusion 360 content....

![IMG_7662](https://user-images.githubusercontent.com/77895272/118041525-3400a300-b373-11eb-8d1d-a9fdc4982e11.JPG)

**Comment by Dante777** [comment]
Hi alf45tar,
Could you explain, please, could calibration be performed for each Ladder-type pedal separately? In case that resistors used in ladder have slightly different values?

**Comment by alf45tar** [comment]
@Dante777
It is not possible. All ladders must be the same.

**Comment by Dante777** [comment]
Thanks, I thought as much.

**Comment by mike76700** [comment]
juani13973 , 
the onedrive link for your 18 footswitches configuration don't work , can you resend me a link for this ?  
thanks a lot

**Comment by juani13973** [comment]
Hi Mike, I only uploaded an old configuration of the footswitch that alf45tar helped me to re format to the new compatible version that is needed.
there is nothing else there... (that is why I turned it off)
