### ISSUE TITLE
I am using B10k pot and I see a lot of jumping around in the output 

### ISSUE THREAD

**Issue by peeyush-shippo** [alf45tar/PedalinoMini#219]
Hi I am using a B10K pot hooked upto A2,D2. Its working except I don't see full range and output is not stable I see a lot of jumping around. I am using auto calibration. The schematic I saw here was using Yamaha which has 50K pot. would you recommend trying a 50k pot?

**Comment by alf45tar** [comment]
DId you connected the GND? Did you solder the pot or used a breadboard? Breadboard loose connection can be the reason.
10k or 50k are ok both.

**Comment by akosbeke** [comment]
Are you using power from your computer or a dedicated power supply? Jumping like this can happen due to the lack of stable power.

**Comment by peeyush-shippo** [comment]
I am using power from my computer. let me try using dedicated power supply.
