### ISSUE TITLE
OTA Update for firmware compiled for SSH1106WIRE display

### ISSUE THREAD

**Issue by teopost** [alf45tar/PedalinoMini#222]
After the OTA update my display is not working properly.
The display of my Pedalinomini is SSH1106WIRE.
The version I am using was previously compiled by me modified the file platformio.ini

**Comment by teopost** [comment]
ADDENDUM:
II reloaded the previous firmware 2.2.1, but now the WEB UI is like this

![image](https://user-images.githubusercontent.com/2573389/118392212-b4a3f580-b638-11eb-8923-67274f0770c0.png)

**Comment by alf45tar** [comment]
Version 2.2.2 include a new Bootstrap version. The corresponding System Image must be uploaded.

**Comment by alf45tar** [comment]
I suggest to apply the same changes you did to platform.ini to the new version 2.2.2.

**Comment by teopost** [comment]
can I do it via OTA?

**Comment by alf45tar** [comment]
Yes, you can. Compile using platformio ide, goto .pio/building looking for firmare.bin and spifferi.bin file, upload them connecting to http://<pedalino ip or name>.local/update

**Comment by teopost** [comment]
Thanks you. It's works
