### ISSUE TITLE
Defective esp32 board?

### ISSUE THREAD

**Issue by davidin73** [alf45tar/PedalinoMini#224]
Hello
After various attempts to send midi commands to my Helix', and various controls, i think my esp32 board is defective in the midi out section.
How can I verify if is it?
Thanks in advice

**Comment by alf45tar** [comment]
There is no midi out session in the esp32. It is just a serial interface. 
Which midi out schematic did you used? Did you add the led? Is it blinking?

**Comment by davidin73** [comment]
Hello.
No ,without led....i can modify it this morning to add the led.
I have used the standard schematic ....

**Comment by davidin73** [comment]
Done the LED's add....
Is flashing on pushbutton

**Comment by alf45tar** [comment]
It is a good news. Are you sure of connection? Try to invert pin 4 and 5 on MIDI connector. It is not dangerous because there is a diode in every MIDI IN port to protect against pin inversion.

**Comment by davidin73** [comment]
Hm....i think I have failed the resistences values on the midi port and the +5v midi connector...🤦🏻‍♂️
I have re measured, and aren't 220 ohms,but around 190 ohms....
the sight begins to play tricks on me ... 😞i try to replace them, and later i post you the result...
Thanks for your patience

**Comment by davidin73** [comment]
Solved
Effectively was the two cables inverted in the midi connector
Thanks for your patience!!!!
