### ISSUE TITLE
Buttons 7 and 8 on real buttons

### ISSUE THREAD

**Issue by davidin73** [alf45tar/PedalinoMini#225]
Hi!
Just for information
There's some maner to phisically connect the 7 and 8 buttons on some external button?
Thanks

**Comment by alf45tar** [comment]
It is not so easy. GPIO_0 and GPIO_35 are not available as external board pins.
You could sold an external button in parallel to existing board switches but I do not recommend it.

**Comment by davidin73** [comment]
Okay, thank you for your answer
