### ISSUE TITLE
Controlling Zoom Pedals ?

### ISSUE THREAD

**Issue by quangvankts** [alf45tar/PedalinoMini#23]
What is the easiest way to make Pedalino Mini work with Zoom pedals, which seems to require USB Host ?
Thanks

**Comment by underwoodblog** [comment]
If the Zoom pedals are Class Compliant search for MIDI USB Host. That "converts" your Class Compliant USB Device to normal MIDI.

**Comment by alf45tar** [comment]
PedalinoMini is a USB device, not an USB host.
USB host feature requires additional hardware.

**Comment by quangvankts** [comment]
If USB Host Shield hardware is added, is Arduino Pro Micro still needed ?

**Comment by alf45tar** [comment]
No, it isn't.

According to https://github.com/felis/USB_Host_Shield_2.0#boards, ESP32 can be connected directly using GPIO5 : SS, GPIO17 : INT, GPIO18 : SCK, GPIO19 : MISO, GPIO23 : MOSI.
