### ISSUE TITLE
[Enhancement] Midi Value Tracker

### ISSUE THREAD

**Issue by TarFilarek** [alf45tar/PedalinoMini#237]
Hello!

A small enhancement idea came to my mind.

**MIDI VALUE Tracker**

![131382397_242344857227704_5074943177736721114_n](https://user-images.githubusercontent.com/64553282/122012234-3c5a5c80-cdbd-11eb-8ed7-2c01e689b24d.jpg)

_When the **VALUE** cell is left blank*, the pedal will use the last sent **VALUE**.
*it could also be a letter, eq. **T** from **TRACK** or **C** from **COPY**_

It could be used to quickly and precisely change **MIDI VALUE** sent by **ANALOG PEDAL** (potentiometer/expression pedal). It would allow control of multiple digital pedals/knobs/sliders with only one press and move of the Expression Pedal.

Right now it can be done with **BANK+**/**BANK-** (each bank with a different **MIDI VALUE** for the same **PEDAL**), but it's much less clear and comfortable.

**Comment by alf45tar** [comment]
Thanks @TarFilarek for the suggestion.

I implemented the universal expression pedal in a different way. 

1. Leave empty the Send field of an analog pedal.
2. It will control the last Control Code, Note On, Note Off, Pitch Bend and Channel Pressure send by one on any other pedals.

Let me know if it meets your expectations.

**Comment by TarFilarek** [comment]
Hi!

Sorry for writing back so late. My controller was disassembled, and I couldn't check it until today.

It works absolutely brilliant! Thank You!

**Comment by alf45tar** [comment]
Thanks to you @TarFilarek for your contribution
