### ISSUE TITLE
Pin A3 on TTGO-T-Eight

### ISSUE THREAD

**Issue by Hans68** [alf45tar/PedalinoMini#24]
As GPIO34 is used for Battery indication on TTGO-T-Eight, where to connect Pin A3 ? 
Is there generally a different usage of GPIO Pins with TTGO ?
Cheers

**Comment by alf45tar** [comment]
Pins are limited and there is no more pin for battery.
I used it for testing. The real usage of A3 is for pedal 3.

**Comment by Hans68** [comment]
Thanks
