### ISSUE TITLE
12-button plywood build with modded expression pedal

### ISSUE THREAD

**Issue by akosbeke** [alf45tar/PedalinoMini#240]
Hi there,

I realized that I haven't really shared my final PedalinoMini build that I finished in January this year.

So here's a couple of details:

- it has 12 buttons (using two 6-button ladder)
- diffused LED indicators
- USB-C port
- ON/OFF switch
- 3 routed 6.3 jacks for extra controllers
- hardware MIDI ports
- the case is made of 3mm plywood so it's super lightweight but also sturdy the way I designed it

I also modded a cheap M-Audio EX-P expression pedal so it has a toe-switch. The pedal this way has two 6.3 jack plugs: one for the expression pedal and one for the toe-switch. It works absolutely amazingly.

A few photos:

![IMG_1665](https://user-images.githubusercontent.com/7037649/124348379-e4f42300-dbe9-11eb-90aa-9a2cc2da19a1.jpg)

![IMG_1660](https://user-images.githubusercontent.com/7037649/124348385-f5a49900-dbe9-11eb-9364-621853f99144.jpg)

![IMG_1662](https://user-images.githubusercontent.com/7037649/124348439-3c928e80-dbea-11eb-80af-3e551435cdb7.jpg)

![IMG_1664](https://user-images.githubusercontent.com/7037649/124348449-43210600-dbea-11eb-82c8-90f1ea752234.jpg)

![IMG_1659](https://user-images.githubusercontent.com/7037649/124348454-45836000-dbea-11eb-9ea7-13d66c1428a8.jpg)

**Comment by jwyse** [comment]
This looks awesome. Can we see photos of the inside, and the box design?

**Comment by akosbeke** [comment]
Yeah, sure.

I have these photos that were taken before I wired up the DIN sockets, so you won't see those, but other than that this is how it's constructed.

The USB-C part kinda looks horrible but I had these adapters laying around and they work. 😆 

The other interesting thing is that I had to put a mosfet before each button because they were extremely noisy. I'm pretty sure it's not the cheapest solution but I'm a software engineer not an electrical engineer and they got the job done.

I made a 3D model for the enclosure but I managed to lost it when I upgraded to a new mac...

![IMG_1687](https://user-images.githubusercontent.com/7037649/124358038-bc3a5080-dc1e-11eb-8635-ed589f3579b5.jpg)

![IMG_1688](https://user-images.githubusercontent.com/7037649/124358047-c4928b80-dc1e-11eb-8d39-3233318af19a.jpg)

**Comment by akosbeke** [comment]
Thankfully I was wrong. I did find the 3D model.

I designed it in blender. Although I have to mention that I had to do a few tweaks here and there like chamfering the vertical posts so it won't interfere with the switches, or some holes on the back for the USB-C port, the ON/OFF switch, etc.

https://drive.google.com/file/d/1gljxhFCWMeqbo-k4A6Z_3AIgbYPNIpn8/view?usp=sharing

**Comment by jwyse** [comment]
Awesome, thanks for sharing those!

**Comment by DWSQUIRES** [comment]
Very cool build. Did you use got glue to diffuse the LEDs?

**Comment by akosbeke** [comment]
Yep, that's what I did. I was going to frost an acrylic sheet first but then I realized that it's too meticulous and it's impossible to make a precise cut without a laser cutter which I do not have.

But after some tests it turned out that the good old-fashioned hot glue works just as well.
