### ISSUE TITLE
How can I move a bank?

### ISSUE THREAD

**Issue by teopost** [alf45tar/PedalinoMini#244]
I would like to switch 2 banks

![image](https://user-images.githubusercontent.com/2573389/126040571-47fc2a2e-24b8-41c6-a5af-ef4ca9fc7b7a.png)

I tried to do this using the configuration editor, but the changes are not applied

**Comment by alf45tar** [comment]
Did you saved changes using Save on the right of configuration editor?
Did you loaded the configuration?

**Comment by teopost** [comment]
Yes. the configuration is saved. the json is modified but is not applied

**Comment by alf45tar** [comment]
Did you changed the bank number in the Actions root of both banks?

**Comment by teopost** [comment]
I didn't! Now I have succeeded
I suggest adding a more user friendly feature as it is very inconvenient to change the settings in this way.
Thanks for the support

**Comment by alf45tar** [comment]
It is absolutely true.

**Comment by alf45tar** [comment]
Bank order re-arrangment using drag & drop will be released with version 2.2.8.

**Comment by teopost** [comment]
Wow! Fantastic

**Comment by teopost** [comment]
How does it work?
Where should I drag & drop?

**Comment by teopost** [comment]
Tested. It work.
Much appreciated modification
Thank you

**Comment by teopost** [comment]
Ops! I found a problem!
The change is not saved

**Comment by alf45tar** [comment]
Drag & drop the bank number/name.
Click on any bank to save the order into memory
Click on Save button to save into EEPROM

**Comment by teopost** [comment]
It works. 
This implementation is very useful
Thank you
