### ISSUE TITLE
I want connect 12 footswitch and 1 wah pedal, but I don't understand schematic and setup via web.

### ISSUE THREAD

**Issue by e36910** [alf45tar/PedalinoMini#247]
I can setup only 6 footswitch using pin 13, 12, 14, 27, 26, 25. But I don't understand how to use for exemple only pin 13 with 6 footswitch and pin 12 with 6 footswitch to get a total of 12 pedals and using pin 14 to get wah pedal. I want using photoresistor as wah pedal. How to connecting and setup this? Thank you.

**Comment by alf45tar** [comment]
Ladder pedal mode requires 2 pins: one digital and one analog.

**Comment by e36910** [comment]
![pedal3](https://user-images.githubusercontent.com/85799952/126941096-5deb2e92-6fc9-45a2-8807-8d4b657a86a8.jpg)
Is it correct settings?

**Comment by alf45tar** [comment]
If Pedal 1 is configured as Ladder use the Button value in every action to distinguish the 6 footswitches and assign separate actions.

**Comment by e36910** [comment]
Do you have exaple sutup pedal 1 via web interface?

**Comment by alf45tar** [comment]
![Screenshot 2021-07-26 at 08 30 06](https://user-images.githubusercontent.com/35426671/126943285-4d244962-ffb1-4e16-8177-6fc89ceb533a.png)
![Screenshot 2021-07-26 at 08 31 47](https://user-images.githubusercontent.com/35426671/126943294-c9baa0b6-f630-4662-84ee-c67fdb6db1a9.png)

**Comment by e36910** [comment]
![IMG_20210726_140012](https://user-images.githubusercontent.com/85799952/126978756-4bc6bca4-2594-4659-ae48-a44e43f4b8be.jpg)
I use this schematic with R10. Working only 5 buttons. Schematic on the project doesn't work.

**Comment by alf45tar** [comment]
Did you calibrated you ladder as indicated in the instructions?

**Comment by e36910** [comment]
No, because I haven`t display. My pedal will be without display.

**Comment by alf45tar** [comment]
Without a display you need to calculate the ladder levels and enter into the Options
![Screenshot 2021-07-26 at 13 29 07](https://user-images.githubusercontent.com/35426671/126981913-1ab504fd-a467-4151-af29-c3e87c0b9818.png)

Did you do the math?
