### ISSUE TITLE
Actions removed from WebUI changing profile

### ISSUE THREAD

**Issue by teopost** [alf45tar/PedalinoMini#249]
Hi,
  when I change my profile from webui, actions sometimes disappear.
Unfortunately in some cases I have lost the bank data (I have not yet understood when this happens)

Maybe this video can help

https://youtu.be/6fveHXz25f4

from second 47 to the end

PS: This video  has temporarily uploaded to youtube but will be removed

**Comment by alf45tar** [comment]
I noted the bug some days ago. I am fixing it.

**Comment by alf45tar** [comment]
Fixed in sponsor version.
