### ISSUE TITLE
I became a sponsor and received a link to a private repository, but there is version 2.2.1 and publicly available 2.2.2

### ISSUE THREAD

**Issue by e36910** [alf45tar/PedalinoMini#252]
Are there instructions on how to install the sponsored version, what are the differences from the public one?

**Comment by alf45tar** [comment]
The instructions are the same for the public version except the GitHub repository to clone is https://github.com/pedalino-sponsors/PedalinoMini

The current sponsor version is [2.2.7](
https://github.com/pedalino-sponsors/PedalinoMini/blob/3df1407c4b7b8d17cf8060bca7a95b8962238ea3/src/Pedalino.h#L17)
