### ISSUE TITLE
Doesn't work "New Action"

### ISSUE THREAD

**Issue by e36910** [alf45tar/PedalinoMini#253]
Do you have video or other manual how setup 36 CC button?

**Comment by e36910** [comment]
![pedal](https://user-images.githubusercontent.com/85799952/126892279-75b6438c-6be9-4e8f-b346-63087aa8720d.jpg)

**Comment by alf45tar** [comment]
Did you “Upload File System Image” under Platform?
Do not skip this step otherwise the WebUI will not works properly.

**Comment by e36910** [comment]
![pedal2](https://user-images.githubusercontent.com/85799952/126896451-7efc7687-4f98-4f97-b65a-1161bda090fd.jpg)
How is it doing?

**Comment by alf45tar** [comment]
![Screenshot 2021-07-25 at 13 07 58](https://user-images.githubusercontent.com/35426671/126896927-d79a8784-d323-4c57-9350-61ed38ca374d.png)

**Comment by e36910** [comment]
How to setup 36 footswitch CC control? Web interface has only 7 pedal. Do you have example setup?

**Comment by alf45tar** [comment]
Use the first 6 and configure as Ladder.
