### ISSUE TITLE
How to  bluetooth connect via bias fx2 in windows10?

### ISSUE THREAD

**Issue by e36910** [alf45tar/PedalinoMini#254]
Interesting driver for windows for connection bluetooth pedal with bias fx2 and other vst plugin. Do you have manual?

**Comment by alf45tar** [comment]
https://www.youtube.com/watch?v=bfV4szNlFWM
https://www.youtube.com/watch?v=gYCDurXL1Qw

**Comment by e36910** [comment]
Is it possible to use Wi-Fi instead of Bluetooth to transfer midi signal to Windows and ios?

**Comment by alf45tar** [comment]
Yes, it is.
For iOS use https://apps.apple.com/us/app/midi-network/id1102428729
For Windows you need https://www.tobias-erichsen.de/software/rtpmidi.html

**Comment by e36910** [comment]
![midi](https://user-images.githubusercontent.com/85799952/127306939-cc0acd93-a6e6-4800-b35f-5db948748d30.jpg)
It doesn't work

**Comment by alf45tar** [comment]
Did you connected your Windows machine to the PedalinoMini hotspot?

**Comment by e36910** [comment]
Yes

**Comment by e36910** [comment]
Midibery  doesn't work to

**Comment by alf45tar** [comment]
I replicated the issue with macOS too. It is happing when Pedalino is used as access point.
As a temporary workaround connect PedalinoMini and you PC to an access point.

**Comment by e36910** [comment]
Can it be possible to connect it through bluetooth somehow? Midibery doesn't work

**Comment by alf45tar** [comment]
Network MIDI/AppleMIDI/RTP MIDI fixed in the latest sponsor version

**Comment by e36910** [comment]
Will the bluetooth connection work with Windows 10?
MIDI/AppleMIDI/RTP MIDI is working. Thank you!

**Comment by alf45tar** [comment]
Bluetooth MIDI works for me.

The procedure is:
1. Pair PedalinoMini as any Bluetooth device in Windows 10
2. Run MIDIberry and select PedalinoMini device name in the INPUT list

If you need a MIDI port:
1. Create a MIDI port with loopMIDI
2. Select the MIDI port in the OUTPUT of MIDIberry

**Comment by e36910** [comment]
I have Windows ltsc, bluetooth connection via midiberry doesn't work. I did everything according to the instructions.

**Comment by alf45tar** [comment]
I do not know Windows LTSC and I do not support it because it is not for this kind of application.
