### ISSUE TITLE
How to remove the frame around the bank name

### ISSUE THREAD

**Issue by teopost** [alf45tar/PedalinoMini#255]
Hi,
  Is there a way to remove the frame around the bank name?
A compile parameter would be fine too

**Comment by alf45tar** [comment]
If you don't like the frame (me too) delete or comment the following lines

https://github.com/alf45tar/PedalinoMini/blob/95adcf452d1a4d9d8d7f1c82f5dc2924e6513c48/src/DisplayOLED.h#L939

https://github.com/alf45tar/PedalinoMini/blob/95adcf452d1a4d9d8d7f1c82f5dc2924e6513c48/src/DisplayTFT.h#L1076
