### ISSUE TITLE
Can I connect my iPhone via wifi midi?

### ISSUE THREAD

**Issue by e36910** [alf45tar/PedalinoMini#258]
What program is needed to connect iPhone via wifi for midi control?  Which connection has less wifi or bluetooth latency?

**Comment by alf45tar** [comment]
https://apps.apple.com/us/app/midi-network/id1102428729

Bluetooth should have low latency due to point-to-point connection but I do not have any exact measure.

**Comment by teopost** [comment]
what is it for? what can you do with the iphone?

**Comment by alf45tar** [comment]
For example you can control Amplitube installed on any iOS device.

**Comment by e36910** [comment]
> what is it for? what can you do with the iphone?

I am using an iPhone instead of a guitar processor. I just install jailbreak and use bias fx2 crack version 👍
