### ISSUE TITLE
Different calibration settings Resistor Ladder Network with battery(pin 3,3v and gnd) or  usb.

### ISSUE THREAD

**Issue by e36910** [alf45tar/PedalinoMini#261]
When I use USB it has 350,500,650,725,780,850,1023
When I use battery 3.7v connecting via pin 3,3v and gnd it has 350,500,750,900,950,1000,1023
Is it bug?

**Comment by alf45tar** [comment]
A 3.7V battery cannot be connected to 3.3 pin to power the board.
When fully charged a Li battery can reach 4.2V.

**Comment by e36910** [comment]
Do I need to plug it into the connector VIN?

**Comment by alf45tar** [comment]
https://techexplorations.com/guides/esp32/begin/power/
