### ISSUE TITLE
How to connection led 2 pin neer knob? 

### ISSUE THREAD

**Issue by e36910** [alf45tar/PedalinoMini#262]
I have 12 buttons via ledder connection and I would like an ice indicator to work next to each button, how can I implement this option?

**Comment by e36910** [comment]
How to connect 6 leds?

**Comment by alf45tar** [comment]
![Screenshot 2021-09-06 at 08 51 55](https://user-images.githubusercontent.com/35426671/132173053-0ff26c4d-ef80-4219-ac0d-e7abe1e9e45f.png)

**Comment by e36910** [comment]
What about Data? Is it pin D25 for Pedal 1 ?

**Comment by e36910** [comment]
If I understand 5v connect to VIN pic. Is it correct?

**Comment by alf45tar** [comment]
Yes, it is.
