### ISSUE TITLE
How to connect a distance sensor as a pedal wah?

### ISSUE THREAD

**Issue by e36910** [alf45tar/PedalinoMini#264]
I have such a distance sensor and I would like to use it as a pedal wah.  Is it possible to connect it?  Is there a wiring diagram for the contacts of this sensor?
https://a.aliexpress.com/_An8FSA
![-934876035-499342221](https://user-images.githubusercontent.com/85799952/132117538-7e1d67e1-f145-4c47-abb6-cdd7ed170d40.jpg)

**Comment by alf45tar** [comment]
The sensor is not supported yet. It requires software changes too.

**Comment by renne** [comment]
@alf45tar 
The driver can be adopted from [Tasmota](https://tasmota.github.io/docs/HC-SR04/).

Padding your foot on a 2 cm hole for wah/tremolo would be funny. ;-)

**Comment by e36910** [comment]
https://youtu.be/mWa1He9FP5U

**Comment by e36910** [comment]
https://youtu.be/wWkQJ3UaHrQ

**Comment by alf45tar** [comment]
@e36910 stay tuned. I will release ultrasonic sensor support soon.

**Comment by alf45tar** [comment]
@e36910 just released
