### ISSUE TITLE
Question about ladder config.

### ISSUE THREAD

**Issue by NeidalMcCanuk** [alf45tar/PedalinoMini#266]
Hello, good night.

I have a question anput the use of "Voltage ladder". Everytime I turn on the PedalinoMini, must I configure again selecting the "Ladder config" mode? Or it stores forever the calibration?

Thanks alf45tar!

**Comment by alf45tar** [comment]
Ladder config is saved into the EEPROM forever. Not exactly forever but until you redo a calibration or change values via web UI.
