### ISSUE TITLE
How do I transfer my settings from one board to another?

### ISSUE THREAD

**Issue by e36910** [alf45tar/PedalinoMini#271]
I would like to save my settings from one board and transfer them to another. How can you do this correctly?
I do everything as in the picture, but nothing works.
![конфиг](https://user-images.githubusercontent.com/85799952/134684213-1fcb8b11-ff89-44f4-b02c-ee943a575efb.jpg)

**Comment by alf45tar** [comment]
On source board

1. Save the current configuration with a anme using New button
2. Select the just saved configuration from Available Configurations and click Download button

On destination board

1. Click on Choose file under Upload Configuration
2. Select the file you just downloaded from source board and click Upload
3. Select the configuration just uploaded from Available Configuration and press Apply or Apply & Save
4.

**Comment by e36910** [comment]
I did so, but nothing worked.

**Comment by alf45tar** [comment]
I need more information about error or at least the log to serial port.
