### ISSUE TITLE
Doesn't connect to local address for configuration via usb

### ISSUE THREAD

**Issue by e36910** [alf45tar/PedalinoMini#272]
Wifi stopped working on my board. Can I configure my device via usb without using wifi?

**Comment by alf45tar** [comment]
Reset to factory default and restart the procedure to connect wifi

**Comment by e36910** [comment]
The board initially has connection problems via wifi. This is a hardware problem in the board, wifi is not working. is it possible to enter the web interface using only usb?

**Comment by e36910** [comment]
![bug](https://user-images.githubusercontent.com/85799952/134784475-1a94ce13-6910-4cb2-b71c-91322bbfd852.jpg)

**Comment by alf45tar** [comment]
No, it is not possible.
