### ISSUE TITLE
Led setup doesn't work

### ISSUE THREAD

**Issue by e36910** [alf45tar/PedalinoMini#274]
I soldered and connected the led according to the diagram, but they don't work. How to set them up correctly?
My setup on screen, connect on video.
![led setup](https://user-images.githubusercontent.com/85799952/135073171-741c6bbe-8b5a-46ad-8d5a-a873de50f59b.jpg)
https://youtu.be/YQTpcHifErA

**Comment by alf45tar** [comment]
Did you connected led strip DATA to D5?
It the video is connected to D25.

**Comment by e36910** [comment]
When I connected to d5, only the first green LED turns on when I press any button and then no reaction, it continues to shine.
