### ISSUE TITLE
Unable to sponsor

### ISSUE THREAD

**Issue by wybbbb** [alf45tar/PedalinoMini#276]
I’m from China, and I can’t pay with credit card or paypal. The following message will pop up when I click to pay
Your account is currently locked from purchases. Please update your payment information.

**Comment by alf45tar** [comment]
I saw you solved the issue

**Comment by wybbbb** [comment]
> 我看到你解决了这个问题
If you haven’t solved it, you have been unable to pay. No matter if you use a credit card or a paypal account, it will always be displayed when you pay“Your account is currently locked from purchases. Please update your payment information.”
