### ISSUE TITLE
pedal 1 button 2 not working

### ISSUE THREAD

**Issue by prostealth** [alf45tar/PedalinoMini#277]
i just uploaded public build on esp32 doit devkit v1
the button 2 on pedal not working
here is the log
Loading profile ...
Reading NVS Profile A ... done
Bank  2
Pedal  1     1   MOMENTARY2   PRESS_1       POLARITY+   CONTROL_CHANGE      80   Channel  1   Pin D25   Pin A36
Pedal  2     1   MOMENTARY2   PRESS_1       POLARITY+   CONTROL_CHANGE      82   Channel  1   Pin D26   Pin A39      
Pedal  3     1   MOMENTARY2   PRESS_1       POLARITY+   CONTROL_CHANGE      76   Channel  1   Pin D27   Pin A34
Pedal  4     1   MOMENTARY2   PRESS_1       POLARITY+   CONTROL_CHANGE      78   Channel  1   Pin D14   Pin A35
Pedal  5     1   MOMENTARY1   PRESS_1       POLARITY+      Channel  0   Pin D12
Pedal  6     1   MOMENTARY1   PRESS_1       POLARITY+      Channel  0   Pin D13
Pedal  7     12L   MOMENTARY1   PRESS_1_2_L   POLARITY+      Channel  0   Pin D0
MTC None
Pedal: 1     Button: 1    EventType: 0     ButtonState: 0
Action:
CONTROL CHANGE.....Code  80......Value 127.....Channel  1
Pedal: 1     Button: 1    EventType: 1     ButtonState: 1
Action:
CONTROL CHANGE.....Code  80......Value   0.....Channel  1
Pedal: 1     Button: 1    EventType: 2     ButtonState: 1
SYSTEM_EVENT_AP_STACONNECTED
dhcps: send_nak>>udp_sendto result 0
Event: 18
AppleMIDI Connected Session ID: 25404865 Name: Hansa-PC
Pedal: 1     Button: 1    EventType: 0     ButtonState: 0
Action:
CONTROL CHANGE.....Code  80......Value 127.....Channel  1
Pedal: 1     Button: 1    EventType: 1     ButtonState: 1
Action:
CONTROL CHANGE.....Code  80......Value   0.....Channel  1
Pedal: 1     Button: 1    EventType: 2     ButtonState: 1

the switch is ok when im checking using multimeter
i try to upload on another board but the problem still persist.

**Comment by alf45tar** [comment]
Did you connected button 2 to pin 39?

**Comment by prostealth** [comment]
i connect it to vp pin..
i dont know where is pin 39.

**Comment by prostealth** [comment]
why battery and A1 have same pin?
is it okay?
![IMG_20211003_112626.jpg](https://user-images.githubusercontent.com/39737044/135739872-026f9db5-d93b-40ba-845d-5254200da6b3.jpg)

**Comment by prostealth** [comment]
A2 to A4 are working well.
i didnt test A5 and A6 since they're  TRS jacks.
only button 2 / A1 that doesnt work

**Comment by alf45tar** [comment]
Sorry I was wrong. A1 is pin 36 or VP.
There is not enough pin for battery on some board. I think you identified the issue. I suggest to delete or comment the following line

https://github.com/alf45tar/PedalinoMini/blob/93ae329235076b2dc7be8abaa3794b6e8d870a12/platformio.ini#L11

or assign BATTERY_PIN to an unused pin.

**Comment by prostealth** [comment]
yes.. now all is well..
