### ISSUE TITLE
Learn mode for ladder pedal. How to enter calibration mode?

### ISSUE THREAD

**Issue by e36910** [alf45tar/PedalinoMini#278]
I read the instructions, but it does not say how to get into the calibration mode. When I doing in normal mode it doesn't work.
How do I enter calibration mode for ladder calibration?

**Comment by alf45tar** [comment]
Booting mode 7

https://github.com/alf45tar/PedalinoMini#booting-modes

**Comment by e36910** [comment]
Don't understand. I read your manual. I need calibration mode.

**Comment by e36910** [comment]
Maybe press button "boot" on the board?

**Comment by alf45tar** [comment]
Yes, reboot your board and keep the BOOT button pressed until Ladder Config appear on display. Release the BOOT button an follow the instruction.

**Comment by e36910** [comment]
I think you need to write this manual into the settings plate.

**Comment by e36910** [comment]
Thank you
