### ISSUE TITLE
What is the latest sponsor version number?

### ISSUE THREAD

**Issue by bobvc133** [alf45tar/PedalinoMini#279]
What is the latest sponsor version number?

**Comment by alf45tar** [comment]
It should be the same of the public version. As off today there is no difference.

**Comment by bobvc133** [comment]
> 它应该与公共版本相同。今天休息没有什么区别。

**Comment by bobvc133** [comment]
> 它应该与公共版本相同。今天休息没有什么区别。



> It should be the same of the public version. As off today there is no difference.
