### ISSUE TITLE
How to modify the Web UI display language

### ISSUE THREAD

**Issue by bobvc133** [alf45tar/PedalinoMini#282]
How to modify the display language of the Web UI and which file to modify? It is inconvenient to use the browser translation plug-in to translate the page every time.

**Comment by bobvc133** [comment]
> The web user interface is embedded into https://github.com/alf45tar/PedalinoMini/blob/master/src/WebConfigAsync.h

After I modified it, there were many unknown problems, and many codes were related. For example, the user configuration file could not be restored. How can I modify it to avoid these problems? Or set it as a language pack, so that users in many different languages can help translate, I can provide Chinese translation

**Comment by alf45tar** [comment]
Translation should modify only the frontend. Did you touched also the backend?

**Comment by bobvc133** [comment]
> Translation should modify only the frontend. Did you touched also the backend?

I basically don't know the back end, but I can provide Chinese translation for the words, if
PedalinoMini can support multi-language packages, so it will be welcomed by more language users
