### ISSUE TITLE
MIDI LED display problem

### ISSUE THREAD

**Issue by bobvc133** [alf45tar/PedalinoMini#285]
In the Legacy MIDI part I built according to the circuit diagram, the MIDI OUT LED will flash when the button is clicked to output the signal. It should be correct, but the MIDI IN LED will always light up after the device is turned on. Is this normal?
![QQ截图20211027112813](https://user-images.githubusercontent.com/91867813/138995278-c853f679-5879-427d-accd-421c3e93bdad.jpg)
![P11027-111828](https://user-images.githubusercontent.com/91867813/138995283-a56816ee-305b-413a-8bf8-50ee088c0d48.jpg)

**Comment by alf45tar** [comment]
The difference of 1.5 V is the reason of led on.
Just a question. Is the MIDI IN working?

**Comment by bobvc133** [comment]
> The difference of 1.5 V is the reason of led on. Just a question. Is the MIDI IN working?

I am building my pedal prototype and I am in the process of modifying the design of the PCB board and shell. I haven't purchased a MIDI data cable to test whether the MIDI interface can send and receive messages normally. When I found that the MIDI IN LED is always on, I thought It is my schematic or circuit problem, so I have repeatedly checked the schematic, checked related issues, and purchased multiple 6N137 optocoupler replacements to troubleshoot the problem. Is the current voltage difference a problem with my construction or the original design? Sorry, I only understand a little bit of code, and basically don't understand the circuit.
