### ISSUE TITLE
Feature request: Flash ESP32 via Chrome Web Serial API

### ISSUE THREAD

**Issue by renne** [alf45tar/PedalinoMini#292]
Hi,

currently OS-specific command-line tools or IDEs are necessary to flash PedalinoMini on the ESP32.
This makes the use of PedalinoMini impossible for non IT-savy musicians.

I suggest flashing the ESP32 via the [Chrome Web Serial API](https://codelabs.developers.google.com/codelabs/web-serial#0).
[Tasmota](https://tasmota.github.io/) uses the Chrome Web Serial API [here](https://tasmota.github.io/install/) via the [ESP Web Tools](https://esphome.github.io/esp-web-tools/).

**Comment by alf45tar** [comment]
It looks interesting. Thanks @renne to let me know that technology. I will use for sure for flash PedalinoMini.

**Comment by mknerr** [comment]
Thank you! I just encountered this as well while working with a smart home project (ESPhome), and was blown away. I have been able to get platformIO working most of the time, but it has definitely been a source of frustration at times, and an obstacle I

**Comment by alf45tar** [comment]
Stay tuned. It will be released soon.

**Comment by alf45tar** [comment]
Just released

**Comment by mknerr** [comment]
Amazing. Can't wait to try it.

**Comment by renne** [comment]
@alf45tar 
I just installed PedalinoMini on a TTGO T-Display via Chrome (Version 96.0.4664.93 (Offizieller Build) (64-Bit)) on Ubuntu 21.04.

Great!
