### ISSUE TITLE
Schematics for the sponsors case version

### ISSUE THREAD

**Issue by gustavsl** [alf45tar/PedalinoMini#295]
I've been tinkering with the many possibilities of the firmware and found out that the 8 button configuration from the sponsor's case which I 3D printed would suit me well.
Is there any schematics or further details to build such a setup?
Thanks a lot for your work!

**Comment by jisv48** [comment]
Hola Gustavo,

What type of material did you use on the printing of the case?  I appreciate your assistance since this will be the first time I’ll 3D print something. Thanks Jose Salazar

**Comment by gustavsl** [comment]
Hey @jisv48! I printed this in red PLA, 0.25 layer height and 20% triangle infill. Feels solid enough.

**Comment by alf45tar** [comment]
@gustavsl added schematics here https://github.com/alf45tar/PedalinoMini-Case-1
PedalinoMini Case 1 in PLA is indestructible. Charge with you weight (before to add the foot switches of course) and let me know if you broken it. I don't think so.

**Comment by gustavsl** [comment]
@alf45tar thank you so much for this! All the switches are SPDT, right?

And you were right, attached is a pic of me standing over the case :) Sturdy as hell.
![IMG_1679](https://user-images.githubusercontent.com/5434838/145110222-4bdfe032-d981-4bba-b8fd-d0de54400655.png)

**Comment by alf45tar** [comment]
I use 3PDT because they are generally available.
SPDT are fine too.
