### ISSUE TITLE
ttgo cannot be built

### ISSUE THREAD

**Issue by bobvc133** [alf45tar/PedalinoMini#299]
Executing task: C:\Users\dada\.platformio\penv\Scripts\platformio.exe run --environment ttgo-t-display <

Processing ttgo-t-display (platform: espressif32; framework: arduino; board: esp32dev)
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32dev.html
PLATFORM: Espressif 32 (3.4.0) > Espressif ESP32 Dev Module
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
DEBUG: Current (esp-prog) External (esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES:
 - framework-arduinoespressif32 3.10006.210326 (1.0.6)
 - tool-esptoolpy 1.30100.210531 (3.1.0)
 - toolchain-xtensa32 2.50200.97 (5.2.0)
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 45 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <AceButton> 1.9.1+sha.5a11b88
|-- <ArduinoJson> 6.18.5+sha.ed342b9
|-- <AsyncTCP> 1.1.1+sha.ca8ac5f
|-- <ESP Async WebServer> 1.2.3+sha.1d46269
|   |-- <AsyncTCP> 1.1.1+sha.ca8ac5f
|   |-- <FS> 1.0
|   |-- <WiFi> 1.0
|   |-- <ArduinoJson> 6.18.5+sha.ed342b9
|-- <ESP8266 and ESP32 OLED driver for SSD1306 displays> 4.2.1+sha.216812c
|   |-- <Wire> 1.0.1
|   |-- <SPI> 1.0
|-- <FastLED> 3.4.0+sha.1d236ab
|   |-- <SPI> 1.0
|-- <Improv> 1.0.0+sha.e8d5177
|-- <MD_REncoder> 1.0.1+sha.d0c998d
|-- <NimBLE-Arduino> 1.3.1+sha.4a6111d
|-- <OSC> 0.0.0+sha.de8cf4b
|-- <ResponsiveAnalogRead> 1.2.1+sha.504c16b
|-- <TFT_eSPI> 2.4.0+sha.eee56b2
|   |-- <SPIFFS> 1.0
|   |   |-- <FS> 1.0
|   |-- <FS> 1.0
|   |-- <SPI> 1.0
|-- <MIDI Library> 5.0.2+sha.8f8c7cf
|-- <AppleMIDI> 3.1.2+sha.df105dc
|   |-- <MIDI Library> 5.0.2+sha.8f8c7cf
|-- <BLE-MIDI> 2.1.1+sha.5c42e14
|   |-- <MIDI Library> 5.0.2+sha.8f8c7cf
|   |-- <NimBLE-Arduino> 1.3.1+sha.4a6111d
|-- <ipMIDI> 1.0.3+sha.b166047
|   |-- <MIDI Library> 5.0.2+sha.8f8c7cf
|-- <Preferences> 1.0
|-- <SPIFFS> 1.0
|   |-- <FS> 1.0
|-- <WiFi> 1.0
|-- <SPI> 1.0
|-- <Wire> 1.0.1
|-- <Ticker> 1.1
|-- <HTTPClient> 1.2
|   |-- <WiFi> 1.0
|   |-- <WiFiClientSecure> 1.0
|   |   |-- <WiFi> 1.0
|-- <Update> 1.0
|-- <WiFiClientSecure> 1.0
|   |-- <WiFi> 1.0
|-- <ArduinoOTA> 1.0
|   |-- <Update> 1.0
|   |-- <WiFi> 1.0
|   |-- <ESPmDNS> 1.0
|   |   |-- <WiFi> 1.0
|-- <ESPmDNS> 1.0
|   |-- <WiFi> 1.0
|-- <ESP32 Async UDP> 1.0.0
|-- <FS> 1.0
Building in release mode
Compiling .pio\build\ttgo-t-display\libf3f\TFT_eSPI\TFT_eSPI.cpp.o
Archiving .pio\build\ttgo-t-display\lib0c2\libAsyncUDP.a
Compiling .pio\build\ttgo-t-display\FrameworkArduino\WString.cpp.o
Compiling .pio\build\ttgo-t-display\FrameworkArduino\base64.cpp.o
Compiling .pio\build\ttgo-t-display\FrameworkArduino\cbuf.cpp.o
Compiling .pio\build\ttgo-t-display\FrameworkArduino\esp32-hal-adc.c.o
.pio\libdeps\ttgo-t-display\TFT_eSPI\TFT_eSPI.cpp: In member function 'virtual void TFT_eSPI::drawPixel(int32_t, int32_t, uint32_t)':
.pio\libdeps\ttgo-t-display\TFT_eSPI\TFT_eSPI.cpp:3289:21: error: 'SPI_X' was not declared in this scope
   while (spi_get_hw(SPI_X)->sr & SPI_SSPSR_BSY_BITS) {};
                     ^
Compiling .pio\build\ttgo-t-display\FrameworkArduino\esp32-hal-bt.c.o
.pio\libdeps\ttgo-t-display\TFT_eSPI\TFT_eSPI.cpp:3289:26: error: 'spi_get_hw' was not declared in this scope
   while (spi_get_hw(SPI_X)->sr & SPI_SSPSR_BSY_BITS) {};
                          ^
.pio\libdeps\ttgo-t-display\TFT_eSPI\TFT_eSPI.cpp:3289:34: error: 'SPI_SSPSR_BSY_BITS' was not declared in this scope
   while (spi_get_hw(SPI_X)->sr & SPI_SSPSR_BSY_BITS) {};
                                  ^
.pio\libdeps\ttgo-t-display\TFT_eSPI\TFT_eSPI.cpp:3294:20: error: 'SPI_X' was not declared in this scope
     spi_set_format(SPI_X,  8, (spi_cpol_t)0, (spi_cpha_t)0, SPI_MSB_FIRST);
                    ^
.pio\libdeps\ttgo-t-display\TFT_eSPI\TFT_eSPI.cpp:3294:32: error: 'spi_cpol_t' was not declared in this scope
     spi_set_format(SPI_X,  8, (spi_cpol_t)0, (spi_cpha_t)0, SPI_MSB_FIRST);
                                ^
.pio\libdeps\ttgo-t-display\TFT_eSPI\TFT_eSPI.cpp:3294:47: error: 'spi_cpha_t' was not declared in this scope
     spi_set_format(SPI_X,  8, (spi_cpol_t)0, (spi_cpha_t)0, SPI_MSB_FIRST);
                                               ^
.pio\libdeps\ttgo-t-display\TFT_eSPI\TFT_eSPI.cpp:3294:61: error: 'SPI_MSB_FIRST' was not declared in this scope
     spi_set_format(SPI_X,  8, (spi_cpol_t)0, (spi_cpha_t)0, SPI_MSB_FIRST);
                                                             ^
.pio\libdeps\ttgo-t-display\TFT_eSPI\TFT_eSPI.cpp:3294:74: error: 'spi_set_format' was not declared in this scope
     spi_set_format(SPI_X,  8, (spi_cpol_t)0, (spi_cpha_t)0, SPI_MSB_FIRST);
                                                                          ^
.pio\libdeps\ttgo-t-display\TFT_eSPI\TFT_eSPI.cpp:3296:19: error: 'spi_get_hw' was not declared in this scope
   spi_get_hw(SPI_X)->dr = (uint32_t)TFT_CASET;
                   ^
.pio\libdeps\ttgo-t-display\TFT_eSPI\TFT_eSPI.cpp:3298:34: error: 'SPI_SSPSR_BSY_BITS' was not declared in this scope
   while (spi_get_hw(SPI_X)->sr & SPI_SSPSR_BSY_BITS){};
                                  ^
.pio\libdeps\ttgo-t-display\TFT_eSPI\TFT_eSPI.cpp:3305:34: error: 'SPI_SSPSR_BSY_BITS' was not declared in this scope
   while (spi_get_hw(SPI_X)->sr & SPI_SSPSR_BSY_BITS) {};
                                  ^
.pio\libdeps\ttgo-t-display\TFT_eSPI\TFT_eSPI.cpp:3309:34: error: 'SPI_SSPSR_BSY_BITS' was not declared in this scope
   while (spi_get_hw(SPI_X)->sr & SPI_SSPSR_BSY_BITS) {};
                                  ^
.pio\libdeps\ttgo-t-display\TFT_eSPI\TFT_eSPI.cpp:3316:34: error: 'SPI_SSPSR_BSY_BITS' was not declared in this scope
   while (spi_get_hw(SPI_X)->sr & SPI_SSPSR_BSY_BITS) {};
                                  ^
.pio\libdeps\ttgo-t-display\TFT_eSPI\TFT_eSPI.cpp:3328:36: error: 'SPI_SSPSR_BSY_BITS' was not declared in this scope
     while (spi_get_hw(SPI_X)->sr & SPI_SSPSR_BSY_BITS) {};
                                    ^
.pio\libdeps\ttgo-t-display\TFT_eSPI\TFT_eSPI.cpp:3352:34: error: 'SPI_SSPSR_BSY_BITS' was not declared in this scope
   while (spi_get_hw(SPI_X)->sr & SPI_SSPSR_BSY_BITS) {};
                                  ^
.pio\libdeps\ttgo-t-display\TFT_eSPI\TFT_eSPI.cpp: In member function 'virtual int16_t TFT_eSPI::drawChar(uint16_t, int32_t, int32_t, uint8_t)':
.pio\libdeps\ttgo-t-display\TFT_eSPI\TFT_eSPI.cpp:4133:12: warning: unused variable 'flash_address' [-Wunused-variable]
   uint32_t flash_address = 0;
            ^
.pio\libdeps\ttgo-t-display\TFT_eSPI\TFT_eSPI.cpp:4162:11: warning: unused variable 'w' [-Wunused-variable]
   int32_t w = width;
           ^
.pio\libdeps\ttgo-t-display\TFT_eSPI\TFT_eSPI.cpp:4163:11: warning: unused variable 'pX' [-Wunused-variable]
   int32_t pX      = 0;
           ^
.pio\libdeps\ttgo-t-display\TFT_eSPI\TFT_eSPI.cpp:4164:11: warning: unused variable 'pY' [-Wunused-variable]
   int32_t pY      = y;
           ^
.pio\libdeps\ttgo-t-display\TFT_eSPI\TFT_eSPI.cpp:4165:11: warning: unused variable 'line' [-Wunused-variable]
   uint8_t line = 0;
           ^
.pio\libdeps\ttgo-t-display\TFT_eSPI\TFT_eSPI.cpp:4166:8: warning: unused variable 'clip' [-Wunused-variable]
   bool clip = xd < _vpX || xd + width  * textsize >= _vpW || yd < _vpY || yd + height * textsize >= _vpH;
        ^
In file included from .pio\libdeps\ttgo-t-display\TFT_eSPI\TFT_eSPI.cpp:4991:0:
.pio\libdeps\ttgo-t-display\TFT_eSPI\Extensions/Sprite.cpp: In member function 'virtual int16_t TFT_eSprite::drawChar(uint16_t, int32_t, int32_t, uint8_t)':
Compiling .pio\build\ttgo-t-display\FrameworkArduino\esp32-hal-cpu.c.o
.pio\libdeps\ttgo-t-display\TFT_eSPI\Extensions/Sprite.cpp:2178:12: warning: unused variable 'flash_address' [-Wunused-variable]
   uint32_t flash_address = 0;
            ^
.pio\libdeps\ttgo-t-display\TFT_eSPI\Extensions/Sprite.cpp:2207:11: warning: unused variable 'w' [-Wunused-variable]
   int32_t w = width;
           ^
.pio\libdeps\ttgo-t-display\TFT_eSPI\Extensions/Sprite.cpp:2208:11: warning: unused variable 'pX' [-Wunused-variable]
   int32_t pX      = 0;
           ^
.pio\libdeps\ttgo-t-display\TFT_eSPI\Extensions/Sprite.cpp:2209:11: warning: unused variable 'pY' [-Wunused-variable]
   int32_t pY      = y;
           ^
.pio\libdeps\ttgo-t-display\TFT_eSPI\Extensions/Sprite.cpp:2210:11: warning: unused variable 'line' [-Wunused-variable]
   uint8_t line = 0;
           ^
.pio\libdeps\ttgo-t-display\TFT_eSPI\Extensions/Sprite.cpp:2211:8: warning: unused variable 'clip' [-Wunused-variable]
   bool clip = xd < _vpX || xd + width  * textsize >= _vpW || yd < _vpY || yd + height * textsize >= _vpH;
        ^
Compiling .pio\build\ttgo-t-display\FrameworkArduino\esp32-hal-dac.c.o
Compiling .pio\build\ttgo-t-display\FrameworkArduino\esp32-hal-gpio.c.o
Compiling .pio\build\ttgo-t-display\FrameworkArduino\esp32-hal-i2c.c.o
Compiling .pio\build\ttgo-t-display\FrameworkArduino\esp32-hal-ledc.c.o
*** [.pio\build\ttgo-t-display\libf3f\TFT_eSPI\TFT_eSPI.cpp.o] Error 1
============================================================================================================================================= [FAILED] Took 11.50 seconds =============================================================================================================================================
Environment     Status    Duration
--------------  --------  ------------
ttgo-t-display  FAILED    00:00:11.502
======================================================================================================================================== 1 failed, 0 succeeded in 00:00:11.502 ========================================================================================================================================终端进程“C:\Users\dada\.platformio\penv\Scripts\platformio.exe 'run', '--environment', 'ttgo-t-display'”已终止，退出代码: 1。

终端将被任务重用，按任意键关闭。

**Comment by alf45tar** [comment]
Did you try a Clean All before Build?

**Comment by alf45tar** [comment]
The latest version of TFT_eSPI library has an issue. To use the previous one edit platform.ini and modify lib_deps with

`https://github.com/Bodmer/TFT_eSPI#20ad7e2`

**Comment by alf45tar** [comment]
Temporary fix non anymore need. TFT_eSPI library fixed.

**Comment by bobvc133** [comment]
received, thank you
