### ISSUE TITLE
help with windows???

### ISSUE THREAD

**Issue by gurnay1973** [alf45tar/PedalinoMini#3]
with windows works through wifi ???? or just midi usb ???? Thank you.

**Comment by alf45tar** [comment]
Both works with Windows.

Wifi requires rtpMIDI (https://www.tobias-erichsen.de/software/rtpmidi.html) or ipMIDI (https://nerds.de/en/ipmidi.html) or https://www.humatic.de/htools/mnet/man.htm for both.
