### ISSUE TITLE
HC-SR04 module library download address is missing

### ISSUE THREAD

**Issue by bobvc133** [alf45tar/PedalinoMini#300]
The download address of the ultrasonic module library is not added in the platformio.ini configuration file

**Comment by alf45tar** [comment]
@bobvc133 thanks for reporting.
Fixed.

**Comment by bobvc133** [comment]
c_cpp_properties.json configuration is also missing

**Comment by alf45tar** [comment]
c_cpp_properties.json is auto generated

**Comment by bobvc133** [comment]
Okay, maybe because of my network problem I didn’t download the library file and generate it automatically
