### ISSUE TITLE
Feature request: Audio-to-MIDI conversion

### ISSUE THREAD

**Issue by renne** [alf45tar/PedalinoMini#305]
@alf45tar 
Philip Karlsson Gisslow showed it is possible to [convert audio to midi in real-time on a Raspberry Pi Pico](https://www.youtube.com/watch?v=Fu0Qsz2h3HE).
It would be great to have this on PedalinoMini using the ADCs of the ESP32. Multiple ADC-inputs, e.g. connected to a hexa-phonic guitar pickup like [Roland GK-Kit GT3](https://www.amazon.com/Roland-GK-KIT-GT3-GK-Kit-GT3/dp/B004AUAUQA), would allow polyphonic Audio-to-MIDI conversion

**Comment by alf45tar** [comment]
It looks like Philip is not sharing or selling the `libmigic.`
