### ISSUE TITLE
HC-SR04 doesn`t work with new update

### ISSUE THREAD

**Issue by e36910** [alf45tar/PedalinoMini#309]
I tried connect HC-SR04 VCC-VIN, GND-GND, Echo-D34, Trig-D27. Also I configured pedal3 mode analog and action for pedal3 - move fnd CC. What I did wrong?

**Comment by e36910** [comment]
Also I connected R10 via 3v and D34

**Comment by alf45tar** [comment]
Pedal mode should be ULTRASONIC.

**Comment by e36910** [comment]
It doesn't have after update. 
![Screenshot_2022-01-10-18-50-47-677_com android chrome](https://user-images.githubusercontent.com/85799952/148805869-c925b64b-a252-4346-b9dd-df541603f785.jpg)

**Comment by alf45tar** [comment]
Which version are you using? Ultrasonic sensor is released only for sponsors. Version is 2.3.3.
