### ISSUE TITLE
Updating 

### ISSUE THREAD

**Issue by mknerr** [alf45tar/PedalinoMini#31]
Forgive me, but what's the best way to update with new firmware? I rebuilt and uploaded, but I don't think I'm seeing changes in the web interface, and I'm not sure if the firmware is different either, because changes I thought had been made to the display weren't evident either.

I also tried to use the OTA update feature, but couldn't find the binary in PlatformIO.

Thanks in advance.

**Comment by jimhiggs** [comment]
I assume you worked it out as this is so old. As to OTA, I was presuming you use firmware.bin which is buried in the project folder where your code is. Look for a .pio folder and then build and the project name (your choice of env during build).
Having said that I don't believe OTA is working for me as it resets the chip but is over far too soon. No idea how  to find out whats is going on though . Perhaps I should open a new ticket eh?.
