### ISSUE TITLE
Question on powering

### ISSUE THREAD

**Issue by Designbase** [alf45tar/PedalinoMini#311]
I am using a ESP32 Devkit, 10 buttons and 10 NeoPixels diffuus 5 mm Leds (Leds are 5V but powered by 3.3.V from board).
If I am powering the board via USB all buttons and Leds are working fine.

As soon as I power the Board with an external Power supply straight to the breadboard on the + and - strips where the ESP board is also powered from, the buttons do not react properly. It seems like the Ladder values are wrong.

How should I power this? I am planning on using a battery as soon as the project is build into the enclosure.

Thanks.

**Comment by alf45tar** [comment]
Did you redo the ladder calibration after changed the power method?
Is your power supply stable?
Check if the power wires are loose when inserted into the breadboard. Did you tried to change the breadboard holes?

**Comment by Designbase** [comment]
I just redid the calibration and indeed that solved the issue.
Thanks!
