### ISSUE TITLE
Jog Wheel Setup

### ISSUE THREAD

**Issue by prostealth** [alf45tar/PedalinoMini#313]
hi, Im trying to use a jog wheel as preset up and down. but in the menu there is only 1 action (jog) and 1 button. make it rotating left and right only resulting same action. is it normal?

**Comment by alf45tar** [comment]
Yes, it is. Rotating a jog wheel increase or decrease the value of one CC.
The button of jog wheel can be linked to a different action.
Of course multiple actions can be linked to the same jog wheel.
