### ISSUE TITLE
How can I set it up to achieve a setting similar to the LINE6 fbv MK2 expression pedal?

### ISSUE THREAD

**Issue by bobvc133** [alf45tar/PedalinoMini#314]
Hello, how can the pedalinomini be set up to achieve a setting similar to the LINE6 fbv MK2 expression pedal? The default is VOLUME function and LED, move the pedal to send CC7, when you move the expression pedal until the bottom momentary switch is triggered, activate the WHA function and LED, turn off the VOLUME function and LED, then move the pedal to send CC11
![P20205-175258_看图王](https://user-images.githubusercontent.com/91867813/152637812-1023ef12-6022-44f6-85da-d4227b7708e0.jpg)
![P20205-175307_看图王](https://user-images.githubusercontent.com/91867813/152637896-41e786cc-ea1a-4804-9e55-cf8825a5933b.jpg)

**Comment by alf45tar** [comment]
![Screenshot 2022-02-05 at 11 21 29](https://user-images.githubusercontent.com/35426671/152638156-d53e87ea-e5f6-4523-8159-25bcef41fbc7.png)

**Comment by alf45tar** [comment]
Pedal 6 is the expression pedal
Pedal 5 is a footswitch
Led 1 is VOLUME
Led 2 is WAH

On pedal 5 press:

- CC 7 is activated/sent
- led 1 is set to green
- led 2 is set to black

On pedal 5 release:

- CC 11 is activated/set
- led 1 is set to black
- led 2 is set to red

Pedal 6 will sent the last CC activated.

**Comment by bobvc133** [comment]
Pedal 5 is momentary switch

**Comment by alf45tar** [comment]
The only way to send different CC on the same momentary switch is to use 2 banks.

On monetary switch press add 2 actions:

- send CC 7 on first bank or CC11 on second bank
- switch the next bank using Bank+ or Bank-

**Comment by bobvc133** [comment]
I tried the second scheme of switching libraries, but some settings cannot be customized, such as LED number and color

**Comment by alf45tar** [comment]
For set led color you can use a separate action
