### ISSUE TITLE
Physical wiring diagram of PedalinoMini-Case-1

### ISSUE THREAD

**Issue by bobvc133** [alf45tar/PedalinoMini#324]
Hello, can you post the physical wiring diagram of the PedalinoMini-Case-1? I would like to refer to the installation wiring

**Comment by alf45tar** [comment]
Schematic is published [here](https://github.com/alf45tar/PedalinoMini-Case-1).
What do you mean with physical wiring? A photo of my implementation?

**Comment by bobvc133** [comment]
> 

yes i would like to see how you routed the installation as i am considering whether to make a pcb board to avoid messy wiring

**Comment by bobvc133** [comment]
![Uploading Snipaste_2022-04-03_11-35-01.png…]()

**Comment by bobvc133** [comment]
In addition, is the din and dout of the WS2812B in the schematic diagram reversed?

**Comment by alf45tar** [comment]
Your PCB cannot works with PedalinoMini-Case1. Components are in a different place and also leds and footswitches are on different plane/level.

**Comment by alf45tar** [comment]
> In addition, is the din and dout of the WS2812B in the schematic diagram reversed?

You are right. Schematic is wrong. I will fix it. Thanks.

**Comment by bobvc133** [comment]
3D printing the case is a bit expensive, so I made the case out of black acrylic, the cost is only about $5, I am in China, other accessories are very cheap, and the 10-pedal pedal cost only about $30

**Comment by y0m1g** [comment]
I would also appreciate a photo of your physical implementation inside the case 🙏

**Comment by alf45tar** [comment]
![IMG_1552](https://user-images.githubusercontent.com/35426671/161814459-80634773-097c-4fb0-b873-1c87f206a663.jpg)

**Comment by alf45tar** [comment]
> > In addition, is the din and dout of the WS2812B in the schematic diagram reversed?
> 
> You are right. Schematic is wrong. I will fix it. Thanks.

Schematic has been fixed

**Comment by alf45tar** [comment]
In version 2.4.0 released last February it is possible to link each button to a led in Pedals setup in order to streamline Actions definition.

In other words assign the led to a pedal/button in Pedals setup and use Default value as led in Actions definition.

**Comment by bobvc133** [comment]
> In version 2.4.0 released last February it is possible to link each button to a led in Pedals setup in order to streamline Actions definition.
> 
> In other words assign the led to a pedal/button in Pedals setup and use Default value as led in Actions definition.
> 
> The led wiring can be simplified and the order is independent from pedals.

I mean, other than the person who made the PedalinoMini, it may take a few more tests when editing the LEDs to get the order right
