### ISSUE TITLE
Resistance Ladder Calibration Problems

### ISSUE THREAD

**Issue by bobvc133** [alf45tar/PedalinoMini#326]
I found that the resistance ladder calibration can only use the first group of interfaces, and the remaining five groups of interfaces cannot calibrate the resistance ladder. If the first group of buttons is less than 6, then the resistance ladder cannot be fully calibrated

**Comment by alf45tar** [comment]
It is by design. Only the first one is used for calibration.

**Comment by bobvc133** [comment]
> Yes, it can be modified changing the source code. In my previous reply I indicated the line of code.

alright, thank you very much!

**Comment by alf45tar** [comment]
Please share your build when finished.
