### ISSUE TITLE
Momentary switch always send Note On msgs with velocity zero

### ISSUE THREAD

**Issue by hany-tawfik** [alf45tar/PedalinoMini#327]
Hi, I am connecting PedalinoMini to Mainstage using BLE and it works fine except when sending Note On msgs, the velocity 'from value' 'to value' areas are greyed out and set to zero. I can see that a midi msg is received on Mainstage, but I can't listen to any sound because of the velocity value.

Is there something I am doing wrong?

Thanks in advance!

**Comment by alf45tar** [comment]
I fixed the bug in version 2.4.2 just released.
Thanks @hany-tawfik
