### ISSUE TITLE
FLIP_SCREEN 

### ISSUE THREAD

**Issue by bobvc133** [alf45tar/PedalinoMini#328]
#define FLIP_SCREEN  A value of 0 or 1 doesn't seem to invert the screen vertically

**Comment by alf45tar** [comment]
It works only for OLED but I am adding to TFT too.

**Comment by alf45tar** [comment]
Added from version 2.4.3

**Comment by bobvc133** [comment]
> Added from version 2.4.3

I am using an SSD1306 0.96 screen and a SSD1309 compatible SSD1306 2.42 screen. After updating to 2.4.3, the screen still does not vertically invert the screen. Besides modifying the #define FLIP_SCREEN value to 1, which code needs to be modified?

**Comment by alf45tar** [comment]
I re-tested and it works for me.
Did you customised the source?

**Comment by bobvc133** [comment]
> I re-tested and it works for me. Did you customised the source?

I have several TTGO T-DISPLAY and ESP32 development boards. The TTGO can flip the screen vertically, but the ESP32+SSD1306 screen can't. I want to know what code needs to be modified?

**Comment by alf45tar** [comment]
https://github.com/alf45tar/PedalinoMini/blob/f265fe8a7ad44d1fbcbff3457a15359d05c61882/src/DisplayOLED.h#L1147

**Comment by bobvc133** [comment]
> https://github.com/alf45tar/PedalinoMini/blob/f265fe8a7ad44d1fbcbff3457a15359d05c61882/src/DisplayOLED.h#L1147
Sponsored version DisplayOLED.h code is different

**Comment by alf45tar** [comment]
You are right. My fault.
Fixed now.

**Comment by bobvc133** [comment]
OK problem solved, #define FLIP_SCREEN value is 0 when the screen is reversed, 1 is normal
