### ISSUE TITLE
startup screen

### ISSUE THREAD

**Issue by bobvc133** [alf45tar/PedalinoMini#329]
Can TTGO customize the boot screen? How to modify?

**Comment by alf45tar** [comment]
Start here

https://github.com/alf45tar/PedalinoMini/blob/93f915d08a022515a33ca77fab4e160ca2a61f90/src/DisplayTFT.h#L1256

**Comment by bobvc133** [comment]
The image conversion array often has problems with incomplete display, it may be a problem with the image format, and finally I got it, thank you
The image conversion array often has problems with incomplete display, it may be a problem with the image format, and finally I got it, thank you
![QQ截图20220422192155](https://user-images.githubusercontent.com/91867813/164705263-3df26db4-779e-4308-bcf9-96009be122e6.jpg)
