### ISSUE TITLE
MIDI pedal finished product release & LED color issue

### ISSUE THREAD

**Issue by bobvc133** [alf45tar/PedalinoMini#330]
This is my pedal! The latest sponsored version firmware has a problem with the LED color setting, it is set to red, but the actual display is green.
![QQ截图20220426205906](https://user-images.githubusercontent.com/91867813/165307696-7099b4bb-ff32-4740-a44f-147460e18303.jpg)
![QQ截图20220426205858](https://user-images.githubusercontent.com/91867813/165307725-32718394-5b35-4c6f-bb5b-cc93260eabee.jpg)
![QQ截图20220426205914](https://user-images.githubusercontent.com/91867813/165307749-f71079b2-807c-43ed-ab88-98e3da6ff186.jpg)
![QQ截图20220426205749](https://user-images.githubusercontent.com/91867813/165307767-c072cbe8-5f8c-4cbb-ae98-08c119cd6744.jpg)
![QQ截图20220426205813](https://user-images.githubusercontent.com/91867813/165307799-8213016f-47a2-4d13-857f-fd7b80032586.jpg)
![QQ截图20220426210155](https://user-images.githubusercontent.com/91867813/165307827-c5c9ef46-fd94-4923-b3c2-4c42a727ca33.jpg)

**Comment by mknerr** [comment]
That's beautiful! 
Regarding your LED issue, I can't say for certain, but having worked with pixel strip before, I know the colors are not always addressed in the same order (ie., GRB, RGB, etc.), so you probably just need to tweak the code somewhere to adjust that. 
If you try to make them Red, do they turn green?
@alf45tar, Perhaps an option could be added to the settings to make it easier to adjust. Probably not a big deal; you'd really only need to do this once.

**Comment by bobvc133** [comment]
Yes, if you often need to modify the code to customize the settings, then it is meaningless to update the firmware through the browser, backup and restore the configuration file and other regular operations. Ordinary users basically cannot upgrade the firmware unless the firmware is a customized version. It is recommended to add custom settings such as the number of LEDs, vertically flip the screen, etc. to the WEB interface.

**Comment by mknerr** [comment]
Yeah, good point.

**Comment by alf45tar** [comment]
@bobvc133 it is amazing

**Comment by alf45tar** [comment]
> That's beautiful!
> Regarding your LED issue, I can't say for certain, but having worked with pixel strip before, I know the colors are not always addressed in the same order (ie., GRB, RGB, etc.), so you probably just need to tweak the code somewhere to adjust that.
> If you try to make them Red, do they turn green?
> @alf45tar, Perhaps an option could be added to the settings to make it easier to adjust. Probably not a big deal; you'd really only need to do this once.

Did you try to change the following setting?

https://github.com/alf45tar/PedalinoMini/blob/93f915d08a022515a33ca77fab4e160ca2a61f90/src/Pedalino.h#L28

**Comment by bobvc133** [comment]
> > That's beautiful!
> > Regarding your LED issue, I can't say for certain, but having worked with pixel strip before, I know the colors are not always addressed in the same order (ie., GRB, RGB, etc.), so you probably just need to tweak the code somewhere to adjust that.
> > If you try to make them Red, do they turn green?
> > @alf45tar, Perhaps an option could be added to the settings to make it easier to adjust. Probably not a big deal; you'd really only need to do this once.
> 
> Did you try to change the following setting?
> 
> https://github.com/alf45tar/PedalinoMini/blob/93f915d08a022515a33ca77fab4e160ca2a61f90/src/Pedalino.h#L28

You can customize the settings by modifying the code, but I have to re-flash the machine. It is basically impossible to update the firmware through the browser. VS and PlatformIO sometimes have more problems. I hope that these custom items can be set in the WEB interface, and the flashing machine is simple. Just upgrade the firmware

**Comment by alf45tar** [comment]
Thanks @bobvc133 for the suggestion. I will try to add as much as possible every configuration parameters in the web interface with the next major release.
Another planned improvement is to remove use of EEPROM and use only configuration files to avoid problem on version upgrade.

**Comment by bobvc133** [comment]
> Thanks @bobvc133 for the suggestion. I will try to add as much as possible every configuration parameters in the web interface with the next major release. Another planned improvement is to remove use of EEPROM and use only configuration files to avoid problem on version upgrade.

Looking forward to the new version of the firmware, thank you for your efforts!
