### ISSUE TITLE
Jog Wheel not working

### ISSUE THREAD

**Issue by bobvc133** [alf45tar/PedalinoMini#333]
The Jog Wheel doesn't seem to be working properly，ttgo t-display 2.4.4

**Comment by bobvc133** [comment]
![QQ截图20220507154956](https://user-images.githubusercontent.com/91867813/167244800-e5784fc6-b36a-4b21-9c7d-a9f683d7862d.jpg)
I added two more KY-040s to the pedals, the switch and the resistance ladder are connected, and the Jog Wheel is connected to A3, D3, A4, D4, they are all built according to the schematic diagram, but they can't work properly

**Comment by alf45tar** [comment]
For the moment you can use a workaround to fix the jog wheel: add at least one action to bank 0.

**Comment by bobvc133** [comment]
> For the moment you can use a workaround to fix the jog wheel: add at least one action to bank 0.

I added easing in BANK 0, KY-040 still doesn't work
