### ISSUE TITLE
ESP Web Tools

### ISSUE THREAD

**Issue by bobvc133** [alf45tar/PedalinoMini#341]
Because I am in China, I need a VPN to use ESP Web Tools, so I configured an ESP Web Tools server test, but found a problem, my TTGO T-DISPLAY memory is 16M, built by VS or you ESP Web Tools burns the firmware, the WEB interface can display the normal size of 16m, but the memory of the ESP Web Tools I built only shows 4M after burning, have you encountered such a problem? How is it solved?

**Comment by alf45tar** [comment]
ESP32 has the ability to also use up to 4 MB of external SPI RAM memory. The external memory is incorporated in the memory map and, with certain restrictions, is usable in the same way as internal data RAM.

https://thingpulse.com/esp32-how-to-use-psram/
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/external-ram.html

**Comment by bobvc133** [comment]
![QQ截图20220526200051](https://user-images.githubusercontent.com/91867813/170485227-0c740d7a-45ee-4e40-a090-7383866cab13.jpg)
![QQ截图20220526200839](https://user-images.githubusercontent.com/91867813/170485244-683e7b98-bf94-4ca1-89e3-cba2b8139eee.jpg)
![QQ截图20220526200428](https://user-images.githubusercontent.com/91867813/170485267-30748670-1486-42d6-bf5b-5c7cf357a343.jpg)
![Snipaste_2022-05-26_20-03-53](https://user-images.githubusercontent.com/91867813/170485273-f69cbebb-7651-4d33-b5a0-b88c17a3dcf7.png)
The first two pictures are the results of upgrading the firmware on the ESP Web Tools page I built, and the last two pictures are the results of upgrading the firmware on the ESP Web Tools page you built. The hardware and firmware used are the same, but the Flash Size is different.

**Comment by alf45tar** [comment]
Did you changed partitions file?

**Comment by bobvc133** [comment]
> Did you changed the partitions file?
> 
> https://github.com/alf45tar/PedalinoMini/blob/master/src/partitions_ota.csv

I just modified the firmware link address of ttgo-t-display-2.4.0.json, because I installed ESP Web Tools on my server and copied the 2.4.0 version firmware you released, so I didn't modify other files at all, the only one The difference is that I use the ESP Web Tools installed on my own server to upgrade the firmware. Is it because my ESP Web Tools configuration is wrong that the Flash Size is different?

**Comment by alf45tar** [comment]
The SPI flash size is configured by writing a field in the software bootloader image header, flashed at offset 0x1000.

By default, the SPI flash size is detected by esptool.py when this bootloader is written to flash, and the header is updated with the correct size. Alternatively, it is possible to generate a fixed flash size by setting CONFIG_ESPTOOLPY_FLASHSIZE in the project configuration.

**Comment by bobvc133** [comment]
> The SPI flash size is configured by writing a field in the software bootloader image header, flashed at offset 0x1000.
> 
> By default, the SPI flash size is detected by esptool.py when this bootloader is written to flash, and the header is updated with the correct size.
> 
> esptool.py is used by VSC but not by ESP Web Tool.

Maybe you don't understand what I mean. Below the screenshot above, I have explained that when I use the ESP Web Tool page you built to upgrade the firmware, it will correctly identify the flash size, the Flash Size is 16m, but after the ESP Web Tool page I built is upgraded However, it shows that the Flash Size 4m, ttgo-t-display-2.4.0.json and other files have not been modified, and the path is "https://raw.githubusercontent.com/alf45tar/PedalinoMini/2.4.0/firmware/ttgo- t-display/”. VSC is not used.
![Snipaste_2022-05-29_00-24-55_看图王](https://user-images.githubusercontent.com/91867813/170834096-af8d4d97-16e9-4ebd-b2d9-2209ba795099.png)
