### ISSUE TITLE
Latch display problem

### ISSUE THREAD

**Issue by bobvc133** [alf45tar/PedalinoMini#344]
The code in the red box was added by me, you can see if it is missing, I found that when I set the pedal to Latch, add an action to send Control Change, and the sent signal still shows Code instead of CC
![Snipaste_2022-06-10_19-09-11](https://user-images.githubusercontent.com/91867813/173054514-8f8adde2-432f-4d30-86be-c97d3c291c61.png)

**Comment by alf45tar** [comment]
Thank you. I will fix it the next version.
