### ISSUE TITLE
invalid attribute

### ISSUE THREAD

**Issue by bobvc133** [alf45tar/PedalinoMini#346]
After setting the LED color action and saving the configuration file, the jsoneditor in the configuration page will prompt that the channel is an invalid attribute

**Comment by bobvc133** [comment]
In addition, save the configuration file, apply and save this configuration in other user configuration groups, the LED color setting item in the sequence has an error LED number, which is 1 larger than the actual number

**Comment by alf45tar** [comment]
Thanks for debugging.
Both fixed in version 2.4.5 just release for sponsors.
