### ISSUE TITLE
RGB order modification

### ISSUE THREAD

**Issue by bobvc133** [alf45tar/PedalinoMini#349]
I have changed the RGB order to GRB in the WebConfigAsync.h file, the actual LED display color is correct, but the order of the options page still displays RGB, how can I change the default display GRB?

**Comment by bobvc133** [comment]
> Not sure what you changed in WebConfigAsync.h. EEPROM is changed. Did you reset it to factory default?

The purpose of modifying these default settings is to hope that these basic items will not be set when restoring to factory settings

**Comment by alf45tar** [comment]
Change the following line in Pedalino.h too

`EOrder  rgbOrder = RGB;`

**Comment by bobvc133** [comment]
> EOrder rgbOrder = RGB

ok, perfect
