### ISSUE TITLE
The problem with version 2.4.8 still exists in version 2.4.9

### ISSUE THREAD

**Issue by bobvc133** [alf45tar/PedalinoMini#354]
The steps of booting and networking are incomplete, only the first two, and the number of LEDs on the option page cannot be saved and modified

**Comment by alf45tar** [comment]
The re-add steps modify platform.ini. Firmware is going too big to include everything. Select what you need and compile it.
Number of leds in Options page is experimental (it is not included in the list of changes). FastLED library do no support to change the number of LEDS at runtime.
