### ISSUE TITLE
How to set the action to switch effect switches of different effect chains

### ISSUE THREAD

**Issue by bobvc133** [alf45tar/PedalinoMini#358]
How to set up actions to toggle different effect switches on the effect chain, for example by default effect A is on and effect B is off, when you press the pedal, effect A is off and effect B is on, when you press the pedal again, effect A On, Effect B is off.

**Comment by alf45tar** [comment]
Use Sequences

**Comment by bobvc133** [comment]
> Use Sequences

Can you show the specific setup of actions and sequences? When the effect is switched, two different CC signals are sent. Send 0 is turned off, and send 127 is turned on. There are problems with the send signal or the indicator light I set.

**Comment by alf45tar** [comment]
![Screenshot 2022-08-20 at 20 06 35](https://user-images.githubusercontent.com/35426671/185760653-60458ec8-a984-49de-973b-1f9627c98233.png)

![Screenshot 2022-08-20 at 20 06 46](https://user-images.githubusercontent.com/35426671/185760654-a0602a74-145b-4fc6-bdc9-1b8bd75ef365.png)

![Screenshot 2022-08-20 at 20 07 21](https://user-images.githubusercontent.com/35426671/185760656-0aeddda3-f257-4dd5-b820-1c4d40397a98.png)

**Comment by bobvc133** [comment]
This configuration is still an instantaneous effect, it should be a latch effect. For example, by default, the A effect is turned on, the B effect is turned off, and the indicator light is red. Step on it to turn off the A effect and turn on the B effect, and the indicator light turns green. , press again to restore the original state

**Comment by alf45tar** [comment]
With a momentary switch activate the second action on DOUBLE CLICk or LONG PRESS.
At the moment it is the only alternative because PedalinoMini can store one previous value per pedal only. In your case you should store at least 2 values.

**Comment by bobvc133** [comment]
Unless it is a combination of click+double-click or long-press, the long-press will first trigger the pressed action and then execute the long-pressed action. A double tap will trigger the double tap action followed by the two pressed actions.

**Comment by alf45tar** [comment]
You are right. Replace PRESS with CLICK on first action.

**Comment by bobvc133** [comment]
This problem can be solved if the hardware is replaced by a latch switch, but the long-press and repeated-press actions will not work.

**Comment by alf45tar** [comment]
Did you enabled them in Pedals setup?

**Comment by bobvc133** [comment]
No, my button hardware is a momentary switch, using the resistance ladder mode, the question about the latching switch is just my personal judgment
