### ISSUE TITLE
Disable Battery Indicator on TTGO T-Eight 

### ISSUE THREAD

**Issue by bobbyzero** [alf45tar/PedalinoMini#36]
When installed on the T-Eight and powered by USB, the battery indicator on the display constantly flashes at empty.

An option to disable this display element would be ideal, I'm never going to need it.

**Comment by alf45tar** [comment]
Comment "-D BATTERY" on platformio.ini

**Comment by bobbyzero** [comment]
I commented out the line "-D BATTERY" in the "build_flags_ttgo_t_eight section" of platformio.ini

- no change, battery icon still flashes.

Did a complete clean, flash erase, and rebuild and upload via Platformio to confirm

**Comment by alf45tar** [comment]
Very stange. Try deleting the line -D BATTERY in platformio.ini

**Comment by bobbyzero** [comment]
That's fixed it, thanks!
