### ISSUE TITLE
Interface page options

### ISSUE THREAD

**Issue by bobvc133** [alf45tar/PedalinoMini#365]
In the interface page of the document introduction, the options of Show Incoming and Show Outcoming have been deleted. In fact, the interface page of the 2.5.1 firmware still exists. Are these two items already invalid?
![webui-interfaces](https://raw.githubusercontent.com/alf45tar/PedalinoMini/master/images/webui-interfaces.png)

**Comment by alf45tar** [comment]
Yes, they are valid.
The screenshot is an old image. Documentation need to be updated.

**Comment by bobvc133** [comment]
Version 2.5.3 firmware screenshots and interface introduction have not been modified
