### ISSUE TITLE
External button

### ISSUE THREAD

**Issue by bobvc133** [alf45tar/PedalinoMini#366]
I want to connect two external buttons on ESP32_DOIT, one to control the configuration file switch, one to control the library switch, GPIO0 has been mapped to GPIO23 and can be used normally, and I also want to set an 8th button similar to GPIO35 of TTGO T DISPALY, which can be used GPIO2 interface, what code needs to be modified?
![Snipaste_2022-09-12_14-49-40](https://user-images.githubusercontent.com/91867813/189590483-9d6cfd1e-36dd-43f6-9aa8-6ec90f5d64dd.png)

**Comment by bobvc133** [comment]
I tested and found that when GPIO23 is mapped as the BOOT button, and the power on/off function is set, it can be powered off but cannot be powered on

**Comment by alf45tar** [comment]
Not completely clear your request. Let me try to reply.

Configuration file switch is not possible using pedals. This is not an available action. It is not so complex to implement. Do you need it?

What do you mean with library switch? Is it he same of bank switch? if yest it is already implemented as an action and can be linked to any pedal.

What do yo mean with GPIO23 mapped as BOOT button? BOOT button is connected to GPIO00.

**Comment by bobvc133** [comment]
What I mean is to ask which extra GPIOs can be used on the ESP32_DOIT development board. I plan to connect two external buttons to implement the functions I defined for GPIO0 and GPIO35 on the TTGO development board.
![Snipaste_2022-09-28_23-19-55](https://user-images.githubusercontent.com/91867813/192818780-02d0830f-83d8-46bb-8df4-ebab35d9b491.png)

**Comment by bobvc133** [comment]
This problem has been solved, modify the code to change GPIO0 to GPIO2, add a pull-down resistor, and then add GPIO23 port as pedal 8
![Uploading Snipaste_2022-12-03_23-28-33.png…]()
