### ISSUE TITLE
Upload configuration error message

### ISSUE THREAD

**Issue by bobvc133** [alf45tar/PedalinoMini#367]
When uploading a configuration file, it will remind the upload is complete and no file is selected at the same time

![Snipaste_2022-09-12_21-04-12](https://user-images.githubusercontent.com/91867813/189661059-e893eef3-5ad9-4408-9c08-0171b3d9cb91.png)

**Comment by alf45tar** [comment]
fixed in the next release

**Comment by alf45tar** [comment]
just released public version 2.5.2

**Comment by bobvc133** [comment]
2.5.3 version firmware problem still exists

**Comment by alf45tar** [comment]
I cannot replicate it. It is disappered to me.

![Screenshot 2022-10-16 at 14 07 05](https://user-images.githubusercontent.com/35426671/196034658-d867d516-712b-460a-a935-f18fa7bf32ef.png)

**Comment by bobvc133** [comment]
Firmware version 2.5.4 is no longer a problem
