### ISSUE TITLE
When I choose options tab via web interface device rebooting

### ISSUE THREAD

**Issue by e36910** [alf45tar/PedalinoMini#368]
Device rebooting after selected options, or if I write link 192.168.4.1/options. What can I do?

**Comment by rigr** [comment]
Had the same issue while the unit was powered by USB. A separate ower source made it stable.

**Comment by e36910** [comment]
I'm using power via VIN and GDN pins wiht 5v phone adapters

**Comment by rigr** [comment]
The 5V phone adapter might be too weak if you power the LEDs from the same source. But maybe there is another issue.what board do you use? what version of pedalino? How many LEDs? what interfaces are enabled? etc

**Comment by alf45tar** [comment]
May I suggest to reset to factory default or Upload Filesystem Image?

**Comment by e36910** [comment]
After update the device does not turn on

**Comment by alf45tar** [comment]
I think I cannot help without more details. Reopen it if you need anything else.
