### ISSUE TITLE
Proper behavior of momentary 3 pedal

### ISSUE THREAD

**Issue by mknerr** [alf45tar/PedalinoMini#37]
I’ve been testing different types of switches and pedals and I have not been able to get my momentary 3 type pedal to work correctly, but I’m not entirely sure how it is supposed to function. My assumption is that I would set the corresponding pedal input to momentary 3, then configure the desired behavior in the banks tab. Presumably, then each switch would trigger MIDI value 1, 2, and 3, respectively. ??
If that’s correct, I’ll probably focus on the hardware and connections, but I’m using a TC electronic switch, and @marosell ‘s PCB, which should limit issues there. Specific behavior below.

Switch 1 fires MIDI value 1 on press, and MV2 on release. 
Switch 3 fires MV2 on press and MV3 on release.
Switch 2 is firing MIDI note 65?? (possibly from the bank 1 settings??)

I also tried a BOSS fs-6, set for momentary 2, and was similarly getting the MIDI note 65 command from switch A.

**Comment by alf45tar** [comment]
Switch 1 use current bank
Switch 2 use current bank + 1
Switch 3 use current bank + 2

**Comment by mknerr** [comment]
Thank you!! It's working perfectly, now that I know what it supposed be doing. And, the functionality is better than I had hoped.
