### ISSUE TITLE
Locations of "Apply/Save"-buttons in the web interface

### ISSUE THREAD

**Issue by MiqViq** [alf45tar/PedalinoMini#371]
To save time while editing I suggest that "Apply/Save"-buttons should be in the same row as Actions-title is, like in my example picture.

 
![Pedalino_Apply_Save_buttons-2022-10-09 at 15 11 53](https://user-images.githubusercontent.com/2473980/194756844-6895d159-d357-49f0-a8c9-673459f008d7.png)

**Comment by alf45tar** [comment]
make sense

**Comment by alf45tar** [comment]
Just released with version 2.5.3 for sponsors only.
Thanks for the suggestion.
