### ISSUE TITLE
LED color options logic reversed in Actions? 

### ISSUE THREAD

**Issue by MiqViq** [alf45tar/PedalinoMini#373]
It seems that the logic of choosing On/Off colors are reversed, at least when choosing Button action as Press.

When pressing down the Button #1 I presumed the LED to have the color that is chosen in LED's On-choice, which should follow common logic.
But instead I need to define the color in the Action's Off-choice (magenta).
The same issue is on the right side with "Button Release" chosen as trigger, with the same "reversed" logic for choosing the LED state colors.

Restarting the device did not resolve this issue.

![Pedalino_led_colors_reversed_with_on_press-2022-10-09 at 19 55 40](https://user-images.githubusercontent.com/2473980/194770319-4f51e387-3a1b-413c-a14a-832ab949e1e7.png)

**Comment by alf45tar** [comment]
Modified the interface to clarify which color is used.
Solved in version 2.5.3 just released to sponsors.
