### ISSUE TITLE
Chip resistors

### ISSUE THREAD

**Issue by bobvc133** [alf45tar/PedalinoMini#376]
Can the 1/4W resistor in the schematic be replaced with a chip resistor in a 0603 package? This saves board space

**Comment by alf45tar** [comment]
No experience with 0603 resistor but it looks like they are 1/10W.
They are ok for 10K pull-up resistors but not for 220 ohm used in MIDI because they consume 0,11W.

**Comment by smadds** [comment]
1/10W should be fine, as this is not a continuous 5V DC. Actual power is likely to be about half of the max

**Comment by alf45tar** [comment]
I agree it can works but to be safe it is better to use 2 resistors because when the UART signal is idle, it sits at a logic high state.
The value of the 2 resistors should be 1/2 if connected in serie or 2x if connected in parallel.

**Comment by bobvc133** [comment]
There should be no problem using a 1/4W 1206 resistor, the volume is slightly larger

**Comment by alf45tar** [comment]
1/4W resistor are fine.
