### ISSUE TITLE
RGB order problem

### ISSUE THREAD

**Issue by bobvc133** [alf45tar/PedalinoMini#379]
There is a problem with the RGB color order setting: the LED I use is WS2812B, and I change the color order to GRB in the options, although the LED can display red or green correctly, but when I set the PC action and repeatedly press the button, it will flash green or red once. Send PC signal to another PedalinoMini via IP MIDI, the corresponding LED will display the opposite color. In addition, modifying the factory configuration code of the Config.h file to rgbOrder = GRB does not have any effect, unless you modify the code of the Pedalino.h file to #define LED_RGB_ORDER GRB to solve the LED flashing wrong color, another PedalinoMini color shows the opposite problem.

**Comment by alf45tar** [comment]
Check the latest 2.5.4

**Comment by bobvc133** [comment]
After setting the color order to GRB in the option page, the LED can display the color normally, but modifying the factory setting rgbOrder = GRB in the Config.h code is still invalid, and must be modified in the option page.
![Snipaste_2022-10-16_21-31-05](https://user-images.githubusercontent.com/91867813/196038436-acdf49e9-db3b-4143-912b-2f2216e9d270.png)

**Comment by bobvc133** [comment]
In addition, the documentation does not update the pictures and information about Show Incoming and Show Outcoming in the Interfaces page.

**Comment by alf45tar** [comment]
> In addition, the documentation does not update the pictures and information about Show Incoming and Show Outcoming in the Interfaces page.

Noted. I will fix it soon or later. It is not on top of priorities.

**Comment by alf45tar** [comment]
> After setting the color order to GRB in the option page, the LED can display the color normally, but modifying the factory setting rgbOrder = GRB in the Config.h code is still invalid, and must be modified in the option page.
> ![Snipaste_2022-10-16_21-31-05](https://user-images.githubusercontent.com/91867813/196038436-acdf49e9-db3b-4143-912b-2f2216e9d270.png)

This change is not enough if not saved into NVS.

**Comment by bobvc133** [comment]
I modified the code in the Config.h file EOrder order = GRB and the code in the Pedalino.h file EOrder rgbOrder = GRB solved my problem, but I don't know if there are other problems with this modification

**Comment by alf45tar** [comment]
I do not think you will issues with this 2 changes.
