### ISSUE TITLE
Wrong drawing of bottom row

### ISSUE THREAD

**Issue by potul** [alf45tar/PedalinoMini#383]
When a button in the top row is active, the button in the second row is not displayed in the OLED.

I looked at the code, and in DisplayOLED.h, line 908 , depending on what is done in the top row, the display stays in black color. It should be put back into WHITE before drawing the bottom row. Adding a simple line

display->setColor(WHITE);

just before starting the "//Bottom line" section will fix the issue.

**Comment by potul** [comment]
Let me clarify I'm not using the sponsor version, so I'm not sure if this is already fixed in it.

**Comment by alf45tar** [comment]
Thanks for fix. Ported to version 3.0.1 too.
