### ISSUE TITLE
Momentary 2 only displays pedal name from current bank

### ISSUE THREAD

**Issue by bobbyzero** [alf45tar/PedalinoMini#39]
When using Momentary 2 to send e.g. program change messages, the first button sends the value from the current bank, and the second button from bank + 1. But the on-screen display for both only shows the pedal name from the current bank.

I feel like the feedback should match the information being sent, i.e. when sending value from bank + 1, the pedal name for bank + 1 should be what's displayed. 

This is to recall presets on my guitar amp (H&K Grandmeister 36), and I'd like each button to have a descriptive name. Right now I have to use the name for 2 different presets

**Comment by alf45tar** [comment]
Fixed
