### ISSUE TITLE
ABOUT PROFILES IN YOUTUBE VIDEO

### ISSUE THREAD

**Issue by bobvc133** [alf45tar/PedalinoMini#391]
Can you post the full configuration files of both videos?
![Snipaste_2022-11-12_13-37-37](https://user-images.githubusercontent.com/91867813/201459283-f11bc71f-472e-4159-ae4f-7c58399144ad.png)

**Comment by bobvc133** [comment]
Another question is is the encoder not suitable for the TTGO T DISPLAY development board?

**Comment by alf45tar** [comment]
The full configuration of the first video is the 'mustang' configuration file. It is not yet updated for version 3 with Controls.
I do not have anymore the configuration of the second video because it was a test. Just set the Actions Send as Repeat.

Encoders can be used with any board.

**Comment by bobvc133** [comment]
> The full configuration of the first video is the 'mustang' configuration file. It is not yet updated for version 3 with Controls. I do not have anymore the configuration of the second video because it was a test. Just set the Actions Send as Repeat.
> 
> Encoders can be used with any board.

There seems to be an error in the configuration file
![Snipaste_2022-11-12_17-50-52](https://user-images.githubusercontent.com/91867813/201468733-e041c6f0-05da-46bf-8b54-751034e070cc.png)
![Snipaste_2022-11-12_17-51-16](https://user-images.githubusercontent.com/91867813/201468742-3d3a1721-8c99-41b7-80ec-8546903bdab5.png)
![Snipaste_2022-11-12_17-51-26](https://user-images.githubusercontent.com/91867813/201468752-ab03d68f-13f8-44bc-9286-e56bf247f11c.png)

**Comment by alf45tar** [comment]
Use sponsor 2.5.4

**Comment by bobvc133** [comment]
> Use sponsor 2.5.4

At the beginning of the test, the 2.5.4 firmware was used. I found that the configuration file format was not updated.

![Snipaste_2022-11-12_18-19-15](https://user-images.githubusercontent.com/91867813/201469669-03f6d925-5d01-46c6-984a-ac93c35eef97.png)
![Snipaste_2022-11-12_18-19-30](https://user-images.githubusercontent.com/91867813/201469675-727c4923-2700-4f6b-9980-47953cf64c25.png)

**Comment by alf45tar** [comment]
Did you updated the Filesytem Image too?

**Comment by bobvc133** [comment]
I always erase and re-burn

**Comment by bobvc133** [comment]
> Did you updated the Filesytem Image too?

I uploaded the configuration file in the sponsor version, the action and pedal settings are normal, but on the TTGO development board, only the switch is working properly, the wheel is not normal, the EPS32 doit development board switch and the wheel are both normal
