### ISSUE TITLE
2.5.4 Firmware mustang configuration file error

### ISSUE THREAD

**Issue by bobvc133** [alf45tar/PedalinoMini#392]
2.5.4 The mustang configuration file of the firmware is wrong, the tag name lacks a #, it should be Thresh ###, applying & saving to the current configuration after modification in the configuration editor will cause restart problems, even if the application & saving is successful, the tag on the action page The name still displays Thresh ##, but it can be saved as Thresh ### when edited on the action page.
![Snipaste_2022-11-13_02-55-37](https://user-images.githubusercontent.com/91867813/201490632-2dc5522e-1b7d-4ad8-b229-fc1f8b06bb28.png)
![Snipaste_2022-11-13_02-56-44](https://user-images.githubusercontent.com/91867813/201490640-13fd0411-de30-4501-869b-0577601d0452.png)

**Comment by alf45tar** [comment]
Just release version 3.0.1 with tag name truncation fix and a new 'mustang' configuration file for version 3.
