### ISSUE TITLE
Advice on control functionality

### ISSUE THREAD

**Issue by bobvc133** [alf45tar/PedalinoMini#393]
There are many unreasonable places in the control functions of the 3.0.1 firmware. I will list the problems that have been tested, and I will also put forward suggestions for improvement, hoping to help you.

question:
1. My pedal mode is the resistance ladder mode. There are two groups. If I add 12 actions, my action page will be very long, which is not conducive to comparing and viewing the function settings of the same group of buttons. The computer and mobile browser layouts will also be Confusion and large blanks appear.

![QQ截图20221114004906](https://user-images.githubusercontent.com/91867813/201533562-de9dba10-1fbf-4c6d-b780-bc2ea7037405.jpg)
![Snipaste_2022-11-14_00-49-32](https://user-images.githubusercontent.com/91867813/201533606-56a287d8-c779-4c92-8abe-504e0f622cf7.png)

2. The number of controls does not need to be so many at all, because the pedals that need control functions are all because there are fewer hardware buttons, so there are not many corresponding button combinations. For example, a pedal with 6 buttons can only expand 15 controls at most. There are only 5 or 7 controls that are convenient for foot operation, and pedals with many hardware buttons basically do not need control functions. Adding so many controls can only increase the difficulty for users to use. (The picture below shows the 6-button pedal single-foot control combination)

![Snipaste_2022-11-14_00-02-52](https://user-images.githubusercontent.com/91867813/201533256-db4437ab-339c-4d14-bbfb-ff55e2be023f.png)

3. After the user upgrades the 3.0 firmware, the previous configuration file will no longer be available, and must be reconfigured according to the concept of controls. For some users, reconfiguration is a big project.

Suggest:
1. Restore the pedal concept, the control functions appear in the form of independent control groups, up to three groups of 18 are enough. Users can directly load the configuration file of the previous version of the firmware, only need to add the settings of the control part.
2. Divide the PRESS effect into an instantaneous effect and a latch effect. The instantaneous effect consists of a Press action and a Release, which is simplified into only one Press action, saving web page layout.

![Snipaste_2022-11-13_23-25-12](https://user-images.githubusercontent.com/91867813/201533271-33b28c0a-5675-4ece-b449-1a23f37dd75b.png)
![Snipaste_2022-11-14_00-24-11](https://user-images.githubusercontent.com/91867813/201534301-e24298d2-ade2-4cd5-ba59-d73489dd04a9.png)

![201424465-88b69720-458e-4464-9959-43ebabe405cc](https://user-images.githubusercontent.com/91867813/201533293-b3f08c0e-2bfc-4640-ab6a-ea8904448abe.png)

**Comment by alf45tar** [comment]
Thanks for your feedback. Version 3 is a new born and it will grow step by step.
