### ISSUE TITLE
Sequence action label setting problem

### ISSUE THREAD

**Issue by bobvc133** [alf45tar/PedalinoMini#395]
“If action tag end with dot (.) the corresponding led and color is set on boot.”
When using the sequence, the action tags can be displayed normally, but the LED and color settings do not take effect
![Snipaste_2022-11-14_15-30-20](https://user-images.githubusercontent.com/91867813/201602249-01633066-8142-4300-9fa2-3df69c1dae76.png)

![Snipaste_2022-11-14_15-40-22](https://user-images.githubusercontent.com/91867813/201602273-dbf50bbc-7709-45b2-be3a-f95e758cc948.png)
![Snipaste_2022-11-14_15-40-33](https://user-images.githubusercontent.com/91867813/201602286-885475e6-8a7e-426d-a72e-3cb7d1b61a4d.png)

**Comment by alf45tar** [comment]
Give a try to version 3.0.2

**Comment by bobvc133** [comment]
> Give a try to version 3.0.2

The 3.0.2 firmware has other issues with the LEDs. When switching user profiles, the LEDs that were turned on in the previous user profile will remain on.

**Comment by alf45tar** [comment]
Fixed. Version remain 3.0.2.

**Comment by bobvc133** [comment]
> Fixed. Version remain 3.0.2.

Another new problem was found, the LED will flash the set color first during the network connection process.

**Comment by alf45tar** [comment]
This is not a bug. PedalinoMini works via Bluetooth during WiFI connection (or if WiFi is disabled).
The initial led status is set before WiFi connection.

**Comment by bobvc133** [comment]
> Give a try to version 3.0.2

Could you please fix the problem with the 2.5.4 firmware? Because I use the resistance ladder mode and have many buttons, the control function of version 3.0.2 is not very practical for me, and it is very inconvenient to configure.

**Comment by alf45tar** [comment]
Sorry but I have no time to back port fixes to old versions. I am supporting only the last one.
However the issue can be fixed removing the -1 from the following lines

https://github.com/alf45tar/PedalinoMini/blob/009cb836cf7acb08430078b100e7f4c5ac19dbd0/src/Controller.h#L1717-L1718

**Comment by bobvc133** [comment]
3.0.7 firmware, sending Step by Step has reproduced this problem, and the action tag setting does not take effect.
