### ISSUE TITLE
Confused with Control logic after update to 3.0.9

### ISSUE THREAD

**Issue by jimhiggs** [alf45tar/PedalinoMini#424]
I am using 3 ladders 6 switches for each.
Before updating (on 3.0.4) when I defined a press action the switch would send the On CC value on Press and the Off value on the next Press (or so I believed) so I could use the switch as a latch to say turn reverb on on the first press and off on the second press.
Since moving to 3.0.9 the action Press no longer allows me to enter an Off value or tag or set the led color. So repeated presses just do the same thing.
I tried 2 controls, one Press and one Release and also Press/Release but these send the off as soon as I release the switch.
Am I misunderstanding the way it used to work or am I missing something from how it works now?
How do I implement a latch type function with a ladder button?

**Comment by alf45tar** [comment]
Each button of your ladders must be assigned to a control. You will have 18 different controls.
Latch type function can be implemented for momentary buttons using Sequences and Step by Step action.

**Comment by jimhiggs** [comment]
Ok thanks. I think I will run out of sequences then because I have 18 ladder switches and two external i/ps for switches or exp pedals and I think most cases will need a sequence. I have already used 4 of the 16. Can I increase the number in pedalino.h file?

**Comment by alf45tar** [comment]
Yes, sure.

**Comment by jimhiggs** [comment]
I do not fully understand step by step functionality. Will need to play with it.
One quick question is continuously saving the config bad for the memory? Should I try to use apply  and only save less frequently?

**Comment by alf45tar** [comment]
You can use Apply of course but the EEPROM memory has a specified life of 100,000 write/erase cycles.
You cannot reach the limit using the Save button. You should press it around 27 times per day for the next 10 years.

**Comment by jimhiggs** [comment]
Great, thanks for the extra info. I will close this now.

**Comment by jimhiggs** [comment]
I should have tried before closing. How can I use latch functionality using a sequence. i am not seeing it.

**Comment by alf45tar** [comment]
Use "Step by Step+" Action selecting the Sequence with the 2 CC.

**Comment by jimhiggs** [comment]
Magic. I understand step by step now. Very useful

**Comment by jimhiggs** [comment]
So I have Tag 1 set to Normal and Tag2 set to Bright in the Action (No :). The contents of Tag2 is shown above the bank name and is shown for both steps set in the sequence. Tag1 set in the Actions is ignored. 
Also when I started with the Blueboard config, Bright was displayed above the bank name but highlighted when on. I have not been able to achieve that with actions I have created.

**Comment by alf45tar** [comment]
You are right. Both are limits of the current design.

**Comment by alf45tar** [comment]
In version 3.0.10 Tag1 is for odd sequence numbers, Tag2 is for even sequence numbers.

**Comment by jimhiggs** [comment]
Thanks. When building 3.10 I get an Error:The program size (2023402 bytes) is greater than maximum allowed (1900544 bytes)

**Comment by alf45tar** [comment]
Fixed.

**Comment by jimhiggs** [comment]
Thanks.

**Comment by jimhiggs** [comment]
I have a ladder switch configured as both a press and a long press but when I do the long press it does the short press action and then the long press action. is there something I should configure to prevent this ?

**Comment by jimhiggs** [comment]
Tried double click and it does the same. I should add, the single press action is a 2 step sequence. On long press or double click It is performing the 1st step of the sequence (I can tell by the display showing the cc info, which it does not display usually when I single press) and then it does the long press (or double click action) after.

**Comment by jimhiggs** [comment]
From monitoring.
So it seems  where a press action and a log press action is declared for a switch a long press will perform the action of the short press and then the action of the long press.
Changing the press to a click action we only get the long press action.
Assuming this is how it woks we should not have a press action and a long press on the same control and instead use a click and a long press?

Results of monitoring.
action set as press
on single press
[3842687] Pedal/Button: 2/1     EventType: Press             ButtonState: 0
Action Delay On....SEQUENCE.....Number  5.....Step  2
CONTROL CHANGE.....Code  28......Value 127.....Channel  1
LED COLOR.....Led  9......RGB Color #001100
--------------------------------------------------
[3842850] Pedal/Button: 2/1     EventType: Release           ButtonState: 1
[3843252] Pedal/Button: 2/1     EventType: Click             ButtonState: 1

on long press
[3855926] Pedal/Button: 2/1     EventType: Press             ButtonState: 0
Action Delay On....SEQUENCE.....Number  5.....Step  1
CONTROL CHANGE.....Code  28......Value   0.....Channel  1
LED COLOR.....Led  9......RGB Color #000000
--------------------------------------------------
[3856427] Pedal/Button: 2/1     EventType: LongPress         ButtonState: 0
Action ....BANK+.....10
[3856841] Pedal/Button: 2/1     EventType: LongReleased      ButtonState: 1

Action set as click
on click
[3070132] Pedal/Button: 2/1     EventType: Press             ButtonState: 0
[3070247] Pedal/Button: 2/1     EventType: Release           ButtonState: 1
[3070647] Pedal/Button: 2/1     EventType: Click             ButtonState: 1
Action Delay On....SEQUENCE.....Number  5.....Step  2
CONTROL CHANGE.....Code  28......Value 127.....Channel  1
LED COLOR.....Led  9......RGB Color #001100
--------------------------------------------------

on long press
[3075457] Pedal/Button: 2/1     EventType: Press             ButtonState: 0
[3075957] Pedal/Button: 2/1     EventType: LongPress         ButtonState: 0
Action ....BANK+.....10
[3076457] Pedal/Button: 2/1     EventType: RepeatPressed     ButtonState: 0
[3076653] Pedal/Button: 2/1     EventType: LongReleased      ButtonState: 1

**Comment by jimhiggs** [comment]
Sorry about the bold text, i did not set it ab cant edit it to normal text

**Comment by alf45tar** [comment]
If you want to use Long or Double Press you have to replace Press with Click. The reason is simple. Click is triggered when 2 events occur: a Press and Release within a configurable interval. Once release a long press cannot happen anymore but a double press can.
The result you can have 3 events on a single button: Click, Double press and Long Press.

**Comment by jimhiggs** [comment]
Excellent . I am sure that explanation will help others when searching for help.

**Comment by alf45tar** [comment]
If you interested of latch emulation with momentary switches you get a try to version 3.1.0.

**Comment by jimhiggs** [comment]
OK will give it a try now. Thanks.

**Comment by jimhiggs** [comment]
Works great. Easier to configure than Step by Step+ an now i wont need so many sequences.

**Comment by jimhiggs** [comment]
I spoke too soon. It does not work if you press another button in between. So if I latch a switch on,  the next time I press it will latch off. OK
But if I press on switch A (on) then press on a different switch in the same ladder it fires the release of the second switch and not the press. If I then press the first switch again it fires the press, not the release.
So basically if you press on buttons 1 to 6 in a ladder in a row it will alternate between press and release actions rather than a on press for each (assuming they were all in an off state). Hope I have explained this right.

**Comment by alf45tar** [comment]
Fixed in version 3.1.1

**Comment by jimhiggs** [comment]
Confirmed. Will carry on testing.
