### ISSUE TITLE
2.5.4 Missing features

### ISSUE THREAD

**Issue by Ratterbass** [alf45tar/PedalinoMini#432]
I have tried installing the sponsor version firmware both via platformIo and via webinstaller+manual update, but there seem to be some features missing. 

1) I can't find send control snap under actions
2) I can't find simultaneous button press under triggers

Is there something missing in the installation files, do I have a bug? User error?

Thanks in advance!

![image](https://user-images.githubusercontent.com/121395227/221408300-d06f065f-fb50-463b-9d93-655f268be344.png)
![image](https://user-images.githubusercontent.com/121395227/221408347-28fae4e3-7f70-46b0-bc86-badb0ee95d90.png)
![image](https://user-images.githubusercontent.com/121395227/221408354-af6e9439-b137-46c2-8ee8-05e3921e6380.png)
![image](https://user-images.githubusercontent.com/121395227/221408390-bc95a542-a8db-4735-8f5e-4cda069a081f.png)

**Comment by alf45tar** [comment]
2.5.4 is the public version. The latest sponsor version is 3.1.1 available here https://github.com/pedalino-sponsors/PedalinoMini.

**Comment by Ratterbass** [comment]
> 2.5.4 is the public version. The latest sponsor version is 3.1.1 available here https://github.com/pedalino-sponsors/PedalinoMini.

I don't see anything more recent than 2.5.4 in that repo. 
![image](https://user-images.githubusercontent.com/121395227/221558300-d220a5e3-19c0-45c0-8b79-7388a83f46af.png)

When I manually build 3.1.1 from the src files and upload it to the ESP, the chip is stuck in a bootloop:

![image](https://user-images.githubusercontent.com/121395227/221567487-a71c5d21-1239-473a-b124-de9c67ebaa4b.png)

The manually built firmware.bin file is just over 2M, so manual update through the webUI doesn't work either. 

Any ideas?

**Comment by alf45tar** [comment]
Did you follow the instructions https://github.com/alf45tar/PedalinoMini#how-to-build-and-upload?
Just replace the repository to clone.

**Comment by Ratterbass** [comment]
Yes, I did. I deleted the whole thing and tried both manual download as well as git:clone. 

Always the same result: boot loop

**Comment by alf45tar** [comment]
Did you reset EEPROM to factory default?

**Comment by Ratterbass** [comment]
I redid the whole procedure, including flash erase on a windows PC instead of a Mac and it went smoothly and the controller is now running. 

Seems like MacOS (13.2.1) needs some special attention when flashing?

**Comment by alf45tar** [comment]
Weird because I am on MacOS 13.2.1 too.

**Comment by alf45tar** [comment]
In the next version I will delete ports from platform.ini because auto detection works fine.
