### ISSUE TITLE
Restart the device after pressing the buttons

### ISSUE THREAD

**Issue by e36910** [alf45tar/PedalinoMini#433]
After switching presses I see the same problem, the device restarts, sometimes it works fine, and sometimes by pressing a button the device restarts, I thought that the problem was with the board, but when I replaced it, the problem remained the same. Buttons are soldered through the resistors 10k in series, no problems with the power supply, tried through the usb and through the pin 5v solder. What can be the problem?

**Comment by alf45tar** [comment]
Can you post here the log?
The pull up resistor is not is not in serie. However is should not be the reason of restart.

**Comment by e36910** [comment]
My example - https://youtu.be/Fg-qYdnU9uI

**Comment by e36910** [comment]
how to create log?

**Comment by alf45tar** [comment]
The debug information are printed automatically on USB UART. You can use Visual Studio Code and Monitor option or any other program can read the serial port via USB.

**Comment by e36910** [comment]
I don't know how to do it

**Comment by e36910** [comment]
PROGRAM CHANGE.....Program   0.....Channel  1
Pedal: 1     Button: 2    EventType: 1     ButtonState: 1
Pedal: 2     Button: 2    EventType: 0     ButtonState: 0
Action: 1
CONTROL CHANGE.....Code   1......Value   0.....Channel  1
LED COLOR.....Led  0......RGB Color #050005
Pedal: 2     Button: 2    EventType: 1     ButtonState: 1
Pedal: 2     Button: 3    EventType: 0     ButtonState: 0
Action: 2
CONTROL CHANGE.....Code   2......Value   0.....Channel  1
LED COLOR.....Led  0......RGB Color #000505
Pedal: 2     Button: 3    EventType: 1     ButtonState: 1
Pedal: 2     Button: 3    EventType: 0     ButtonState: 0
Action: 2
CONTROL CHANGE.....Code   2......Value 127.....Channel  1
LED COLOR.....Led  0......RGB Color #000505
Pedal: 2     Button: 3    EventType: 1     ButtonState: 1
Pedal: 2     Button: 3    EventType: 2     ButtonState: 1
Pedal: 2     Button: 4    EventType: 0     ButtonState: 0
Action: 3
CONTROL CHANGE.....Code   3......Value 127.....Channel  1
LED COLOR.....Led  0......RGB Color #050400
Pedal: 2     Button: 4    EventType: 1     ButtonState: 1
Pedal: 1     Button: 2    EventType: 0     ButtonState: 0
Action: A
PROGRAM CHANGE.....Program   0.....Channel  1
Pedal: 1     Button: 2    EventType: 1     ButtonState: 1
Pedal: 1     Button: 3    EventType: 0     ButtonState: 0
Action: B
PROGRAM CHANGE.....Program   1.....Channel  1
Pedal: 1     Button: 3    EventType: 1     ButtonState: 1
Pedal: 1     Button: 3    EventType: 2     ButtonState: 1
Pedal: 1     Button: 4    EventType: 0     ButtonState: 0
Action: C
PROGRAM CHANGE.....Program   2.....Channel  1
Pedal: 1     Button: 4    EventType: 1     ButtonState: 1
Pedal: 1     Button: 3    EventType: 0     ButtonState: 0
Action: B
PROGRAM CHANGE.....Program   1.....Channel  1
Pedal: 1     Button: 3    EventType: 1     ButtonState: 1
Pedal: 1     Button: 3    EventType: 2     ButtonState: 1
Pedal: 2     Button: 3    EventType: 0     ButtonState: 0
Action: 2
CONTROL CHANGE.....Code   2......Value   0.....Channel  1
LED COLOR.....Led  0......RGB Color #000505
Pedal: 2     Button: 3    EventType: 1     ButtonState: 1
Pedal: 2     Button: 3    EventType: 2     ButtonState: 1
Pedal: 1     Button: 2    EventType: 0     ButtonState: 0
Action: A
PROGRAM CHANGE.....Program   0.....Channel  1
Pedal: 1     Button: 2    EventType: 1     ButtonState: 1
Pedal: 1     Button: 3    EventType: 0     ButtonState: 0
Action: B
PROGRAM CHANGE.....Program   1.....Channel  1
Pedal: 1     Button: 3    EventType: 1     ButtonState: 1
Pedal: 2     Button: 4    EventType: 0     ButtonState: 0
Action: 3
CONTROL CHANGE.....Code   3......Value   0.....Channel  1
LED COLOR.....Led  0......RGB Color #050400
Pedal: 2     Button: 4    EventType: 1     ButtonState: 1
Pedal: 1     Button: 4    EventType: 0     ButtonState: 0
Action: C
PROGRAM CHANGE.....Program   2.....Channel  1
Pedal: 1     Button: 4    EventType: 1     ButtonState: 1
Pedal: 1     Button: 2    EventType: 0     ButtonState: 0
Action: A
PROGRAM CHANGE.....Program   0.....Channel  1
Pedal: 1     Button: 2    EventType: 1     ButtonState: 1
Pedal: 1     Button: 4    EventType: 0     ButtonState: 0
Action: C
PROGRAM CHANGE.....Program   2.....Channel  1
Pedal: 1     Button: 4    EventType: 1     ButtonState: 1
Pedal: 1     Button: 5    EventType: 0     ButtonState: 0
Action: D
PROGRAM CHANGE.....Program   3.....Channel  1
Pedal: 1     Button: 5    EventType: 1     ButtonState: 1
Pedal: 1     Button: 5    EventType: 2     ButtonState: 1
Pedal: 2     Button: 2    EventType: 0     ButtonState: 0
Action: 1
CONTROL CHANGE.....Code   1......Value 127.....Channel  1
LED COLOR.....Led  0......RGB Color #050005
Pedal: 2     Button: 2    EventType: 1     ButtonState: 1
Pedal: 2     Button: 3    EventType: 0     ButtonState: 0
Action: 2
CONTROL CHANGE.....Code   2......Value 127.....Channel  1
LED COLOR.....Led  0......RGB Color #000505
Pedal: 2     Button: 3    EventType: 1     ButtonState: 1
Pedal: 1     Button: 2    EventType: 0     ButtonState: 0
Action: A
PROGRAM CHANGE.....Program   0.....Channel  1
Pedal: 2     Button: 3    EventType: 2     ButtonState: 1
Pedal: 1     Button: 2    EventType: 1     ButtonState: 1
Pedal: 2     Button: 4    EventType: 0     ButtonState: 0
Action: 3
CONTROL CHANGE.....Code   3......Value 127.....Channel  1
LED COLOR.....Led  0......RGB Color #050400
Pedal: 2     Button: 4    EventType: 1     ButtonState: 1
Pedal: 1     Button: 3    EventType: 0     ButtonState: 0
Action: B
PROGRAM CHANGE.....Program   1.....Channel  1
Pedal: 1     Button: 3    EventType: 1     ButtonState: 1
Pedal: 2     Button: 4    EventType: 0     ButtonState: 0
Action: 3
CONTROL CHANGE.....Code   3......Value   0.....Channel  1
LED COLOR.....Led  0......RGB Color #050400
Pedal: 1     Button: 3    EventType: 2     ButtonState: 1
Pedal: 2     Button: 4    EventType: 1     ButtonState: 1
Pedal: 1     Button: 4    EventType: 0     ButtonState: 0
Action: C
PROGRAM CHANGE.....Program   2.....Channel  1
Pedal: 1     Button: 4    EventType: 1     ButtonState: 1
Pedal: 1     Button: 5    EventType: 0     ButtonState: 0
Action: D
PROGRAM CHANGE.....Program   3.....Channel  1
Pedal: 1     Button: 5    EventType: 1     ButtonState: 1
Pedal: 2     Button: 4    EventType: 0     ButtonState: 0
Action: 3
CONTROL CHANGE.....Code   3......Value 127.....Channel  1
LED COLOR.....Led  0......RGB Color #050400
Pedal: 2     Button: 4    EventType: 1     ButtonState: 1
Pedal: 2     Button: 2    EventType: 0     ButtonState: 0
Action: 1
CONTROL CHANGE.....Code   1......Value   0.....Channel  1
LED COLOR.....Led  0......RGB Color #050005
Pedal: 2     Button: 2    EventType: 1     ButtonState: 1
Pedal: 2     Button: 3    EventType: 0     ButtonState: 0
Action: 2
CONTROL CHANGE.....Code   2......Value   0.....Channel  1
LED COLOR.....Led  0......RGB Color #000505
Pedal: 2     Button: 3    EventType: 1     ButtonState: 1
Pedal: 1     Button: 2    EventType: 0     ButtonState: 0
Action: A
PROGRAM CHANGE.....Program   0.....Channel  1
Pedal: 2     Button: 2    EventType: 0     ButtonState: 0
Action: 1
CONTROL CHANGE.....Code   1......Value 127.....Channel  1
LED COLOR.....Led  0......RGB Color #050005
Pedal: 2     Button: 2    EventType: 1     ButtonState: 1
Pedal: 1     Button: 2    EventType: 1     ButtonState: 1
Pedal: 2     Button: 2    EventType: 2     ButtonState: 1
Pedal: 1     Button: 3    EventType: 0     ButtonState: 0
Action: B
PROGRAM CHANGE.....Program   1.....Channel  1
Pedal: 1     Button: 3    EventType: 1     ButtonState: 1
Pedal: 2     Button: 2    EventType: 0     ButtonState: 0
Action: 1
CONTROL CHANGE.....Code   1......Value   0.....Channel  1
LED COLOR.....Led  0......RGB Color #050005
Pedal: 2     Button: 2    EventType: 1     ButtonState: 1
Pedal: 1     Button: 4    EventType: 0     ButtonState: 0
Action: C
PROGRAM CHANGE.....Program   2.....Channel  1
Pedal: 1     Button: 4    EventType: 1     ButtonState: 1
Pedal: 2     Button: 3    EventType: 0     ButtonState: 0
Action: 2
CONTROL CHANGE.....Code   2......Value 127.....Channel  1
LED COLOR.....Led  0......RGB Color #000505
Pedal: 2     Button: 3    EventType: 1     ButtonState: 1
Pedal: 1     Button: 3    EventType: 0     ButtonState: 0
Action: B
PROGRAM CHANGE.....Program   1.....Channel  1
Pedal: 1     Button: 3    EventType: 1     ButtonState: 1
Pedal: 2     Button: 3    EventType: 0     ButtonState: 0
Action: 2
CONTROL CHANGE.....Code   2......Value   0.....Channel  1
LED COLOR.....Led  0......RGB Color #000505
Pedal: 2     Button: 3    EventType: 1     ButtonState: 1
Pedal: 2     Button: 2    EventType: 0     ButtonState: 0
Action: 1
CONTROL CHANGE.....Code   1......Value 127.....Channel  1
LED COLOR.....Led  0......RGB Color #050005
Pedal: 2     Button: 2    EventType: 1     ButtonState: 1
Pedal: 1     Button: 2    EventType: 0     ButtonState: 0
Action: A
PROGRAM CHANGE.....Program   0.....Channel  1
Pedal: 1     Button: 2    EventType: 1     ButtonState: 1
Pedal: 1     Button: 3    EventType: 0     ButtonState: 0
Action: B
PROGRAM CHANGE.....Program   1.....Channel  1
Pedal: 1     Button: 3    EventType: 1     ButtonState: 1
ets Jul 29 2019 12:21:46

rst:0x1 (POWERON_RESET),boot:0x12 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:10124
load:0x40080400,len:5828
entry 0x400806a8
ChipRevision 3, CPU Freq 240 MHz, SDK Version v3.3.5-1-g85c43024c
Flash Size 4194304, Flash Speed 40000000 Hz
Internal Total Heap 260088, Internal Free Heap 231140
PSRAM Total Heap 0, PSRAM Free Heap 0
nvs Total 65536
PlatformIO Built Environment: esp32doit-devkit-v1
_________           .___      .__  .__                 _____  .__       .__     ___ ________________    ___
\______  \ ____   __| _/____  |  | |__| ____   ____   /     \ |__| ____ |__|   /  / \__    ___/     \   \  \ 
|     ___// __ \ / __ |\__  \ |  | |  |/    \ /  _ \ /  \ /  \|  |/    \|  |  /  /    |    | /  \ /  \   \  \
|    |   \  ___// /_/ | / __ \|  |_|  |   |  (  <_> )    Y    \  |   |  \  | (  (     |    |/    Y    \   )  )
|____|    \___  >____ |(____  /____/__|___|  /\____/\____|__  /__|___|  /__|  \  \    |____|\____|__  /  /  / 
              \/     \/     \/             \/               \/        \/       \__\                 \/  /__/
                                                                                  (c) 2018-2022 alf45star      
                                                                      https://github.com/alf45tar/PedalinoMini

Hostname: EBD82240
PSRAM not found
Bluetooth Classic disabled: 15248 bytes released
Internal Total Heap 275424, Internal Free Heap 246292
PSRAM Total Heap 0, PSRAM Free Heap 0
SPIFFS mount OK
'nvs' partition was successfully initialized
Reading NVS Global ... done
[NVS][Global][Device Name]:      Melatonin
[NVS][Global][Boot Mode]:        4
[NVS][Global][STA SSID]:         WiFrier
[NVS][Global][STA Password]:     123qweasdzxc
[NVS][Global][AP SSID]:          MelatoninPedals
[NVS][Global][AP Password]:      1234567890
[NVS][Global][HTTP Username]:    admin
[NVS][Global][HTTP Password]:    1234567890
[NVS][Global][Bootstrap Theme]:  bootstrap
[NVS][Global][Current Profile]:  0
[NVS][Global][Flip Screen]:      1
[NVS][Global][Tap Dance Mode]:   0
[NVS][Global][Bank Switch]:      0
[NVS][Global][Single Time]:      200
[NVS][Global][Double Time]:      400
[NVS][Global][Long   Time]:      500
[NVS][Global][Repeat Time]:      500
[NVS][Global][Encoder Sensit]:   5
[NVS][Global][RGB Order]:        10
[NVS][Global][LedsOnBright]:     5
[NVS][Global][LedsOffBright]:    5
[NVS][Global][OSCLocalPort]:     8000
[NVS][Global][OSCRemoteHost]:    255.255.255.255
[NVS][Global][OSCRemotePort]:    9000
[NVS][Global][Ladder]:           Ladder 1 Level 350
[NVS][Global][Ladder]:           Ladder 2 Level 500
[NVS][Global][Ladder]:           Ladder 3 Level 650
[NVS][Global][Ladder]:           Ladder 4 Level 725
[NVS][Global][Ladder]:           Ladder 5 Level 780
[NVS][Global][Ladder]:           Ladder 6 Level 850

Boot AP+BLE
Loading profile 0 ...
Reading NVS Profile A ... done
Bank  2
Pedal  1        1   LADDER             PRESS_1       POLARITY+   PROGRAM_CHANGE       0   Channel  1   Pin A36 D25
Pedal  2        1   LADDER             PRESS_1       POLARITY+   CONTROL_CHANGE       1   Channel  1   Pin A39 D26
Pedal  3     None   ANALOG                           POLARITY+      Channel  1   Pin A34 D27
Pedal  4     None                                    POLARITY+      Channel  1
Pedal  5     None                                    POLARITY+      Channel  1
Pedal  6     None                                    POLARITY+      Channel  1
Pedal  7     None                                    POLARITY+      Channel  1
MTC None
... profile 0 loaded.
USB MIDI started
DIN MIDI started
BLE MIDI service advertising started
Skipped connection to last AP and/or SmartConfig/WPS setup
SYSTEM_EVENT_WIFI_READY
AP MelatoninPedals started with password 1234567890
AP SSID     : MelatoninPedals
AP PSK      : 1234567890
AP MAC      : 40:22:D8:EB:1D:45
AP IP       : 192.168.4.1
SYSTEM_EVENT_AP_STOP
SYSTEM_EVENT_AP_START
SYSTEM_EVENT_AP_START
Channel     : 1
Connect to MelatoninPedals wireless network with password 1234567890
mDNS responder started
HTTP server started on port 80
Connect to http://Melatonin.local/update for firmware update
Connect to http://Melatonin.local for configuration
ipMIDI started
RTP-MIDI started on port 5004
OSC server started on port 8000
Internal Total Heap 269248, Internal Free Heap 97704
SYSTEM_EVENT_STA_START
SYSTEM_EVENT_SCAN_DONE

**Comment by e36910** [comment]
![image](https://user-images.githubusercontent.com/85799952/222923043-e34560af-67c4-487e-821b-d4e944e63e17.png)

**Comment by e36910** [comment]
![image](https://user-images.githubusercontent.com/85799952/222923134-3c39902a-f230-4cb5-859f-3e9549c9aa70.png)

**Comment by alf45tar** [comment]
It looks like it is not connected with the software because I do not see any software exception error like "division by zero" or "illegal address".
It is a normal log when someone pressed the reset. I suggest to check your hardware connections, short circuit and power supply.
If you post some shots of internals I can have a look?

**Comment by e36910** [comment]
![IMG_20230305_120443_Mi9T_g8 4 LMC r9 v1](https://user-images.githubusercontent.com/85799952/222954337-a40fb238-a772-445a-ae15-a7349ba2f9fa.jpg)

**Comment by e36910** [comment]
![IMG_20230305_120453_Mi9T_g8 4 LMC r9 v1](https://user-images.githubusercontent.com/85799952/222954408-2666348a-46a0-4c31-a256-25431461e9f0.jpg)
