### ISSUE TITLE
Profile/Bank switch via external midi

### ISSUE THREAD

**Issue by Ratterbass** [alf45tar/PedalinoMini#436]
Feature request. Is it possible to switch banks and profiles via external midi? I saw it should be possible with OSC but not every device can send OSC. Is it possible in future version?

**Comment by alf45tar** [comment]
With the next version it will be possible.

CC 00 [1-3] profile switch
CC 32 [0-20] bank switch

Both on channel 16.

**Comment by alf45tar** [comment]
Released with version 3.1.2
