### ISSUE TITLE
STL files

### ISSUE THREAD

**Issue by itsptadeu** [alf45tar/PedalinoMini#439]
Hello my friend. How do I access Pedalino Mini Case 1 STL files? When I try to access it returns the error 404. I have already re-enabled the sponsorship with github, unfortunately it had stopped because github stopped accepting my paypal. Please, help me, I need these files urgently. If there's anything I can do to speed up the process, let me know.

**Comment by itsptadeu** [comment]
help me please! hehehe

**Comment by alf45tar** [comment]
Try now.

**Comment by itsptadeu** [comment]
Hi, my friend.

I'm trying to access the sponsor's repository but it gives a 404 error.

Thx.

Em qui., 16 de mar. de 2023 às 11:34, alf45tar ***@***.***>
escreveu:
