### ISSUE TITLE
Missing info on Schematic_PedalinoMini_Sheet-3.svg

### ISSUE THREAD

**Issue by Wapata** [alf45tar/PedalinoMini#449]
Hello !
My PedalinoMini bpi-leaf-s3 is on my wifi ! It seem it's a success so far.
But can you please add two words into the https://github.com/alf45tar/PedalinoMini/blob/master/images/Schematic_PedalinoMini_Sheet-3.svg shematic ?
I'm looking for "LADDER" and "LADDER 2" because of this paragraph : https://github.com/alf45tar/PedalinoMini#controls

Thanks a lot ! And bravo because it wasn't so hard to put PedalinoMini into the board using -nearly- only your explanations

**Comment by alf45tar** [comment]
LADDER 2 is an error. It doesn't exist. It should be LATCH 2.

**Comment by Wapata** [comment]
Oh. Nice then, thanks for thé answer :-)
