### ISSUE TITLE
Pedalino Mini as Wlan-Midi bridge

### ISSUE THREAD

**Issue by romakrau** [alf45tar/PedalinoMini#45]
Hi Alf45tar, Thanks for this great tool. It works out of the box for a small budget.
It is possible to use this ESP32-Dev kit also as MIDI bridge? I'm mean that on the instrument side we can use the DIN-MIDIin and MIDIout and receive the MIDI data via Wlan or Wifi by another ESP32-DEV with DIN MIDIin / MIDI out.
Greetings
Roman

**Comment by alf45tar** [comment]
Yes, it is possible via IPMIDI because it is a broadcast protocol.
Using rtpMIDI you need a computer (session listener) because PedalinoMini is a session initiator only.

**Comment by romakrau** [comment]
I tried to install rtpMIDI from tobias erichsen. I can see the pedalino but i have to prepare the midi connector for testing. Thanks for your quick response.
