### ISSUE TITLE
3.1.7 Firmware BUG

### ISSUE THREAD

**Issue by bobvc133** [alf45tar/PedalinoMini#458]
1. The length of the interface name is incorrect
2. Tag Settings are not displayed when PC instructions are sent
3. Disabling USB MIDI IN and OUT in Config.h does not take effect

![Snipaste_2023-08-25_11-41-05](https://github.com/alf45tar/PedalinoMini/assets/91867813/e7ebe8ef-d044-4141-8dc7-25edf3a95479)

![Snipaste_2023-08-25_11-41-58](https://github.com/alf45tar/PedalinoMini/assets/91867813/9574db7f-f616-413f-ab5b-d87d0a3df7a1)

![Snipaste_2023-08-25_14-02-03](https://github.com/alf45tar/PedalinoMini/assets/91867813/091808c2-bd72-4acd-827a-c24970337984)
![Snipaste_2023-08-25_14-03-19](https://github.com/alf45tar/PedalinoMini/assets/91867813/36729110-59fb-4011-a28a-ef25b4947ef8)

**Comment by alf45tar** [comment]
Version 3.1.8 just released fix the 3 bugs added in 3.1.7

**Comment by bobvc133** [comment]
> Version 3.1.8 just released fix the 3 bugs added in 3.1.7

Another problem was found that using the sequence function to send Bank Select+/- and Program Change+/- commands is incorrect

**Comment by alf45tar** [comment]
Thanks for debugging. I will have a look later today.

**Comment by alf45tar** [comment]
> > Version 3.1.8 just released fix the 3 bugs added in 3.1.7
> 
> Another problem was found that using the sequence function to send Bank Select+/- and Program Change+/- commands is incorrect

This is not really bug. It is not yet implemented.

**Comment by bobvc133** [comment]
> Thanks for debugging. I will have a look later today.

Another problem was discovered. There is no LED color item in the sequence after the configuration is saved.
![Snipaste_2023-09-09_12-01-49](https://github.com/alf45tar/PedalinoMini/assets/91867813/0bd39bf0-7cf9-45f7-aac2-350e93bc1ffd)

**Comment by alf45tar** [comment]
Thanks for debugging. Fixed in 3.1.9.
