### ISSUE TITLE
Build Issues

### ISSUE THREAD

**Issue by jaylfc** [alf45tar/PedalinoMini#460]
Hi,

I've been away from tinkering for a while and want to get this working on some newer boards. Ive been battling through build errors and missing libraries and found myself stuck at:

In file included from .pio/libdeps/bpi-leaf-s3/OSC/SLIPEncodedBluetoothSerial.cpp:1:
.pio/libdeps/bpi-leaf-s3/OSC/SLIPEncodedBluetoothSerial.h:11:10: fatal error: BluetoothSerial.h: No such file or directory

I've made a copy of it in the src file and vscode will follow the file link to edit it but it fails on build.

Latest versions of vscode and platformio on Mac OS Sonoma and Windows 11.

Pulling my hair out :(

Cheers,
Jay.

**Comment by jaylfc** [comment]
For what it's worth, a fresh clone and attempted build stops at this:

<command-line>: fatal error: /home/runner/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32s3/include/arduino_tinyusb/include/tusb_config.h: No such file or directory
compilation terminated.
Compiling .pio/build/bpi-leaf-s3/libe25/AsyncTCP/AsyncTCP.cpp.o
*** [.pio/build/bpi-leaf-s3/src/PedalinoMini.cpp.o] Error 1
================================== [FAILED] Took 6.00 seconds ==================================

Environment    Status    Duration
-------------  --------  ------------
bpi-leaf-s3    FAILED    00:00:05.996
============================= 1 failed, 0 succeeded in 00:00:05.996 =============================

 *  The terminal process "platformio 'run', '--environment', 'bpi-leaf-s3'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it.

**Comment by jaylfc** [comment]
When trying an esp32 device I get stuck here:

In file included from src/PedalinoMini.cpp:66:0:
src/WifiConnect.h: At global scope:
src/WifiConnect.h:35:25: warning: 'wpsConfig' defined but not used [-Wunused-variable]
 static esp_wps_config_t wpsConfig;
                         ^
*** [.pio/build/heltec_wifi_kit_32/src/PedalinoMini.cpp.o] Error 1
================================================================================================================================================================================================================================== [FAILED] Took 12.26 seconds ==================================================================================================================================================================================================================================

Environment         Status    Duration
------------------  --------  ------------
heltec_wifi_kit_32  FAILED    00:00:12.260

**Comment by alf45tar** [comment]
> For what it's worth, a fresh clone and attempted build stops at this:
> 
> : fatal error: /home/runner/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32s3/include/arduino_tinyusb/include/tusb_config.h: No such file or directory compilation terminated. Compiling .pio/build/bpi-leaf-s3/libe25/AsyncTCP/AsyncTCP.cpp.o *** [.pio/build/bpi-leaf-s3/src/PedalinoMini.cpp.o] Error 1 ================================== [FAILED] Took 6.00 seconds ==================================
> 
> Environment Status Duration
> 
> bpi-leaf-s3 FAILED 00:00:05.996 ============================= 1 failed, 0 succeeded in 00:00:05.996 =============================
> 
> * The terminal process "platformio 'run', '--environment', 'bpi-leaf-s3'" terminated with exit code: 1.
> * Terminal will be reused by tasks, press any key to close it.

/home/runner/ is the folder used by GitHub Actions. Your path of .platformio folder is different. It should be /Users/<your username>/.platformio

**Comment by jaylfc** [comment]
Thanks for helping, I can't seem to find what to change. There's no mention of any folders in there, I've been through every settings page and tried googling everything possible too. As I said been away from the for a while and I think I've forgotten too much!! Any ideas?

Much appreciated!

**Comment by jaylfc** [comment]
So I pushed through with a esp32dev build, figuring out what files were missing and putting them in the right folders and finally got a completed build. Guess I'll do the same with the other platforms I want. No idea what's going on here, multiple clean installs on different os's and same results??

**Comment by alf45tar** [comment]
> Thanks for helping, I can't seem to find what to change. There's no mention of any folders in there, I've been through every settings page and tried googling everything possible too. As I said been away from the for a while and I think I've forgotten too much!! Any ideas?
> 
> Much appreciated!

Check the file `platform.ini` in the top folder

**Comment by alf45tar** [comment]
> Hi,
> 
> I've been away from tinkering for a while and want to get this working on some newer boards. Ive been battling through build errors and missing libraries and found myself stuck at:
> 
> In file included from .pio/libdeps/bpi-leaf-s3/OSC/SLIPEncodedBluetoothSerial.cpp:1: .pio/libdeps/bpi-leaf-s3/OSC/SLIPEncodedBluetoothSerial.h:11:10: fatal error: BluetoothSerial.h: No such file or directory
> 
> I've made a copy of it in the src file and vscode will follow the file link to edit it but it fails on build.
> 
> Latest versions of vscode and platformio on Mac OS Sonoma and Windows 11.
> 
> Pulling my hair out :(
> 
> Cheers, Jay.

Fixed in latest version 3.1.8

**Comment by jaylfc** [comment]
Awesome thanks

**Comment by iammac360** [comment]
Where is version 3.1.8? can't find it in the tags or under releases

**Comment by alf45tar** [comment]
https://github.com/pedalino-sponsors/PedalinoMini/tree/3.1.8
