### ISSUE TITLE
3.2.0 Firmware issues

### ISSUE THREAD

**Issue by bobvc133** [alf45tar/PedalinoMini#464]
1.Because creating a new configuration will cause a restart, I used JSON Editor to create a complete configuration, which can be imported, applied and saved. However, it will still restart when I create a new configuration again, and the new configuration is still incomplete.（Fixed, spiffs occupancy rate is too high resulting in）

[FM3(complete).txt](https://github.com/alf45tar/PedalinoMini/files/12645364/FM3.complete.txt)
[FM3(incomplete).txt](https://github.com/alf45tar/PedalinoMini/files/12645365/FM3.incomplete.txt)

2.When configuring an analog pedal in a bank other than the global bank, the corresponding LED will light up by default.

![Snipaste_2023-09-18_15-42-45](https://github.com/alf45tar/PedalinoMini/assets/91867813/22b42341-0e96-43e6-a914-d931aa8a06df)

3.Incomplete message types in configuration editor ,Some event sending content is empty after creating a new configuration, and the JSON Editor has no option to edit and save.@alf45tar 

![Snipaste_2023-10-15_12-31-14](https://github.com/alf45tar/PedalinoMini/assets/91867813/5fe29b02-039b-48ae-99f6-54b31581b489)
![20231015124325](https://github.com/alf45tar/PedalinoMini/assets/91867813/195d5c6e-c0b7-4470-afef-90c88f7ec0a4)

4.When the sequence is configured with 10 steps, the Step by Step- event will not go backwards when it reaches the 10th step, and step 1 of the Step by Step+ and Step by Step- events on the action page will be automatically modified to 255.（It has been fixed）
![Snipaste_2023-10-25_01-33-14](https://github.com/alf45tar/PedalinoMini/assets/91867813/31a01555-752e-40bf-b89d-99b63d045452)
![Snipaste_2023-10-25_01-32-23](https://github.com/alf45tar/PedalinoMini/assets/91867813/453a53b4-9b56-4e03-9224-995ce705df67)

**Comment by alf45tar** [comment]
Can you explain point 2?

**Comment by bobvc133** [comment]
> global

Configure the analog pedal in BANK1-20, and the corresponding LED will light up by default, just like adding a (.) ending to the action tag, and set the corresponding LED and color at startup.

**Comment by bobvc133** [comment]
> Can you explain point 2?

Configure the analog pedal in BANK1-20, and the corresponding LED will light up by default, just like adding a (.) ending to the action tag, and set the corresponding LED and color at startup.

**Comment by bobvc133** [comment]
What is missing in the third question is not only the items in the red box, but also actions such as Repeat and Repeat Overwrite.

**Comment by bobvc133** [comment]
In addition, how to use the OSC Message item in the event?
![Uploading Snipaste_2023-10-29_21-53-51.png…]()

**Comment by bobvc133** [comment]
Another problem was discovered. Starting from firmware 3.1.11, the configuration of the combined button controls is invalid, and the configuration of the single button controls in the combination is also invalid.

**Comment by bobvc133** [comment]
7. Regarding the third question, there are still inconsistencies in the codes related to actions and sequence events. Some of the names of schema.json, Config.h, and WebConfigAsync.h are different, and some are missing items. The picture below is a list of my statistics.

- None
- Program Change
- Control Change
- Control Change Snap
- Note On
- Note Off
- Bank Select+
- Bank Select-
- Program Change+
- Program Change-
- Pitch Bend
- Channel Pressure
- MIDI Clock Master
- MIDI Clock Slave
- MIDI Clock Off
- MIDI Start
- MIDI Stop
- MIDI Continue
- Sequence
- Step by Step+
- Step by Step-
- Bank+
- Bank-
- MTC Master
- MTC Slave
- MTC Off
- MTC Time Signature
- MTC Start
- MTC Stop
- MTC Continue
- Tap
- BPM+
- BPM-
- OSC Message
- Profile+
- Profile-
- Set Led Color
- Repeat
- Repeat Overwrite
- Device Info
- Power On/Off

**Comment by alf45tar** [comment]
7. Fixed inconsistence in version 3.1.14 (not yet released)

**Comment by bobvc133** [comment]
> 7. Fixed inconsistence in version 3.1.14 (not yet released)

8.When editing the pedal pressing mode in jsoneditor, an error message will appear when changing the mode 12L to 1, 2, or 12. There is no problem when selecting the L, 1L, or 2L options.
![Uploading Snipaste_2023-12-09_21-59-05.png…]()
![Uploading Snipaste_2023-12-09_21-59-35.png…]()
![Uploading Snipaste_2023-12-09_21-59-51.png…]()

**Comment by bobvc133** [comment]
> 7. Fixed inconsistence in version 3.1.14 (not yet released)

8.When editing the pedal pressing mode in jsoneditor, an error message will appear when changing the mode 12L to 1, 2, or 12. There is no problem when selecting the L, 1L, or 2L options.
![Snipaste_2023-12-09_21-59-05](https://github.com/alf45tar/PedalinoMini/assets/91867813/9ef5171a-bc6a-4fec-8c35-c30936980078)
![Snipaste_2023-12-09_21-59-35](https://github.com/alf45tar/PedalinoMini/assets/91867813/6a696e74-c992-4931-9749-dd6179932c42)
![Snipaste_2023-12-09_21-59-51](https://github.com/alf45tar/PedalinoMini/assets/91867813/bddf0380-2e0e-4078-bdfb-ecbd43a32547)

**Comment by alf45tar** [comment]
It is not a PedalinoMini issue but a Json Editor feature explained here how to use it https://github.com/josdejong/jsoneditor/issues/1541#issuecomment-1653919721

**Comment by bobvc133** [comment]
> 7. Fixed inconsistence in version 3.1.14 (not yet released)

The action code of the 3.2.0 firmware is still confusing in many places, such as "MIDI Off" and "MIDI Clock Off", "Start", "Stop", "Continue" and "MTC Start", "MTC Stop"," MTC Continue".

![Snipaste_2023-12-24_13-22-42](https://github.com/alf45tar/PedalinoMini/assets/91867813/95306613-4c8b-4e0b-bf91-e0d85833d20e)
![Snipaste_2023-12-24_13-24-12](https://github.com/alf45tar/PedalinoMini/assets/91867813/8d8077b0-ecf1-47e3-a4ef-e6d573ea468f)
![Snipaste_2023-12-24_13-25-46](https://github.com/alf45tar/PedalinoMini/assets/91867813/0aa99754-e771-46e4-990d-cf292133e6cb)
![Snipaste_2023-12-24_13-26-01](https://github.com/alf45tar/PedalinoMini/assets/91867813/bd4dbc92-a6b3-4598-841a-392d68a69779)
![Snipaste_2023-12-24_13-26-28](https://github.com/alf45tar/PedalinoMini/assets/91867813/c7cd691d-3c3c-4d51-9e06-9fd1820dae8d)
![Snipaste_2023-12-24_13-26-54](https://github.com/alf45tar/PedalinoMini/assets/91867813/07b128a6-42f6-4735-b624-b9314edf6d7c)

**Comment by bobvc133** [comment]
![Snipaste_2023-12-24_20-56-36](https://github.com/alf45tar/PedalinoMini/assets/91867813/27f52803-f8d5-4fb5-87a1-c129281e89ed)
![Snipaste_2023-12-24_20-56-52](https://github.com/alf45tar/PedalinoMini/assets/91867813/397e64e3-df98-4a8f-af3d-0c80a3c799c4)

**Comment by bobvc133** [comment]
![Snipaste_2023-12-24_21-00-21](https://github.com/alf45tar/PedalinoMini/assets/91867813/835a1da2-2d47-4bbc-8638-f59cab713fbe)
![Snipaste_2023-12-24_21-01-08](https://github.com/alf45tar/PedalinoMini/assets/91867813/e6f02cbc-ca7c-4e92-9974-eee128b1a882)

**Comment by bobvc133** [comment]
Except for the fourth and seventh problems above, the rest still exist in the 3.2.0 firmware.

**Comment by alf45tar** [comment]
Renamed "MIDI off" to "MIDI Clock Off" into `schema.json`.
The rest looks good enough to me.

Did you discovered any bug?

**Comment by bobvc133** [comment]
> Renamed "MIDI off" to "MIDI Clock Off" into `schema.json`. The rest looks good enough to me.
> 
> Did you discovered any bug?

https://github.com/alf45tar/PedalinoMini/issues/464#issuecomment-1868563838
![Snipaste_2023-12-25_01-39-09](https://github.com/alf45tar/PedalinoMini/assets/91867813/bdb02f2d-e9da-4c39-83c6-77a1f3c53162)

**Comment by bobvc133** [comment]
> Renamed "MIDI off" to "MIDI Clock Off" into `schema.json`. The rest looks good enough to me.
> 
> Did you discovered any bug?

1. You can select "MTC Start", "MTC Stop", "MTC Continue" and other events on the action page. After creating a new configuration, JSON Editor will prompt an invalid project because there is no corresponding "MTC Start" in the "schema.json" file. , "MTC Stop", "MTC Continue" and other projects. This is the same problem as the lack of "Repeat" and "Repeat Overwrite" projects mentioned before. Although the action page can select events and apply them and save them to the current configuration, after creating a new configuration, JSON Editor An error will be prompted, and when the application is saved to other BANK, an error will appear that the corresponding event is empty.
2. In the code about the sequence part of the WebConfigAsync.h file, you can see that the event options are "MIDI Start", "MIDI Stop", and "MIDI Continue", but in the relevant condition code, you can see "MTC Start". "MTC Stop", "MTC Continue" and other events, I'm not sure if this is a bug.

![Uploading Snipaste_2023-12-25_01-39-09.png…]()

**Comment by alf45tar** [comment]
Got it. It will fixed in 3.2.1

**Comment by alf45tar** [comment]
Problem 1. I cannot duplicate. I can upload FM3 config file and then save a new configuration without reboot on my T-Display board.

**Comment by bobvc133** [comment]
> Problem 1. I cannot duplicate. I can upload FM3 config file and then save a new configuration without reboot on my T-Display board.

After many tests, this problem seems to be caused by the high SPIFFS utilization, because sometimes the new configuration is large, or there are multiple configurations in the configuration list. When the SPIFFS utilization reaches 60%~80%, when the new configuration is created, The probability of a reboot or incomplete configuration is high. Although you can delete other configurations or create new configurations by category, PedalinoMini's 3 user profiles and 21 BANKs will be meaningless because you cannot create so many configurations. In addition, when the BANK takes up a lot, it will have a significant impact on the response speed of the controls. . I don't know if this problem can be improved. In addition, the sixth question is whether it can be fixed in the next version of the firmware. This has a great impact on me. Both the two-button controls and the single-button controls currently cannot be used normally.

**Comment by alf45tar** [comment]
Did you considered to increase the SPIFFS size?

**Comment by alf45tar** [comment]
Can you clarify "Both the two-button controls and the single-button controls currently cannot be used normally."?

**Comment by bobvc133** [comment]
> Can you clarify "Both the two-button controls and the single-button controls currently cannot be used normally."?

This problem has appeared since firmware 3.1.11. Take the following figure as an example. When controls 4, 16, and 6 are all configured with actions, the actions of controls 4, 16, and 6 will not take effect. Delete the action of control 6, and the actions of controls 4 and 16 can take effect normally. Delete the actions of controls 4 and 16, and control 6 can be used normally. 

![292672798-1440c09c-1c71-4b9d-9728-150508114a3a](https://github.com/alf45tar/PedalinoMini/assets/91867813/19d62dd3-49d7-49b6-8873-65ba4ceb50c7)

**Comment by bobvc133** [comment]
> Did you considered to increase the SPIFFS size?

Ready to replace the development board with a larger memory

**Comment by bobvc133** [comment]
![Uploading Snipaste_2023-12-28_20-32-43.png…]()

**Comment by bobvc133** [comment]
![Snipaste_2023-12-28_20-32-43](https://github.com/alf45tar/PedalinoMini/assets/91867813/24cbb210-6198-4994-98c6-0db9a7ecc0d8)
![Snipaste_2023-12-28_20-34-17](https://github.com/alf45tar/PedalinoMini/assets/91867813/2ee3e8cc-056b-4977-a1d7-1855be12edd3)

**Comment by alf45tar** [comment]
> > Did you considered to increase the SPIFFS size?
> 
> I am going to replace the 16MB development board. How can I allocate the flash partition size more reasonably? Can you create a partition table for me?

Sure. Which is your board? How many space do you want for SPIFFS?

**Comment by alf45tar** [comment]
Assuming BPI-Leaf-S3 here the partition table file `partitions_bpi_leaf_se.csv` for a SPIFFS of 2112 Kb.
```
# Name,   Type, SubType,  Offset,   Size,     Flags
nvs0,     data, nvs,      0x9000,   0x5000,
otadata,  data, ota,      0xE000,   0x2000,
app0,     app,  ota_0,    0x10000,  0x2E0000,
app1,     app,  ota_1,    0x2F0000, 0x2E0000,
nvs,      data, nvs,      0x5D0000, 0x10000,
spiffs,   data, spiffs,   0x5E0000, 0x210000,
coredump, data, coredump, 0x7F0000, 0x10000,
```

**Comment by bobvc133** [comment]
> > > Did you considered to increase the SPIFFS size?
> > 
> > 
> > I am going to replace the 16MB development board. How can I allocate the flash partition size more reasonably? Can you create a partition table for me?
> 
> Sure. Which is your board? How many space do you want for SPIFFS?

I am currently using TTGO_T_DISPLAY, BPI_LEAF_S3, and LILYGO_T_DISPLAY_S3, three development boards, with 4MB and 8MB specifications. I plan to replace them all with 16mb SPI flash. The largest single configuration file I need to use is 20 BANKs. If I save 3 user profiles , how much space SPIFFS should be allocated when there are 60 banks in total? Another question is, if I use 16MB for development, will there be enough memory to add the page turning keystrokes function? Many times the music scores I use are in image format, and I use the photo album of the iPad to view them, and there are other applications that do not support MIDI control.

**Comment by alf45tar** [comment]
It found this sheet that can build the partition table for you (it is not mine)
https://docs.google.com/spreadsheets/d/1M6_qx00ZR82jyWa2slCMcvLtnXR9Q9dnis5mR5YChW8/edit#gid=0

**Comment by bobvc133** [comment]
> It found this sheet that can build the partition table for you (it is not mine) https://docs.google.com/spreadsheets/d/1M6_qx00ZR82jyWa2slCMcvLtnXR9Q9dnis5mR5YChW8/edit#gid=0
> 
> Also this app can be useful https://esp32.jgarrettcorbin.com

I re-partitioned the TTGO_T_DISPLAY 4MB development board and the BPI_LEAF_S3 16MB development board. The following is the partition table.
![Snipaste_2024-01-04_00-45-49](https://github.com/alf45tar/PedalinoMini/assets/91867813/f12849f8-aff4-4f15-9b82-78e782fa18c4)
![Snipaste_2024-01-04_00-46-56](https://github.com/alf45tar/PedalinoMini/assets/91867813/920400bd-8105-4ea0-82c3-c6902155b54d)

**Comment by bobvc133** [comment]
> Can you clarify "Both the two-button controls and the single-button controls currently cannot be used normally."?

In 3.2.2 firmware, the problem of control conflict still exists. A button cannot appear in two controls, otherwise both controls will become invalid.

![292672798-1440c09c-1c71-4b9d-9728-150508114a3a](https://github.com/alf45tar/PedalinoMini/assets/91867813/19d62dd3-49d7-49b6-8873-65ba4ceb50c7)
![292672806-a7ad9175-09ce-43e8-85ca-ab9287190736 (1)](https://github.com/alf45tar/PedalinoMini/assets/91867813/8ade9222-0f8e-492d-8286-6341aef58612)
