### ISSUE TITLE
New design 260 x 80 x 26 mm

### ISSUE THREAD

**Issue by alf45tar** [alf45tar/PedalinoMini#468]
@joegriffinable please add here your requisition for the customized PedalinoMini Case1 design

**Comment by joegriffinable** [comment]
Hello,
Not much change from the original design,
I have these to fit inside:
[image0.jpeg]

I tried to print the original version and came across a few issues:
Couldn’t fit the screen in, couldn’t fit MIDI ports.
I’ve bought an arduino mega to fit in and also a Battery case/charge.

The original design was slightly too big,
Please could the dimensions be 8cm/20cm (ok with the height at 3/4cm)


Joe Griffin

On 4 Oct 2023, at 10:02, alf45tar ***@***.***> wrote:

﻿

@joegriffinable<https://github.com/joegriffinable> please add here your requisition for the customized PedalinoMini Case1 design

**Comment by jisv48** [comment]
Here is my requisition for the original case...Hopefully indicates that, just lt me know how much it will cost.  Cheers

**Comment by alf45tar** [comment]
PedalinoMini Case 1 is designed for TTGO TDisplay only which include the battery recharge too.
Arduino Mega is not supported by PedalinoMini.

Dimension cannot be reduced to 8 cm (check the images). There is no space to allocate for the display.

**Comment by joegriffinable** [comment]
Thanks,
I’ll scrap the mega arduino, I thought I could get midi over usb through it.
Is there a way of extending the width of the pedal to 25cm(max.) and reducing to 8cm to accommodate the screen and buttons? Im just trying to squeeze it into a very compact pedalboard!
Thanks

Joe Griffin

On 4 Oct 2023, at 21:03, alf45tar ***@***.***> wrote:

﻿

PedalinoMini Case 1 is designed for TTGO TDisplay only which include the battery recharge too.
Arduino Mega is not supported by PedalinoMini.

Dimension cannot be reduced to 8 cm (check the images). There is no space to allocate for the display.

**Comment by alf45tar** [comment]
The minimum dimension are 265 x 80 mm.
Where can I send/upload the files?

**Comment by joegriffinable** [comment]
Thanks,
I’m not sure where to send them! How do you normally do it?
Thanks

Joe Griffin

On 6 Oct 2023, at 21:53, alf45tar ***@***.***> wrote:

﻿

The minimum dimensions are 265 x 80 mm.
Where can I send/upload the files?

**Comment by alf45tar** [comment]
I can send by email or if you want to share your design with sponsors I can upload on github.

**Comment by joegriffinable** [comment]
I’m happy with sharing!
Please upload on GitHub,
Cheers

Joe Griffin

On 8 Oct 2023, at 13:53, alf45tar ***@***.***> wrote:

﻿

I can send by email or if you want to share your design with sponsors I can upload on github.

**Comment by alf45tar** [comment]
https://github.com/pedalino-sponsors/PedalinoMini/tree/master/case1
