### ISSUE TITLE
Switches not working

### ISSUE THREAD

**Issue by mrybas** [alf45tar/PedalinoMini#470]
Hi! I assembled everything according to the scheme https://github.com/alf45tar/PedalinoMini-Case-1 and the bottom row of buttons (1a,2a,3a,4a) work perfectly. But the top buttons don't work.
 Assembled on the board TTGO T-DISPLAY

**Comment by alf45tar** [comment]
did you load the case1 configuration file?

**Comment by alf45tar** [comment]
Pedals from 1 to 4 need to be configured as Latch 2.

**Comment by mrybas** [comment]
yes, I'm  loaded the case1 configuration file. I'm configured pedals from 1 to 4 to be configured as Latch 2, now pedals 1-4, and 10 working. But 7-9 still not work 
Here is my setting
<img width="1730" alt="image" src="https://github.com/alf45tar/PedalinoMini/assets/18303152/639f3132-afb0-4e7d-9dd1-9673271cfccb">
<img width="1118" alt="image" src="https://github.com/alf45tar/PedalinoMini/assets/18303152/fef1e465-93fc-4777-891c-45aa895a929f">
<img width="895" alt="image" src="https://github.com/alf45tar/PedalinoMini/assets/18303152/9d9f0731-7d49-49c4-b2b3-ff65a5e278c1">
<img width="856" alt="image" src="https://github.com/alf45tar/PedalinoMini/assets/18303152/96422aec-a0bd-4618-8f20-6960f4ebd2d5">

**Comment by mrybas** [comment]
I completely rebuilt the entire circuit and now all the buttons work perfectly. It looks like the problem was a bad connection somewhere on the +3 volt line. Everything works great! Thanks for the help!
