### ISSUE TITLE
Cannot save or load configurations on S3

### ISSUE THREAD

**Issue by maarthome** [alf45tar/PedalinoMini#473]
Hi Alf45tar,

I noticed that I cannot save or load configurations on the S3...? It would be great if this is made possible again.
Also only 1 LED is defined for the BPI_LEAF_S3 in 'Pedalino.h':

#elif defined ARDUINO_BPI_LEAF_S3           // https://wiki.banana-pi.org/BPI-Leaf-S3
#undef  LEDS
#define LEDS                  1

Thanks for your incredible work!

Regards,
Maarten

**Comment by Designbase** [comment]
Dank je voor je bericht!

Ik ben met vakantie tot en met 20 November.

De mail wordt gelezen en mochten er calamiteiten zijn dan zal ik actie ondernemen!

Met vriendelijke Groet,

Ronald Westland
Designbase

**Comment by Jelle7and9** [comment]
Same for me also. Firmware 3.1.13 and BPI leaf S3

**Comment by maarthome** [comment]
Hi Alf45tar,

I recompiled the code and now it is OK :-)
I can load and save configurations!!

Thanks again for this great project!

Regards,
Maarten
