### ISSUE TITLE
Missing libs by build with VS Code see comment 4 and follow

### ISSUE THREAD

**Issue by WernAir77** [alf45tar/PedalinoMini#474]
Hi,

I tried to use a SH1106 OLED display with the web installer on a ESP32, like for ESP32_DOIT_DEV_Kit_1, but I only see a small clear line downside and the rest is snowy ;) 

I tried with and without pull ups and 5V instead of 3v3, but nothing changed. 

Is there a solution? For some years I installed pedalino with VS Code and could change between SD1306 and SH1106, but actually I can't use this workaround, because many libs are missing when I clone from git and follow the description.

**Comment by WernAir77** [comment]
Today I tried the TTGO T-EIGHT 3.1.6 and what should I say, the display works fine but I can't get any access to the web interface or wifi config. 
I also tried several versions of the ESP_32_DOIT_DEV_Kit_1 but with the same result, the display shows a small line and the rest is snowy.

**Comment by Jelle7and9** [comment]
One condition is that you build, upload and _upload filesystem image_ in PlatformIO. The last one is important for the correct WebUI experience.
Do you connect to the WebUI via the Pedalino installer https://alf45tar.github.io/PedalinoMini/installer
It is explained in the Readme

**Comment by WernAir77** [comment]
Yes, I connect via the WebUI after installation of DEV_DOIT_Kit_1, with TTGO_T-EIGHT, I was not able to connect Wifi.

**Comment by WernAir77** [comment]
Sorry for spamming, but I'm lost.
Were can I find bluetoothSerial.h, FastLED.h, Improv.h, HSCR04.h, and so on? I just follow the instruction but these libs are missing and I don't know were to search for...

**Comment by wcraffonara** [comment]
Hi,
  I also tried to compile the project and I've exactly the same issues with missing libs. It would be very nice to have some instruction how to get the libs. Thanks!
Regards

**Comment by alf45tar** [comment]
The lib issue has ben fixed in sponsor version since long time. It will be fixed in public version too when one of the goal will be reached.
