### ISSUE TITLE
LILYGO T-Display-S3 On-Device Button functionality

### ISSUE THREAD

**Issue by Pedalnetics** [alf45tar/PedalinoMini#477]
I just programmed a LILYGO T-Display-S3 via the sponsors repo (if this is not the right place for issues, please redirect me), and it appears the on-device buttons are not functioning properly/as documented.

The boot button does not do anything after bootup; during bootup,it does properly skip steps like Wifi/Smart/etc; I can also hold it on-power-up to boot the special modes.

Once the device is booted and displaying the bank screen, the boot button no longer does anything. There is another on-device button the docs call IO14; this does move forward profiles with a single click, but none of the other functions work: double-press to go back a profile, or long-hold to change/scroll through the display pages. (The RST button does reset the device, and the boot button does nothing at this point).

**Comment by alf45tar** [comment]
Yes, it is the right place for issues.

T-Display-S3 has no default configuration for the moment because it is in early stage of development. You have to created yourself the Actions.

**Comment by Pedalnetics** [comment]
![C38](https://github.com/alf45tar/PedalinoMini/assets/142960765/0fdaeb8e-00b5-459f-a225-726e24ce95a1)
There does seem to be a global action already defined for this (I didn't add these), so maybe it was commited by accident/wasn't fully working? If I change what Press does, it responds as-expected (i.e. if I change Press to Device Info, it does change the display to device info).
However neither Double Press or Long Press seem to work

**Comment by jaylfc** [comment]
Could you elaborate a little on how to setup the buttons, or best to just wait for an update? Cheers!

**Comment by alf45tar** [comment]
<img width="1352" alt="Screenshot 2023-12-15 at 21 27 27" src="https://github.com/alf45tar/PedalinoMini/assets/35426671/18d323aa-0c0a-4aa6-9e19-78cd75010bd7">

**Comment by jaylfc** [comment]
Thanks, I'll give it a try :)

**Comment by alf45tar** [comment]
Added same default config of T-Display for T-Display-S3 in 3.2.0
