### ISSUE TITLE
tag 3.2.0 requires $TMPDIR to build?

### ISSUE THREAD

**Issue by zavorra** [alf45tar/PedalinoMini#483]
Just checked out latest update on sponsor repo

if I just do "pio run" I get

```
PermissionError: Traceback (most recent call last):
  File "/usr/lib64/python3.12/pathlib.py", line 1311, in mkdir
    os.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/PedalinoMini/libdeps/lilygo-t-display-s3'

. . .

```

looking at platformio.ini I noticed that it refers to some env variable called TMPDIR. Defining that variable build succeeds.

**Comment by alf45tar** [comment]
It depends of your OS. It works on macOS and Windows but not in some Linux flavour. For example Ubuntu do not defines TMPDIR.
