### ISSUE TITLE
Heltec Wi-Fi Kit "not supported" error

### ISSUE THREAD

**Issue by Pedalnetics** [alf45tar/PedalinoMini#484]
When trying to flash via the PedalinoMini site, it throws the error "Your ESP32-S3 board is not supported."

Heltec looks to have have updated their Wi-Fi Kit from v2 to v3 (https://heltec.org/project/wifi-kit32-v3/), which changed the processor from an ESP32-D0 to ESP32-S3.

Boot logs:
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x1 (POWERON),boot:0x8 (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3808,len:0x43c
load:0x403c9700,len:0xbec
load:0x403cc700,len:0x2a3c
SHA-256 comparison failed:
Calculated: dcde8d8a4817d9bf5d5d69a7247667264e4e10ac7493514868b61f5aa6146539
Expected: ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
Attempting to boot anyway...
entry 0x403c98d8

**Comment by alf45tar** [comment]
Heltec Wi-Fi Kit v3 is a different board not supported by PedalinoMini. You can try with the firmware for BPI Leaf S3 and some changes in `Pedalino.h`.
