### ISSUE TITLE
Only 1 LED defined for ARDUINO_BPI_LEAF_S3? Is this intensional?

### ISSUE THREAD

**Issue by maarthome** [alf45tar/PedalinoMini#487]
Hi Alf45tar,

There is only 1 LED defined in '/src/Pedalino.h'. Is this on purpose?

#elif defined ARDUINO_BPI_LEAF_S3
#undef  LEDS
#define LEDS                  1

Would be great to have the pre-compiled with 10 LED's, like like for the other processors.

Thanks for this wonderful project!!

**Comment by alf45tar** [comment]
No problem. I can do it.
The only reason it that there are only one led connect to GPIO48.

**Comment by maarthome** [comment]
Great! Thanks a lot!
Best wishes for 2024!
(next time I'll use a spelling checker... :-) )
