### ISSUE TITLE
BPI Leaf S3 FW_3.2.1

### ISSUE THREAD

**Issue by Jelle7and9** [alf45tar/PedalinoMini#493]
Hi Alf45tar,

The pre configured firmware for ESP32 BPI Leaf S3 gives me some issues. 

Pin A4(14), A5(15) and A6(16) do not work as to be aspected, they have double functions. 
Battery pin, SDA and SCL.

See also #454 for suggestions

**Comment by alf45tar** [comment]
Solved with 3.2.2
