### ISSUE TITLE
Increse number of SEQUENCES not applied to combo box

### ISSUE THREAD

**Issue by wcraffonara** [alf45tar/PedalinoMini#497]
Hi,
  if you change the number of SEQUENCES to 
#define SEQUENCES        30

then you can define 30 different sequences in the <Sequences> page but you cannot select a sequence > 16 in the combo box within the Actions page. It seems like the const SEQUENCES is not used in the creation of the combo box.

Regards
Walter

**Comment by alf45tar** [comment]
Fixed in 3.2.4
