### ISSUE TITLE
first led doesn't work since 3.2.2 Lilygo T Display S3

### ISSUE THREAD

**Issue by DxC82** [alf45tar/PedalinoMini#502]
I built the Pedalinomini 4.  unfortunately the 7 LEDs are not assigned correctly.  If the first one should light up, the 2nd one lights up, the third one instead of the 2nd and so on.

**Comment by alf45tar** [comment]
Are you saying that led number 1 is the second, led 2 is the third, etc. and you cannot light up first led?

**Comment by DxC82** [comment]
Yeah right.  The number of LEDs cannot be changed via the html configuration.  The number 10 always remains.

**Comment by DxC82** [comment]
Already after flashing, in the first boot phase, the first LED is omitted.  in version 2.3.1 it still lights up.  from version 2.3.2 no longer.

**Comment by DxC82** [comment]
I flashed version 2.3.1 again.  4 controls, 4 actions with PC, led on and led off. led 7 for button 1. led 5 for button 2, led 3 for button 3 and led 1 for button 1. the LEDs come on correctly but don't go off when switching.
attached the config file. 
[config.zip](https://github.com/alf45tar/PedalinoMini/files/14551461/config.zip)

**Comment by alf45tar** [comment]
Leds are numbered from right to left to simplify the internal connections.
I confirm there is an issue with PC and leds.

**Comment by alf45tar** [comment]
As a temporary fix add your PC actions on a different bank. They are not light off led when used in bank 0.

**Comment by alf45tar** [comment]
Fix in 3.2.9 just released

**Comment by alf45tar** [comment]
Are you using a WS2812B led strip?

**Comment by DxC82** [comment]
Yes.
WS2812B LED Strip, 
Model: BTF-5V-030L-B 
FNSKU: X000U6VGJV 
SKU: WS2812B5M30LB30
5 Meter Roll.

**Comment by DxC82** [comment]
The problem only exists with my Lilygo T-Display S3 (PedalinoMini 4 project).  My Lilygo T display works.

**Comment by alf45tar** [comment]
Check the connections. Can you post some shots?

**Comment by DxC82** [comment]
![17104519111825446123599878072588](https://github.com/alf45tar/PedalinoMini/assets/113459859/3ba3e37e-fdb7-433d-88a8-ab9484d1ee92)

**Comment by alf45tar** [comment]
Connections look good. I do not think it is a board issue.

**Comment by alf45tar** [comment]
Did you try to upload any example from FastLed library?

**Comment by DxC82** [comment]
You're right, it's not the board.  new board and the same error.  There must be something wrong with the board-specific configuration, right?
![17105262922718164820339204133357](https://github.com/alf45tar/PedalinoMini/assets/113459859/0bf0edf6-532e-485b-80b1-f290222a7366)
The first LED is also left out there.

**Comment by DxC82** [comment]
I haven't tried any other code yet.  I'll test FastLED examples right away.

**Comment by DxC82** [comment]
The Adafruit NeoPixel  buttoncycler works! 
![Uploading 17106822481501509452767641208590.jpg…]()


![17106820865997689035467118456238](https://github.com/alf45tar/PedalinoMini/assets/113459859/6c692f04-15b7-4b9b-b361-e2ae852b9fae)


https://github.com/alf45tar/PedalinoMini/assets/113459859/a24ebce9-d16f-4183-a708-40377242e681

**Comment by DxC82** [comment]
https://github.com/alf45tar/PedalinoMini/assets/113459859/287b1d7d-d7fa-4297-96df-46de6c03b5ba

**Comment by DxC82** [comment]
sorry for closing and opening. the LEDs were too bright, I hit the wrong button.

**Comment by DxC82** [comment]
The FastLED example ColorPalette works too! 

![17106830466096016647957505037511](https://github.com/alf45tar/PedalinoMini/assets/113459859/69994a23-6193-4deb-95df-c98811782a18)


https://github.com/alf45tar/PedalinoMini/assets/113459859/20c0a0c6-be2c-4ad2-8ce3-98783ed3d795

**Comment by DxC82** [comment]
Works with WS2812 and WS2812B , 7 or 10 Num_Leds.. 
![17106834949625283617338321019053](https://github.com/alf45tar/PedalinoMini/assets/113459859/179a19e9-f7ca-4ec8-b0a9-d795e29d8fee)

**Comment by alf45tar** [comment]
Can you try the blueboard4 configuration from latest firmware?

**Comment by DxC82** [comment]
Here with the config blueboard4. 

https://github.com/alf45tar/PedalinoMini/assets/113459859/271e385c-342c-4dea-85f7-beec12fb36a2

**Comment by alf45tar** [comment]
Doest it work in 3.2.1?

**Comment by DxC82** [comment]
Yes on 3.2.1 first led works. Since 3.2.2 doesn't, like the videos..

**Comment by alf45tar** [comment]
I retested again my PedalinoMini 4 with 3.2.1 and 3.2.2 and latest firmware and there is no difference for led 1.
Very hard to debug this issue.

**Comment by DxC82** [comment]
I retested again, too.. 
3.2.1 led order OK. 
![IMG_20240402_173512](https://github.com/alf45tar/PedalinoMini/assets/113459859/74d55874-c40c-428f-bd4b-e96c8556142a)


3.2.2 led order wrong. First led without function. 
![IMG_20240402_173830](https://github.com/alf45tar/PedalinoMini/assets/113459859/dd72c085-6d20-4c75-917a-08f52b60f404)

![IMG_20240402_173958](https://github.com/alf45tar/PedalinoMini/assets/113459859/c3e99bcc-0f06-4e15-a7db-adb17e3897b0)


I can't believe I'm the only one with this problem..

**Comment by alf45tar** [comment]
I found the potential reason. Can you try to disable Legacy MIDI OUT?

**Comment by DxC82** [comment]
i disabled first the Lagacy Midi Out -- no change.
i disabled all Midi Interfaces exept BLE in and out -- no change

When booting, the first LED is already deactivated. Maybe this information will help

**Comment by DxC82** [comment]
I am currently on version 3.2.2

**Comment by DxC82** [comment]
I have now compiled version 3.3.0 with midi out on pin 21 (line 117 Pedalino.h)
and it works! I don't know if pin21 is a good choice, but here lies the mistake!

Only the html configurations page now looks strange in my test build..

**Comment by DxC82** [comment]
Thanks, the issue is fixed with 3.3.1
