### ISSUE TITLE
Please provide wiring diagram for PedalinoMini4

### ISSUE THREAD

**Issue by buzzyc** [alf45tar/PedalinoMini#504]
I am excited to build this device, however other than the 3D render, I cannot see any other wiring diagram.
This wouldn't be so bad if the render didn't obscure some of the wiring locations on the S3 shield.
Could you please provide a flat image of the wiring pinout for the S3 please?

Cheers :)

**Comment by mknerr** [comment]
The diagrams in the ReadMe don't suffice?

**Comment by buzzyc** [comment]
As per this image: 
https://github.com/alf45tar/PedalinoMini-4/blob/main/images/PedalinoMini%204%20Wiring.jpg

The top row is obscured. I could probably extrapolate, but it would be nice to not have to guess pinouts

**Comment by alf45tar** [comment]
![image](https://github.com/alf45tar/PedalinoMini/assets/35426671/cdea1fe2-e66d-4899-ae59-40bb2f6c64cc)

**Comment by buzzyc** [comment]
Thank you!

**Comment by alf45tar** [comment]
I updated the wiring image into the repository too.
