### ISSUE TITLE
WEB interface flashing firmware problem

### ISSUE THREAD

**Issue by jsonslim** [alf45tar/PedalinoMini#505]
Hello,
thanks for such a nice project!

The problem: after using the http://alf45tar.github.io/PedalinoMini/installer  and connecting the esp32 board to my router, the page by my address - http://116de378.local/    doesn't load, the browser shows this: 
![image](https://github.com/alf45tar/PedalinoMini/assets/20793480/d1a1a3c8-f892-4cb9-936b-7809c53831f5)

I can see the board in my home network with 192.168.0.46, and when i open the page, it shows this:  
![image](https://github.com/alf45tar/PedalinoMini/assets/20793480/c6046fef-2f5c-4302-b301-f2ba0b97681c)

Desired behavior: the page loads by http://116de378.local/ without  showing the banner with login and password. 
I think it's a good idea to not block a user from with the login/passwd banner, at the beginning. If it's an important feature for you, make the input form on the separate page, and only after the user enters custon login/pass the banner appearance makes sence.

Thanks!

**Comment by alf45tar** [comment]
Username is admin
Default password is 116DE378

Thanks for the suggestion to disable authentication on first login.

**Comment by jsonslim** [comment]
Thank you for the answer! 
After I wrote this issue I saw that the admin/pass instructions were written on the readme section. But the  http://116de378.local/    still doesn't load, it's a timeout problem...

**Comment by alf45tar** [comment]
I suggest to use some tool to debug mDNS/Bonjour/Zeroconf.
I am using https://itunes.apple.com/us/app/discovery-dns-sd-browser/id1381004916?mt=12 on macOS and 
https://www.tobias-erichsen.de/software/zeroconfservicebrowser.html on Windows.

**Comment by serhatsoyyigit** [comment]
This is very confusing. It makes no sense to have a mandatory password for the first installation. I've been trying to figure this out for hours and it doesn't say anywhere in the description. On the contrary, it says that no information is required for login.

How can you try so hard to make it simple and make such a mistake in this part?

**Comment by alf45tar** [comment]
Default password has been removed

**Comment by jsonslim** [comment]
That's great! Thank you!
