### ISSUE TITLE
PIN 12 HIGH on boot

### ISSUE THREAD

**Issue by upgrader-dev** [alf45tar/PedalinoMini#507]
Hello.

I'm bulding a simple Pedalino with 4 buttons.

The pedal 4 is linked to the PIN 12 on TTGO T-display.

But when I connect this PIN 12 to my footswitch, the boot is impossible.

If I switch to pedal 5, everything works flawlessly.

Lately I found this issue with LilYGO that says that PIN 12 HIGH is used to determine if boot lust be done from SD card.
https://github.com/LilyGO/TTGO-T5-ePaper1.54/issues/3

Found what the documentation says about that and this link below : 

https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/peripherals/sd_pullup_requirements.html#mtdi-strapping-pin

Still can't figure out how to connect pedal 4 without making a HIGH at boot on PIN 12 which activates the 1.8V regulator instead of the 3;3v I need

What do you guys think about that?

**Comment by upgrader-dev** [comment]
![image](https://github.com/alf45tar/PedalinoMini/assets/112260527/6fecda29-e93f-489d-8040-8208314d397c)

**Comment by alf45tar** [comment]
The permanent solution is here even if I am not using it on my board. 

https://github.com/espressif/esp-idf/tree/release/v3.2/examples/storage/sd_card#note-about-gpio12

**Comment by upgrader-dev** [comment]
Thank you. So, just to check I understood... I have to insert this line 
[    components/esptool_py/esptool/espefuse.py set_flash_voltage 3.3V]() in the right file to force the 3.3V function. 

Which file do I have to insert this line in?

**Comment by alf45tar** [comment]
I think it is an one time only command. Setting is permanent stored into efuse and cannot changed anymore.
