### ISSUE TITLE
Bank switch from web ui not working

### ISSUE THREAD

**Issue by dbosnyak** [alf45tar/PedalinoMini#55]
If I understand the UI correctly, when I am in the 'live' screen, there is a bank selection area, numbers 1-10 - however clicking these does not seem to change the bank on the device.

**Comment by alf45tar** [comment]
"Live" screen is still under development. For the moment it is better to NOT USE Live screen because it crash/reboot Pedalino.

**Comment by alf45tar** [comment]
"Live" screen is still under development but bank switch do no crash/reboot Pedalino.
