### ISSUE TITLE
Extra Buttons 

### ISSUE THREAD

**Issue by bauerbyter** [alf45tar/PedalinoMini#57]
Hello,
again: your Project is absolute awesome, thanks for all that work.
I am at the moment digging through your code  and found the PEDALS define in the config.h and in the readme you are writing "Each port can connect 1 expression pedal or up to 5 foot switches for a maximum of 30 foot switches"
So I am building myself a footcontroler but I wanted to have 15 Switches (and one espression Pedal) but I dont really get how to add more physical switches to your hardware. 

Thanks and greetings!
Bauerbyter

**Comment by alf45tar** [comment]
Use a voltage ladder as indicated into the schematic.

**Comment by bauerbyter** [comment]
A got it, sorry was blind! thanks for that.

**Comment by alf45tar** [comment]
Please share your project when done.

**Comment by bauerbyter** [comment]
Shure, will do!
