### ISSUE TITLE
Phantom inputs

### ISSUE THREAD

**Issue by timm052** [alf45tar/PedalinoMini#59]
Got the firmware falshed to the device but when it boots into the main screen the screen displays constant changes to the midi signal and rapidly switches between pages and values. I don't have any buttons plugged in and haven't connected to a network yet as i can't get the smart config or wpa button to work this might be connected to the random inputs putting it in wifi disabled boot mose etc. Do i need to have any buttons connected to get it to boot and avoid phantom input i had a go at connecting some but didn't seem to affect it?

![2020-01-09_14-16-08](https://user-images.githubusercontent.com/3995027/72035254-73d0f980-32eb-11ea-9a3f-50217ee57d95.gif)

**Comment by alf45tar** [comment]
By default pedal 5 and 6 are defined as Analog. Without a pull up resistor the value is not stable.
Add the 10k pull up resistors as indicated into the schematic or just connect to the web interface and setup as Momentary or Latch or None.
