### ISSUE TITLE
Touch sensitive behaviour Pin D18

### ISSUE THREAD

**Issue by Hans68** [alf45tar/PedalinoMini#63]
Hi alf45tar,

first of all again many thanks for this great project and your continous support. My Pedalino is nearly finished and working great. Attached a picture of my solution.
Now to the issue: 
I recognized a sensitive behaviour if I touched the non metal housing (glass fibre plastic) close to the region where the Pro micro is located. I got strange displays on the OLED. 
I solved this problem by adding a 100k resistor from D18 to ground. Perhaps helpful also for others.

Cheers
Hans
![IMG_2646](https://user-images.githubusercontent.com/48477907/73347772-738fa280-4288-11ea-868e-ea55fb506d5c.JPG)

**Comment by alf45tar** [comment]
Thanks for sharing your built. If you want to add photos from different point of view (inside included) it will be very appreciated.
Did you customized anything (apart the 100k resistor)?

**Comment by Hans68** [comment]
Hi,

Please find attached some more pictures and the circuit diagram.

Cheers
Hans

[Hans68 pedalinomini.pdf](https://github.com/alf45tar/PedalinoMini/files/4135089/Hans68.pedalinomini.pdf)
![IMG_2650](https://user-images.githubusercontent.com/48477907/73469296-6fe24580-4386-11ea-9e55-7be09ae2b0d0.JPG)
![IMG_2651](https://user-images.githubusercontent.com/48477907/73469298-6fe24580-4386-11ea-811e-b0d79fbf3c32.JPG)
![IMG_2652](https://user-images.githubusercontent.com/48477907/73469299-707adc00-4386-11ea-80eb-3f71e0c0034e.JPG)
![IMG_2654](https://user-images.githubusercontent.com/48477907/73469300-707adc00-4386-11ea-94ff-878929a83fd2.JPG)
![IMG_2657](https://user-images.githubusercontent.com/48477907/73469301-707adc00-4386-11ea-84ab-62dffe5cd554.JPG)
![IMG_2658](https://user-images.githubusercontent.com/48477907/73469302-71137280-4386-11ea-82c8-a4beeb11f48c.JPG)

**Comment by mknerr** [comment]
@Hans68 Nice work. Do you know yet what kind of battery life you are getting? And if you do, what mode are you using, for reference. Thanks!

**Comment by Hans68** [comment]
Hi,
I use "WiFi only" for configuration and "BLE only" mode for operation.  In
BLE mode with all LED's on I got a current of app. 280 mA measured directly
at the 18650 Lion battery with
2.600 mAh. So an operation of  >8 hours should be more than enough for one
Gig.
Cheers
Hans


Am Do., 30. Jan. 2020 um 23:33 Uhr schrieb mknerr <notifications@github.com

**Comment by mknerr** [comment]
Great. Thanks for the info.
