### ISSUE TITLE
Momentary 3

### ISSUE THREAD

**Issue by mknerr** [alf45tar/PedalinoMini#65]
I saw you recently changed the momentary switch behavior, and I think there could be an issue with Momentary 3 now. SW1 alternates between Value 1 and 2, but Sw2 and Sw3 only send value one on each press. Is that the intended behavior? Thanks!

**Comment by alf45tar** [comment]
Yes it is an issue because the code it is not yet updated for Momentary 2 and Momentary 3.
I gave priority to Momentary 1 and leds.

**Comment by mknerr** [comment]
Okay thank you for the info, and all the work in this project.

**Comment by alf45tar** [comment]
Version 2 just released solve the issue.

Thanks for patience
