### ISSUE TITLE
Long Press to send another Control Change/Note

### ISSUE THREAD

**Issue by iwbrhwfy-source** [alf45tar/PedalinoMini#68]
Thank you so much, but I think it would be great if 'long press'  send another Control Change/Note, not only send another Midi Value.
ex:
Single Press => CC60
Long Press => CC61

**Comment by iwbrhwfy-source** [comment]
And how to change Bank from 1-10 on Pedalion? I set Pedal Mode: Momentary, Pedal Function: Bank+1 but when i press Bank alway to A.10 and only can change via web config
Sorry for my English :D

**Comment by alf45tar** [comment]
Check Midi Value 1 and Midi Value 3. They are the lower and upper limit for bank change.

**Comment by iwbrhwfy-source** [comment]
> Check Midi Value 1 and Midi Value 3. They are the lower and upper limit for bank change.

Yes i find it :D this is my project :)))
![IMG_20200208_191215](https://user-images.githubusercontent.com/59449747/74086094-40cc8200-4ab2-11ea-9838-0b63ba4e61bb.jpg)
![IMG_20200208_191219](https://user-images.githubusercontent.com/59449747/74086097-475af980-4ab2-11ea-96d0-de395c74ce6c.jpg)

**Comment by alf45tar** [comment]
I was wrong of course. It is Min and Max the lower and upper limit of bank range.

**Comment by iwbrhwfy-source** [comment]
> Thank you so much, but I think it would be great if 'long press' send another Control Change/Note, not only send another Midi Value.
> ex:
> Single Press => CC60
> Long Press => CC61

is it easy to edit?

**Comment by alf45tar** [comment]
not so hard

**Comment by iwbrhwfy-source** [comment]
> not so hard
Yeah!!
My usbmidi project :D i can select present and turn on off effect with 4 button 
https://youtu.be/mLiJwjWkrs0

**Comment by iwbrhwfy-source** [comment]
> not so hard

i just temporary edit code and 4 button can send 8 diffrent CC  :D
![Screen Shot 2020-02-12 at 8 34 00 PM](https://user-images.githubusercontent.com/59449747/74339758-4b02bf00-4dd7-11ea-8b41-53091a8d2eea.png)
![Screen Shot 2020-02-12 at 8 36 25 PM](https://user-images.githubusercontent.com/59449747/74339796-5c4bcb80-4dd7-11ea-97c0-2664016915fb.png)

**Comment by alf45tar** [comment]
Solved on latest release 2.0
