### ISSUE TITLE
How to show Battery on OLED Display

### ISSUE THREAD

**Issue by iwbrhwfy-source** [alf45tar/PedalinoMini#71]
Hello sir
I use 4 AA Battery to VIN of esp32 devkit v1
Please teach me how to show battery status to OLED
My oled is blank at upper right corner

**Comment by alf45tar** [comment]
First of all you have to connect the VIN to a available PIN (for example GPIO_NUM_23) using a resistor divider.
Then modifiy Pedalino.h to define the correct BATTERY_PIN and other changes into DisplayOLED.h  as indicated here https://github.com/alf45tar/PedalinoMini/issues/58#issuecomment-579974881.
At the end add -D BATTERY on platformio.ini

**Comment by iwbrhwfy-source** [comment]
> First of all you have to connect the VIN to a available PIN (for example GPIO_NUM_23) using a resistor divider.
> Then modifiy Pedalino.h to define the correct BATTERY_PIN and other changes into DisplayOLED.h as indicated here [#58 (comment)](https://github.com/alf45tar/PedalinoMini/issues/58#issuecomment-579974881).
> At the end add -D BATTERY on platformio.ini

And maximum volt to GPIO_NUM_23 sir?

**Comment by alf45tar** [comment]
3.3V

**Comment by iwbrhwfy-source** [comment]
I used resistor divider same value=10k to gpio23
Then i edit code Battery bat(2000, 3000, GPIO_NUM_23) but i dont know why battery show 0mV :(

**Comment by iwbrhwfy-source** [comment]
![IMG_20200217_185840](https://user-images.githubusercontent.com/59449747/74651952-904c3580-51b7-11ea-89fc-c432611fa0e8.jpg)

**Comment by alf45tar** [comment]
Did you disconnected LEFT_PIN and RIGHT_PIN from GPIO_NUM_23 into Pedalino.h?

**Comment by juliowebhouse** [comment]
Hi alf45tar,

I followed the instructions to view the battery but it only shows a discharged battery (blinking).

Settings
Battery bat (3000, 5000, GPIO_NUM_23);

#define RIGHT_PIN GPIO_NUM_0
#define CENTER_PIN GPIO_NUM_0
#define LEFT_PIN GPIO_NUM_0

Connections
GPIO_NUM_23 Connected to VIN and Ground using a 10K resistor.

Can you help me? Thanks.

**Comment by iwbrhwfy-source** [comment]
> Hi alf45tar,
> 
> I followed the instructions to view the battery but it only shows a discharged battery (blinking).
> 
> Settings
> Battery bat (3000, 5000, GPIO_NUM_23);
> 
> #define RIGHT_PIN GPIO_NUM_0
> #define CENTER_PIN GPIO_NUM_0
> #define LEFT_PIN GPIO_NUM_0
> 
> Connections
> GPIO_NUM_23 Connected to VIN and Ground using a 10K resistor.
> 
> Can you help me? Thanks.

I try change pin 23 to another pin exam 34 and it work

**Comment by alf45tar** [comment]
The ESP32 has 18 x 12 bits ADC input channels. These are the GPIOs that can be used as ADC and respective channels:

ADC1_CH0 (GPIO 36)
ADC1_CH1 (GPIO 37)
ADC1_CH2 (GPIO 38)
ADC1_CH3 (GPIO 39)
ADC1_CH4 (GPIO 32)
ADC1_CH5 (GPIO 33)
ADC1_CH6 (GPIO 34)
ADC1_CH7 (GPIO 35)
ADC2_CH0 (GPIO 4)
ADC2_CH1 (GPIO 0)
ADC2_CH2 (GPIO 2)
ADC2_CH3 (GPIO 15)
ADC2_CH4 (GPIO 13)
ADC2_CH5 (GPIO 12)
ADC2_CH6 (GPIO 14)
ADC2_CH7 (GPIO 27)
ADC2_CH8 (GPIO 25)
ADC2_CH9 (GPIO 26)

ADC2 pins cannot be used when Wi-Fi is used. So, if you’re using Wi-Fi and you’re having trouble getting the value from an ADC2 GPIO, you may consider using an ADC1 GPIO instead, that should solve your problem.

**Comment by juliowebhouse** [comment]
alf45tar,

I set up the GPIO_NUM_36 and now it works, but I'm using a 5v voltage regulator connected to the VIN and a 9v battery and I can't find the right configuration, thanks anyway.

**Comment by alf45tar** [comment]
The BATTERY_PIN must be connected to battery output not to voltage regulator if you want measure  the battery voltage.

For more details follow the link
https://github.com/rlogiacco/BatterySense#9v-alkaline-on-5v-mcu
