### ISSUE TITLE
error on building - esp32doit-devkit-v1-wifi  

### ISSUE THREAD

**Issue by bogdancat** [alf45tar/PedalinoMini#72]
'ip_addr_t {aka struct ip_addr}' has no member named 'addr' several times
identifier "panic" is undefined   also severa times

Please advice.

**Comment by alf45tar** [comment]
It is a PlatformIO bug on latest release 4.2.0. Goto to PlatfomIo Community to have more details.
Solution: open PlatformIO IDE Terminal and type 'pio upgrade --dev'. Restart VSCode.

**Comment by alf45tar** [comment]
https://community.platformio.org/t/pio-4-2-0-complile-error-for-asynctcp-id1826/12025

**Comment by bogdancat** [comment]
Thank you for help. I will try tonight.

**Comment by alf45tar** [comment]
4.2.1 has been released and solve the issue.
