### ISSUE TITLE
Momentary2 Giving ON/OFF on press, Off on Release on A port.

### ISSUE THREAD

**Issue by jimhiggs** [alf45tar/PedalinoMini#74]
Monitor log message:
On press button (on pin_A1)
Pedal  1   input 0 output 0
NOTE ON.....Note   0.....Velocity   1.....Channel  1
NOTE OFF....Note   0......Velocity   2.....Channel  1
Pedal  1   input 1 output 1
NOTE OFF....Note   0......Velocity   2.....Channel  1
On press button (on pin_D1)
Pedal  1   input 0 output 0
NOTE ON.....Note   6.....Velocity   1.....Channel  1
Pedal  1   input 1 output 1
NOTE OFF....Note   6......Velocity   2.....Channel  1

Is this what is supposed to happen?  If not am I the only one experiencing this?

**Comment by alf45tar** [comment]
It has been fixed.
Thanks for your debugging.
