### ISSUE TITLE
Heltec WiFi V2 compatibility

### ISSUE THREAD

**Issue by jaylfc** [alf45tar/PedalinoMini#82]
Hi, sorry to comment on an old thread but I tried the above platformio.ini file and get immediate parser errors. Could you please help?

_Originally posted by @jaylfc in https://github.com/alf45tar/PedalinoMini/issues/8#issuecomment-593152223_

**Comment by alf45tar** [comment]
Helmec board is not officially supported because too much pins are used by the board itself.
The scope of this board is for different projects.
