### ISSUE TITLE
Additional function when press 2 button once time

### ISSUE THREAD

**Issue by iwbrhwfy-source** [alf45tar/PedalinoMini#87]
I hope new version you will enhance
I think it will save amount of push buttons.
Example button 1 and 2 for bank up, button 2 and 3 for bank down, button 1 and 2 and 3 for tuner :D
Thank you so much

**Comment by iwbrhwfy-source** [comment]
and button seem not debounce when i select Bank+1, Bank-1  mode (sometime it from bank 1 to bank 3 or 4 with 1 click)
it still ok when i select MIDI mode

**Comment by alf45tar** [comment]
Thanks for the suggestion.

Regarding your debounce issue please check your hardware and/or the software options. Whcih values are you using for Press Time, Double Press, Long Press and Repeat? Can you attach the the log?

Thanks
alf45tar

**Comment by iwbrhwfy-source** [comment]
Thank for your reply
Hardware still ok because a changed some button, and when i select MIDI mode everything very good, only bank+ bank - have issue (i set min 1, max 10)
All value Press Time, Double Press, Long Press and Repeat is default
And how to export the log :D

**Comment by iwbrhwfy-source** [comment]
https://youtu.be/wt8hBgezhzM
I don't extract log becase bank+ function not show on serial monitor @@

**Comment by alf45tar** [comment]
Thank you for the video. Very useful.
You are using a latch switch. Change Pedal Mode from Momentary to Latch.

**Comment by iwbrhwfy-source** [comment]
> Thank you for the video. Very useful.
> You are using a latch switch. Change Pedal Mode from Momentary to Latch.

No, it is momentary switch :D 
Midi function toggle between midi value 1 and midi value 2

**Comment by alf45tar** [comment]
Can you try with Latch setting?

**Comment by iwbrhwfy-source** [comment]
> Can you try with Latch 
https://youtu.be/VSq-OpDNgg8
Yes and i change to another button

**Comment by alf45tar** [comment]
Can you check and confirm the following value into Options?


![image](https://user-images.githubusercontent.com/35426671/76979687-965d3f80-6938-11ea-95a6-9be9f78c0335.png)

**Comment by iwbrhwfy-source** [comment]
> Can you check and confirm the following value into Options?
> 
> ![image](https://user-images.githubusercontent.com/35426671/76979687-965d3f80-6938-11ea-95a6-9be9f78c0335.png)

I just erase flash and upload lastest firmware and still have debounce issue
![Screen Shot 2020-03-19 at 12 14 23 AM](https://user-images.githubusercontent.com/59449747/76988035-b6abef00-6976-11ea-9d7e-1df5f0c9c822.png)

**Comment by iwbrhwfy-source** [comment]
> Can you check and confirm the following value into Options?
> 
> ![image](https://user-images.githubusercontent.com/35426671/76979687-965d3f80-6938-11ea-95a6-9be9f78c0335.png)

I still have issue  :((
https://youtu.be/4vpfVhldKb8

**Comment by alf45tar** [comment]
Let's suppose that your switches are more noisy than normal.
I suggest to increase the debouncing interval from 20 ms to 50 ms or more.

https://github.com/alf45tar/PedalinoMini/blob/0138b4f3c949a73c0d5f26d99fc8bcab838f8e12/src/Pedalino.h#L105

Try to comment the following line
https://github.com/alf45tar/PedalinoMini/blob/0138b4f3c949a73c0d5f26d99fc8bcab838f8e12/src/Pedalino.h#L106

and uncomment the next one
https://github.com/alf45tar/PedalinoMini/blob/0138b4f3c949a73c0d5f26d99fc8bcab838f8e12/src/Pedalino.h#L107

**Comment by iwbrhwfy-source** [comment]
> suppose

![Screen Shot 2020-03-21 at 11 08 25 PM](https://user-images.githubusercontent.com/59449747/77231011-c6237600-6bca-11ea-915d-8fe34254871d.png)
i still noise 
maybe i will try diffrent footswitch type

**Comment by iwbrhwfy-source** [comment]
But it always work OK with any funtion except (Midi+1 2 3...)
https://youtu.be/7t95DVEmuN0

**Comment by alf45tar** [comment]
Are you sure it works ok with MIDI function? 
Check the log if the MIDI message is sent only one time or 2 or more.

**Comment by iwbrhwfy-source** [comment]
> Are you sure it works ok with MIDI function?
> Check the log if the MIDI message is sent only one time or 2 or more.

log with 3 button
![Screen Shot 2020-03-22 at 8 10 41 AM](https://user-images.githubusercontent.com/59449747/77240108-b16bd000-6c14-11ea-8099-bdc5417112ca.png)

**Comment by alf45tar** [comment]
Did you modified my code?

**Comment by iwbrhwfy-source** [comment]
> Did you modified my code?

No sir i clone new code everyday to test, and in 2 esp32 board different, i will test in another PC

**Comment by iwbrhwfy-source** [comment]
> Did you modified my code?

I just change to another pc, install new VSC, clone new code and upload
It still error @@
https://youtu.be/7t95DVEmuN0

**Comment by iwbrhwfy-source** [comment]
![IMG_20200324_231354](https://user-images.githubusercontent.com/59449747/77450035-4c3af900-6e25-11ea-87b8-687a8c5c45ca.jpg)
Reason from my button sir, it ok with small button
But i still down know why code can debounce with MIDI function but can't debounce BANK function

**Comment by alf45tar** [comment]
I suggest to check the latest version 2.0 just released
