### ISSUE TITLE
Noise when connected to esp32

### ISSUE THREAD

**Issue by patricksebastien** [alf45tar/PedalinoMini#88]
Hi, I have so many questions... not sure if it's the right place to ask. Some of them are pretty basic. Anyway here we go with a first one.

I am using the wifi / access point, when connecting from my computer to Pedalino esp32, I receive a lots of Serial stuff on the log:
```
Received from Serial MIDI  NoteOff 0x00   Velocity 0x00   Channel 01
Received from Serial MIDI  NoteOff 0x00   Velocity 0x00   Channel 01
Received from Serial MIDI  NoteOff 0x04   Velocity 0x80   Channel 01
Received from Serial MIDI  NoteOff 0x40   Velocity 0x01   Channel 01
```

Did a video (the blue led is when connected):
https://imgur.com/JfDjeeS

I am using the esp32s, here's the pinout:
![esp32s](https://user-images.githubusercontent.com/441764/77115140-287e4a00-6a04-11ea-98ba-724a39a0e9be.jpg)

Let me know if there's a forum or a better place to ask questions.
Thanks!

**Comment by iwbrhwfy-source** [comment]
Sometime i have issue like you

**Comment by patricksebastien** [comment]
EDIT:
Touching GIOP15 flood the log too, so I disabled the serial_midi:
_PedalinoMini.cpp_
Line 365 //serial_midi_connect();
&
Line 492 //if (*_MIDI.read())

**Comment by mknerr** [comment]
https://github.com/alf45tar/PedalinoMini/issues/59#issue-547225208

**Comment by patricksebastien** [comment]
@mknerr yep thanks for pointing this information, will need to retest with the pull-up resistor on all ADC, but in my case I already disabled all the pedals using the web-config. I think it was related to the midi serial (maybe my devboard is not 100% compatible with the esp32dev)...

**Comment by iwbrhwfy-source** [comment]
In my case when i touch my hand to ground it will ok

**Comment by alf45tar** [comment]
I did some changes to the source code.
When a serial MIDI interface (USB or Legacy) is disabled as input the received data are not logged or show on OLED.

By default MIDI IN is disabled for USB and Legacy interfaces because not all are implementing them.
