### ISSUE TITLE
Separate program changes via double and long press

### ISSUE THREAD

**Issue by mknerr** [alf45tar/PedalinoMini#90]
In the same way you can with CCs, is it possible to have separate program changes via double and long press? Don’t think so, but thought I’d ask. Thanks!

**Comment by iwbrhwfy-source** [comment]
> In the same way you can with CCs, is it possible to have separate program changes via double and long press? Don’t think so, but thought I’d ask. Thanks!

you can edit some code, if longpress bank 1 it will send data in bank 5
![Screen Shot 2020-03-20 at 9 12 54 PM](https://user-images.githubusercontent.com/59449747/77171859-a0756e80-6aef-11ea-9b01-2562eca33bd5.png)

**Comment by mknerr** [comment]
Thank you, that could be an option. Would really like to keep the code stock, if possible, for now at least. 
I’d definitely like to get a handle on what is doing what at some point, though.

**Comment by alf45tar** [comment]
Added with the lastest version
