### ISSUE TITLE
.local mDNS discovery

### ISSUE THREAD

**Issue by bmarshall91** [alf45tar/PedalinoMini#94]
I cannot connect to the web UI using pedal_name.local but can only connect using the IP address. Is there something I’m doing wrong? 

Thanks

**Comment by alf45tar** [comment]
Are you using Win or Mac?
.local address is based on mdns discovery. Are PedalinoMini and your PC on the same network?
PedalinoMini is using 2.4GHZ wifi. If you PC is on 5GHz wifi mdns broadcast could not work.
Please confirm that your PC is connected to the same SSID wireless of PedalinoMini.

**Comment by bmarshall91** [comment]
Computer is a Mac, running on 5GHz on the same network. I'll change it and give it another try.

**Comment by alf45tar** [comment]
Connect your Mac on the same 2.4GHz wifi used by PedalinoMini and it works like a charm.
